### ISSUE TITLE
Drawable has unresolved theme attributes

### ISSUE THREAD

**Issue by christianlanz** [afollestad/material-dialogs#1002]
Hi, I use your material dialog builder class to show a basic text input dialog. But for a few days now (I think since the new support library update?) logcat keeps showing me this error when a dialog is shown.

Am I missing something? Might be an issue in your library.

**I am using the latest version of your library:**
```gradle
compile('com.github.afollestad.material-dialogs:core:0.8.5.6@aar') { transitive = true }
```

**This is my function (written in Kotlin):**
```kotlin
fun showWorkoutNoteDialog(context: Context, workout: Workout, onNoteAdded: (String) -> Unit) {
    MaterialDialog.Builder(context)
        .title(R.string.workout_note)
        .inputType(InputType.TYPE_CLASS_TEXT)
        .input(context.getString(R.string.workout_note_hint), workout.note, false, { dialog, input ->
          onNoteAdded.invoke(input.toString())
        })
        .positiveText(R.string.save)
        .negativeText(R.string.cancel)
        .show()
  }
```

**This is the logcat output:**
```kotlin
W/Resources: Drawable android:drawable/text_cursor_material has unresolved theme attributes! Consider using Resources.getDrawable(int, Theme) or Context.getDrawable(int).
                                                                      java.lang.RuntimeException
                                                                          at android.content.res.Resources.getDrawable(Resources.java:775)
                                                                          at android.support.v7.widget.TintResources.superGetDrawable(TintResources.java:48)
                                                                          at android.support.v7.widget.AppCompatDrawableManager.onDrawableLoadedFromResources(AppCompatDrawableManager.java:374)
                                                                          at android.support.v7.widget.TintResources.getDrawable(TintResources.java:44)
                                                                          at com.afollestad.materialdialogs.internal.MDTintHelper.setCursorTint(MDTintHelper.java:150)
                                                                          at com.afollestad.materialdialogs.internal.MDTintHelper.setTint(MDTintHelper.java:118)
                                                                          at com.afollestad.materialdialogs.DialogInit.setupInputDialog(DialogInit.java:428)
                                                                          at com.afollestad.materialdialogs.DialogInit.init(DialogInit.java:300)
                                                                          at com.afollestad.materialdialogs.MaterialDialog.<init>(MaterialDialog.java:96)
                                                                          at com.afollestad.materialdialogs.MaterialDialog$Builder.build(MaterialDialog.java:1335)
                                                                          at com.afollestad.materialdialogs.MaterialDialog$Builder.show(MaterialDialog.java:1340)
```

**Comment by afollestad** [comment]
You have to be using an old version somehow, it was fixed quite a while ago by using `ContextCompat.getDrawable(Context, int)` instead of `getResources().getDrawable(int)` (which is deprecated).

**Comment by frmz** [comment]
@afollestad was it fixed in 0.8.5.7? Because I am getting the very same issues on 0.8.5.6

**Comment by christianlanz** [comment]
@frmz After cleaning my project and using 0.8.5.7 it works for me now.

**Comment by frmz** [comment]
@christianlanz thanks for confirming!

**Comment by amugox** [comment]
0.8.5.7 also works for me
