### ISSUE TITLE
Multichoice dialogs NPE crash in pre Lollipop

### ISSUE THREAD

**Issue by filipc** [afollestad/material-dialogs#1006]
Problem occurs even in demo app.
Selecting any of multichoice dialogs produce a NPE crash.

`java.lang.NullPointerException
                                                                                at android.support.v4.graphics.drawable.DrawableWrapperDonut.setCompatTintList(DrawableWrapperDonut.java:272)
                                                                                at android.support.v4.graphics.drawable.DrawableCompatBase.setTintList(DrawableCompatBase.java:42)
                                                                                at android.support.v4.graphics.drawable.DrawableCompat$BaseDrawableImpl.setTintList(DrawableCompat.java:94)
                                                                                at android.support.v4.graphics.drawable.DrawableCompat.setTintList(DrawableCompat.java:390)
                                                                                at com.afollestad.materialdialogs.internal.MDTintHelper.setTint(MDTintHelper.java:138)
                                                                                at com.afollestad.materialdialogs.DefaultAdapter.getView(DefaultAdapter.java:75)
                                                                                at android.widget.AbsListView.obtainView(AbsListView.java:2627)
                                                                                at android.widget.ListView.measureHeightOfChildren(ListView.java:1259)
                                                                                at android.widget.ListView.onMeasure(ListView.java:1171)
                                                                                at android.view.View.measure(View.java:16831)
                                                                                at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
...
`

**Comment by keith30xi** [comment]
Also occurs with a single choice dialog

` java.lang.NullPointerException
                                                                              at android.support.v4.graphics.drawable.DrawableWrapperDonut.setCompatTintList(DrawableWrapperDonut.java:272)
                                                                              at android.support.v4.graphics.drawable.DrawableCompatBase.setTintList(DrawableCompatBase.java:42)
                                                                              at android.support.v4.graphics.drawable.DrawableCompat$BaseDrawableImpl.setTintList(DrawableCompat.java:94)
                                                                              at android.support.v4.graphics.drawable.DrawableCompat.setTintList(DrawableCompat.java:390)
                                                                              at com.afollestad.materialdialogs.internal.MDTintHelper.setTint(MDTintHelper.java:45)
                                                                              at com.afollestad.materialdialogs.DefaultAdapter.getView(DefaultAdapter.java:67)
                                                                              at android.widget.AbsListView.obtainView(AbsListView.java:2255)
                                                                              at android.widget.ListView.measureHeightOfChildren(ListView.java:1263)
                                                                              at android.widget.ListView.onMeasure(ListView.java:1175)
                                                                              at android.view.View.measure(View.java:16497)
                                                                              at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                              at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                              at android.view.View.measure(View.java:16497)
                                                                              at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                              at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                              at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                              at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                              at android.view.View.measure(View.java:16497)
                                                                              at com.afollestad.materialdialogs.internal.MDRootLayout.onMeasure(MDRootLayout.java:199)
                                                                              at android.view.View.measure(View.java:16497)
                                                                              at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                              at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                              at android.view.View.measure(View.java:16497)
                                                                              at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                              at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                              at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                              at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                              at android.view.View.measure(View.java:16497)
                                                                              at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                              at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                              at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2291)
                                                                              at android.view.View.measure(View.java:16497)
                                                                              at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1912)
                                                                              at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1084)
                                                                              at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1291)
                                                                              at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
                                                                              at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5600)
                                                                              at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
                                                                              at android.view.Choreographer.doCallbacks(Choreographer.java:574)
                                                                              at android.view.Choreographer.doFrame(Choreographer.java:544)
                                                                              at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
                                                                              at android.os.Handler.handleCallback(Handler.java:733)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:136)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                              at java.lang.reflect.Method.invokeNative(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:515)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                              at dalvik.system.NativeStart.main(Native Method)`

**Comment by keith30xi** [comment]
Appears to be new in **0.8.5.7**.

Works fine in 0.8.5.6.

**Comment by mariotaku** [comment]
Seems MDTintHelper trying to load a non-vector drawable https://github.com/afollestad/material-dialogs/blob/master/core/src/main/java/com/afollestad/materialdialogs/internal/MDTintHelper.java#L135 , I'll issue a pr to fix that.
