### ISSUE TITLE
drawable/text_cursor_material has unresolved theme attributes

### ISSUE THREAD

**Issue by mtrakal** [afollestad/material-dialogs#1007]
```
W/Resources: Drawable android:drawable/text_cursor_material has unresolved theme attributes! Consider using Resources.getDrawable(int, Theme) or Context.getDrawable(int).
                                                                             java.lang.RuntimeException
                                                                                 at android.content.res.Resources.getDrawable(Resources.java:851)
                                                                                 at android.support.v7.widget.TintResources.superGetDrawable(TintResources.java:55)
                                                                                 at android.support.v7.widget.AppCompatDrawableManager.onDrawableLoadedFromResources(AppCompatDrawableManager.java:391)
                                                                                 at android.support.v7.widget.TintResources.getDrawable(TintResources.java:48)
                                                                                 at com.afollestad.materialdialogs.internal.MDTintHelper.setCursorTint(MDTintHelper.java:150)
                                                                                 at com.afollestad.materialdialogs.internal.MDTintHelper.setTint(MDTintHelper.java:118)
                                                                                 at com.afollestad.materialdialogs.DialogInit.setupInputDialog(DialogInit.java:428)
                                                                                 at com.afollestad.materialdialogs.DialogInit.init(DialogInit.java:300)
                                                                                 at com.afollestad.materialdialogs.MaterialDialog.<init>(MaterialDialog.java:96)
                                                                                 at com.afollestad.materialdialogs.MaterialDialog$Builder.build(MaterialDialog.java:1335)
                                                                                 at com.afollestad.materialdialogs.MaterialDialog$Builder.show(MaterialDialog.java:1340)
```

It's log from code like below:
```
MaterialDialog.Builder(context)
                    .title(R.string.shopping_list)
                    .input(context.getString(R.string.shopping_list_enter_name_hint),
                            text, false, new MaterialDialog.InputCallback() {
                                @Override
                                public void onInput(MaterialDialog dialog, CharSequence input) {
                                    // Do something
                                }
                            })
                    .positiveText(R.string.create)
                    .onPositive(new MaterialDialog.SingleButtonCallback() {...}
.show();
```

It's not fatal, just warn, but it's often

**Comment by afollestad** [comment]
I'm using AppCompat methods to retrieve Drawables (`ContextCompat.getDrawable()`). If you're using the latest version of the library, it's an AppCompat issue.
