### ISSUE TITLE
Problem with MDTintHelper and support library?

### ISSUE THREAD

**Issue by plusema86** [afollestad/material-dialogs#1017]
FATAL EXCEPTION: main
                                                                                  Process: , PID: 20945
                                                                                  java.lang.NullPointerException
                                                                                      at android.support.v4.graphics.drawable.DrawableWrapperDonut.setCompatTintList(DrawableWrapperDonut.java:272)
                                                                                      at android.support.v4.graphics.drawable.DrawableCompatBase.setTintList(DrawableCompatBase.java:42)
                                                                                      at android.support.v4.graphics.drawable.DrawableCompat$BaseDrawableImpl.setTintList(DrawableCompat.java:94)
                                                                                      at android.support.v4.graphics.drawable.DrawableCompat.setTintList(DrawableCompat.java:390)
                                                                                      at com.afollestad.materialdialogs.internal.MDTintHelper.setTint(MDTintHelper.java:45)
                                                                                      at com.afollestad.materialdialogs.DefaultAdapter.getView(DefaultAdapter.java:67)
                                                                                      at android.widget.AbsListView.obtainView(AbsListView.java:2351)
                                                                                      at android.widget.ListView.measureHeightOfChildren(ListView.java:1274)
                                                                                      at android.widget.ListView.onMeasure(ListView.java:1186)
                                                                                      at android.view.View.measure(View.java:16749)
                                                                                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5295)
                                                                                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                                      at android.view.View.measure(View.java:16749)
                                                                                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5295)
                                                                                      at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                                      at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                                      at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                                      at android.view.View.measure(View.java:16749)
                                                                                      at com.afollestad.materialdialogs.internal.MDRootLayout.onMeasure(MDRootLayout.java:199)
                                                                                      at android.view.View.measure(View.java:16749)
                                                                                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5295)
                                                                                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                                      at android.view.View.measure(View.java:16749)
                                                                                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5295)
                                                                                      at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                                      at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                                      at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                                      at android.view.View.measure(View.java:16749)
                                                                                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5295)
                                                                                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                                      at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2439)
                                                                                      at android.view.View.measure(View.java:16749)
                                                                                      at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2080)
                                                                                      at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1151)
                                                                                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1380)
                                                                                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1063)
                                                                                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5993)
                                                                                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
                                                                                      at android.view.Choreographer.doCallbacks(Choreographer.java:574)
                                                                                      at android.view.Choreographer.doFrame(Choreographer.java:544)
                                                                                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
                                                                                      at android.os.Handler.handleCallback(Handler.java:733)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                      at android.os.Looper.loop(Looper.java:136)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5584)
                                                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                      at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
                                                                                      at dalvik.system.NativeStart.main(Native Method)

**Comment by muratogat** [comment]
Yes, and it is discussed here: https://github.com/afollestad/material-dialogs/issues/1013

**Comment by Nenomernoi** [comment]
super +

**Comment by afollestad** [comment]
Try the latest release
