### ISSUE TITLE
Crashes with Choice List Dialogs (Single and Multiple) on Android 4.1

### ISSUE THREAD

**Issue by JuliaZozulia** [afollestad/material-dialogs#1028]
Crashes with Choice List Dialogs (Single and Multiple) on Android 4.1 (Sony S) both with my app and your demo app from market. 

03-26 14:16:48.948 27140-27140/com.juliazozulia.upplug E/VectorDrawableCompat: parser error
                                                                               org.xmlpull.v1.XmlPullParserException: Binary XML file line #17<vector> tag requires viewportWidth > 0
                                                                                   at android.support.graphics.drawable.VectorDrawableCompat.updateStateFromTypedArray(VectorDrawableCompat.java:535)
                                                                                   at android.support.graphics.drawable.VectorDrawableCompat.inflate(VectorDrawableCompat.java:472)
                                                                                   at android.support.graphics.drawable.VectorDrawableCompat.createFromXmlInner(VectorDrawableCompat.java:436)
                                                                                   at android.support.graphics.drawable.VectorDrawableCompat.create(VectorDrawableCompat.java:418)
                                                                                   at com.afollestad.materialdialogs.internal.MDTintHelper.setTint(MDTintHelper.java:42)
                                                                                   at com.afollestad.materialdialogs.DefaultAdapter.getView(DefaultAdapter.java:67)
                                                                                   at android.widget.AbsListView.obtainView(AbsListView.java:2271)
                                                                                   at android.widget.ListView.measureHeightOfChildren(ListView.java:1270)
                                                                                   at android.widget.ListView.onMeasure(ListView.java:1182)
                                                                                   at android.view.View.measure(View.java:15367)
                                                                                   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4924)
                                                                                   at android.widget.FrameLayout.onMeasure(FrameLayout.java:314)
                                                                                   at android.view.View.measure(View.java:15367)
                                                                                   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4924)
                                                                                   at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1420)
                                                                                   at android.widget.LinearLayout.measureVertical(LinearLayout.java:697)
                                                                                   at android.widget.LinearLayout.onMeasure(LinearLayout.java:578)
                                                                                   at android.view.View.measure(View.java:15367)
                                                                                   at com.afollestad.materialdialogs.internal.MDRootLayout.onMeasure(MDRootLayout.java:199)
                                                                                   at android.view.View.measure(View.java:15367)
                                                                                   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4924)
                                                                                   at android.widget.FrameLayout.onMeasure(FrameLayout.java:314)
                                                                                   at android.view.View.measure(View.java:15367)
                                                                                   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4924)
                                                                                   at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1420)
                                                                                   at android.widget.LinearLayout.measureVertical(LinearLayout.java:697)
                                                                                   at android.widget.LinearLayout.onMeasure(LinearLayout.java:578)
                                                                                   at android.view.View.measure(View.java:15367)
                                                                                   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4924)
                                                                                   at android.widget.FrameLayout.onMeasure(FrameLayout.java:314)
                                                                                   at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2154)
                                                                                   at android.view.View.measure(View.java:15367)
                                                                                   at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1858)
                                                                                   at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1081)
                                                                                   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1279)
                                                                                   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1004)
                                                                                   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4223)
                                                                                   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
                                                                                   at android.view.Choreographer.doCallbacks(Choreographer.java:555)
                                                                                   at android.view.Choreographer.doFrame(Choreographer.java:525)
                                                                                   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
                                                                                   at android.os.Handler.handleCallback(Handler.java:615)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                                   at android.os.Looper.loop(Looper.java:213)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:4787)
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
                                                                                   at dalvik.system.NativeStart.main(Native Method)
03-26 14:16:48.958 27140-27140/com.juliazozulia.upplug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         java.lang.NullPointerException
                                                                             at android.support.v4.graphics.drawable.DrawableWrapperDonut.setCompatTintList(DrawableWrapperDonut.java:272)
                                                                             at android.support.v4.graphics.drawable.DrawableCompatBase.setTintList(DrawableCompatBase.java:42)
                                                                             at android.support.v4.graphics.drawable.DrawableCompat$BaseDrawableImpl.setTintList(DrawableCompat.java:94)
                                                                             at android.support.v4.graphics.drawable.DrawableCompat.setTintList(DrawableCompat.java:390)
                                                                             at com.afollestad.materialdialogs.internal.MDTintHelper.setTint(MDTintHelper.java:45)
                                                                             at com.afollestad.materialdialogs.DefaultAdapter.getView(DefaultAdapter.java:67)
                                                                             at android.widget.AbsListView.obtainView(AbsListView.java:2271)
                                                                             at android.widget.ListView.measureHeightOfChildren(ListView.java:1270)
                                                                             at android.widget.ListView.onMeasure(ListView.java:1182)
                                                                             at android.view.View.measure(View.java:15367)
                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4924)
                                                                             at android.widget.FrameLayout.onMeasure(FrameLayout.java:314)
                                                                             at android.view.View.measure(View.java:15367)
                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4924)
                                                                             at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1420)
                                                                             at android.widget.LinearLayout.measureVertical(LinearLayout.java:697)
                                                                             at android.widget.LinearLayout.onMeasure(LinearLayout.java:578)
                                                                             at android.view.View.measure(View.java:15367)
                                                                             at com.afollestad.materialdialogs.internal.MDRootLayout.onMeasure(MDRootLayout.java:199)
                                                                             at android.view.View.measure(View.java:15367)
                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4924)
                                                                             at android.widget.FrameLayout.onMeasure(FrameLayout.java:314)
                                                                             at android.view.View.measure(View.java:15367)
                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4924)
                                                                             at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1420)
                                                                             at android.widget.LinearLayout.measureVertical(LinearLayout.java:697)
                                                                             at android.widget.LinearLayout.onMeasure(LinearLayout.java:578)
                                                                             at android.view.View.measure(View.java:15367)
                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4924)
                                                                             at android.widget.FrameLayout.onMeasure(FrameLayout.java:314)
                                                                             at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2154)
                                                                             at android.view.View.measure(View.java:15367)
                                                                             at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1858)
                                                                             at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1081)
                                                                             at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1279)
                                                                             at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1004)
                                                                             at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4223)
                                                                             at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
                                                                             at android.view.Choreographer.doCallbacks(Choreographer.java:555)
                                                                             at android.view.Choreographer.doFrame(Choreographer.java:525)
                                                                             at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
                                                                             at android.os.Handler.handleCallback(Handler.java:615)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                             at android.os.Looper.loop(Looper.java:213)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:4787)
                                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:511)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
                                                                             at dalvik.system.NativeStart.main(Native Method)

**Comment by JuliaZozulia** [comment]
I just notice that this issue is already fixed. Can you tell when new release of library is going to be done?

**Comment by ntaloventi** [comment]
works on me..
get the latest ''com.github.afollestad.material-dialogs:core:0.8.5.7@aar'
and android.support '23.2.1'
but single choice has dprecated method 
1. android.content.Context.getColorStateList
2. android.content.Context.getColor

@author Aidan Follestad (afollestad)
need your comment here...

thanks

**Comment by ashmosaheb** [comment]
I am getting this issue to on a 4.2.2 device with the latest com.github.afollestad.material-dialogs:core:0.8.5.7@aar

**Comment by koolll** [comment]
i having this issue also . any solution ?

**Comment by ntaloventi** [comment]
@kool have you try my comment above?
