### ISSUE TITLE
How to solve the problem ? (0.8.5.7@arr)

### ISSUE THREAD

**Issue by chond** [afollestad/material-dialogs#1041]
java.lang.NoClassDefFoundError: android.support.graphics.drawable.VectorDrawableCompat
                                                                          at com.afollestad.materialdialogs.internal.e.a(Unknown Source)
                                                                          at com.afollestad.materialdialogs.a.getView(Unknown Source)
                                                                          at android.widget.AbsListView.obtainView(AbsListView.java:2257)
                                                                          at android.widget.ListView.measureHeightOfChildren(ListView.java:1263)
                                                                          at android.widget.ListView.onMeasure(ListView.java:1175)
                                                                          at android.view.View.measure(View.java:16508)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                          at android.view.View.measure(View.java:16508)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                          at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                          at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                          at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                          at android.view.View.measure(View.java:16508)

**Comment by afollestad** [comment]
That class isn't used anymore so you're using an old version of the library. 

The error is caused by you not using a new version of Google's libs, though. E.g. AppCompat and Support Library 23.3.0.
