### ISSUE TITLE
java.lang.NoClassDefFoundError，How to solve the problem ? (0.8.5.7)

### ISSUE THREAD

**Issue by chond** [afollestad/material-dialogs#1042]
java.lang.NoClassDefFoundError: android.support.graphics.drawable.VectorDrawableCompat
                                                                          at com.afollestad.materialdialogs.internal.e.a(Unknown Source)
                                                                          at com.afollestad.materialdialogs.a.getView(Unknown Source)
                                                                          at android.widget.AbsListView.obtainView(AbsListView.java:2257)
                                                                          at android.widget.ListView.measureHeightOfChildren(ListView.java:1263)
                                                                          at android.widget.ListView.onMeasure(ListView.java:1175)
                                                                          at android.view.View.measure(View.java:16508)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                          at android.view.View.measure(View.java:16508)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                          at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                          at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                          at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                          at android.view.View.measure(View.java:16508)
                                                                          at com.afollestad.materialdialogs.internal.MDRootLayout.onMeasure(Unknown Source)
                                                                          at android.view.View.measure(View.java:16508)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                          at android.view.View.measure(View.java:16508)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                          at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                          at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                          at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                          at android.view.View.measure(View.java:16508)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                          at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2291)
                                                                          at android.view.View.measure(View.java:16508)
                                                                          at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1955)
                                                                          at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1127)
                                                                          at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1334)
                                                                          at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1039)
                                                                          at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5648)
                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:574)
                                                                          at android.view.Choreographer.doFrame(Choreographer.java:544)
                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
                                                                          at android.os.Handler.handleCallback(Handler.java:733)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:136)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5052)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
                                                                          at dalvik.system.NativeStart.main(Native Method)

**Comment by afollestad** [comment]
You already posted this.
