### ISSUE TITLE
App Crashe Pre-lolipop when using multichoice list dialogue 

### ISSUE THREAD

**Issue by sidsaxena0** [afollestad/material-dialogs#1043]
App keeps crashing when try to use it on pre-lolipop devices : 

java.lang.NullPointerException
                                                                              at android.support.v4.graphics.drawable.DrawableWrapperDonut.setCompatTintList(DrawableWrapperDonut.java:272)
                                                                              at android.support.v4.graphics.drawable.DrawableCompatBase.setTintList(DrawableCompatBase.java:42)
                                                                              at android.support.v4.graphics.drawable.DrawableCompat$BaseDrawableImpl.setTintList(DrawableCompat.java:94)
                                                                              at android.support.v4.graphics.drawable.DrawableCompat.setTintList(DrawableCompat.java:390)
                                                                              at com.afollestad.materialdialogs.internal.MDTintHelper.setTint(MDTintHelper.java:138)
                                                                              at com.afollestad.materialdialogs.DefaultAdapter.getView(DefaultAdapter.java:75)
                                                                              at android.widget.AbsListView.obtainView(AbsListView.java:2255)
                                                                              at android.widget.ListView.measureHeightOfChildren(ListView.java:1263)
                                                                              at android.widget.ListView.onMeasure(ListView.java:1175)
                                                                              at android.view.View.measure(View.java:16497)
                                                                              at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                              at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                              at android.view.View.measure(View.java:16497)
                                                                              at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                              at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                              at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                              at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                              at android.view.View.measure(View.java:16497)
                                                                              at com.afollestad.materialdialogs.internal.MDRootLayout.onMeasure(MDRootLayout.java:199)
                                                                              at android.view.View.measure(View.java:16497)
                                                                              at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                              at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                              at android.view.View.measure(View.java:16497)
                                                                              at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                              at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                              at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                              at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                              at android.view.View.measure(View.java:16497)
                                                                              at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                              at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                              at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2291)
                                                                              at android.view.View.measure(View.java:16497)
                                                                              at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1912)
                                                                              at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1084)
                                                                              at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1291)
                                                                              at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
                                                                              at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5600)
                                                                              at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
                                                                              at android.view.Choreographer.doCallbacks(Choreographer.java:574)
                                                                              at android.view.Choreographer.doFrame(Choreographer.java:544)
                                                                              at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
                                                                              at android.os.Handler.handleCallback(Handler.java:733)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:136)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                              at java.lang.reflect.Method.invokeNative(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:515)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                              at dalvik.system.NativeStart.main(Native Method)
                                                                          

Pleae help.

**Comment by sidsaxena0** [comment]
Sorry didn't see the 0.8.5.8, and later realized issue is resolved.
