### ISSUE TITLE
NullPointerException: MDButton returned null

### ISSUE THREAD

**Issue by javiersantos** [afollestad/material-dialogs#1048]
- Material Dialogs version: `0.8.5.8`
 - Device OS version: `6.0.1`
 - Device Manufacturer: `LG`
 - Device Name: `Nexus 4`

###### Log
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.afollestad.materialdialogs.internal.MDButton.setVisibility(int)' on a null object reference
               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
               at android.app.ActivityThread.-wrap11(ActivityThread.java)
               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
               at android.os.Handler.dispatchMessage(Handler.java:102)
               at android.os.Looper.loop(Looper.java:148)
               at android.app.ActivityThread.main(ActivityThread.java:5422)
               at java.lang.reflect.Method.invoke(Native Method)
               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.afollestad.materialdialogs.internal.MDButton.setVisibility(int)' on a null object reference
               at com.afollestad.materialdialogs.DialogInit.init(DialogInit.java:142)
               at com.afollestad.materialdialogs.MaterialDialog.<init>(MaterialDialog.java:96)
               at com.afollestad.materialdialogs.MaterialDialog$Builder.build(MaterialDialog.java:1335)
               at com.afollestad.materialdialogs.MaterialDialog$Builder.show(MaterialDialog.java:1340)
...
```

When calling this method:

```java
public static MaterialDialog showRateDialog(final Context context) {
        return new MaterialDialog.Builder(context)
                .title(context.getString(R.string.settings_googleplay))
                .content(context.getString(R.string.settings_googleplay_description))
                .cancelable(false)
                .positiveText(context.getString(R.string.button_rate))
                .negativeText(context.getString(R.string.button_no))
                .neutralText(context.getString(R.string.button_later))
                .onPositive(new MaterialDialog.SingleButtonCallback() {
                    @Override
                    public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                        ...
                    }
                })
                .onNegative(new MaterialDialog.SingleButtonCallback() {
                    @Override
                    public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                        ...
                    }
                })
                .onNeutral(new MaterialDialog.SingleButtonCallback() {
                    @Override
                    public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                        ...
                    }
                }).show();

    }
```

**Comment by javiersantos** [comment]
Seems there is an issue affecting to AppCompat 23.3.3. Reverting to 23.2.1 fixes the issue.

**Comment by afollestad** [comment]
Hmm, yeah not much I can do unfortunately. Hopefully it works with newer versions (MD 0.8.6.0, AppCompat 24.0.0).
