### ISSUE TITLE
Random crashes on some devices

### ISSUE THREAD

**Issue by sidsaxena0** [afollestad/material-dialogs#1064]
My apps generally crashes with material dialogues but i am not able to find the reason because it always keep pointing to material dialogue code. Please fix it, if that's an issue or provide some solution, i love to use it.

Here is my stack trace on Android 5.0 (Asus Zenfone 5) 
*****************************************************************************************************************************

```Gradle
 java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
                                                                      at com.afollestad.materialdialogs.util.DialogUtils.getColor(DialogUtils.java:113)
                                                                      at com.afollestad.materialdialogs.MaterialDialog$Builder.<init>(MaterialDialog.java:483)
                                                                      at sid.jones.myeduz.BrowseCourse.showErrorDialogue(BrowseCourse.java:204)
                                                                      at sid.jones.myeduz.BrowseCourse$1$1.run(BrowseCourse.java:106)
                                                                      at android.os.Handler.handleCallback(Handler.java:739)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:135)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5253)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by afollestad** [comment]
That means you passed a `null` context to `new MaterialDialog.Builder(Context)`.
