### ISSUE TITLE
DefaultAdapter NullPointerException

### ISSUE THREAD

**Issue by galadril** [afollestad/material-dialogs#1076]
- Material Dialogs version: `0.8.5.7`
 - Device OS version: `6.0.1`
 - Device Manufacturer: `Nexus`
 - Device Name: `Nexus 5`

```java
java.lang.NullPointerException
    at android.support.v4.graphics.drawable.DrawableWrapperDonut.setCompatTintList(DrawableWrapperDonut.java:272)
    at android.support.v4.graphics.drawable.DrawableCompatBase.setTintList(DrawableCompatBase.java:42)
    at android.support.v4.graphics.drawable.DrawableCompat$BaseDrawableImpl.setTintList(DrawableCompat.java:94)
    at android.support.v4.graphics.drawable.DrawableCompat.setTintList(DrawableCompat.java:390)
    at com.afollestad.materialdialogs.internal.MDTintHelper.setTint(MDTintHelper.java:138)
    at com.afollestad.materialdialogs.DefaultAdapter.getView(DefaultAdapter.java:75)
    at android.widget.AbsListView.obtainView(AbsListView.java:2743)
    at android.widget.ListView.measureHeightOfChildren(ListView.java:1274)
    at android.widget.ListView.onMeasure(ListView.java:1186)
    at android.view.View.measure(View.java:17482)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5376)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
    at android.view.View.measure(View.java:17482)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5376)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1410)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
    at android.view.View.measure(View.java:17482)
    at com.afollestad.materialdialogs.internal.MDRootLayout.onMeasure(MDRootLayout.java:199)
    at android.view.View.measure(View.java:17482)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5376)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
    at android.view.View.measure(View.java:17482)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5376)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1410)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
    at android.view.View.measure(View.java:17482)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5376)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
    at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2548)
    at android.view.View.measure(View.java:17482)
    at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2287)
    at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1373)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1597)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1256)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6635)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:812)
    at android.view.Choreographer.doCallbacks(Choreographer.java:612)
    at android.view.Choreographer.doFrame(Choreographer.java:582)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:798)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:146)
    at android.app.ActivityThread.main(ActivityThread.java:5593)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by afollestad** [comment]
You're not using the latest version of the library like the issue template asks.
