### ISSUE TITLE
java.lang.NullPointerException                                                                           at android.support.v4.graphics.drawable.DrawableWrapperDonut.getState(DrawableWrapperDonut.java:147) 

### ISSUE THREAD

**Issue by gao746700783** [afollestad/material-dialogs#1090]
`E/CrashException: DateTime:2016-06-01 11:15:09
                                                                      ExceptionName:null
                                                                      
                                                                      android.support.v4.graphics.drawable.DrawableWrapperDonut	DrawableWrapperDonut.java[147].getState 
                                                                      android.support.v4.graphics.drawable.DrawableWrapperDonut	DrawableWrapperDonut.java[267].setTintList 
                                                                      android.support.v4.graphics.drawable.DrawableCompatBase	DrawableCompatBase.java[42].setTintList 
                                                                      android.support.v4.graphics.drawable.DrawableCompat$BaseDrawableImpl	DrawableCompat.java[94].setTintList 
                                                                      android.support.v4.graphics.drawable.DrawableCompat	DrawableCompat.java[390].setTintList 
                                                                      com.afollestad.materialdialogs.internal.MDTintHelper	MDTintHelper.java[45].setTint 
                                                                      com.afollestad.materialdialogs.DefaultAdapter	DefaultAdapter.java[67].getView 
                                                                      android.widget.AbsListView	AbsListView.java[2255].obtainView 
                                                                      android.widget.ListView	ListView.java[1263].measureHeightOfChildren 
                                                                      android.widget.ListView	ListView.java[1175].onMeasure 
                                                                      android.view.View	View.java[16566].measure 
                                                                      android.view.ViewGroup	ViewGroup.java[5147].measureChildWithMargins 
                                                                      android.widget.FrameLayout	FrameLayout.java[310].onMeasure 
                                                                      android.view.View	View.java[16566].measure 
                                                                      android.view.ViewGroup	ViewGroup.java[5147].measureChildWithMargins 
                                                                      android.widget.LinearLayout	LinearLayout.java[1427].measureChildBeforeLayout 
                                                                      android.widget.LinearLayout	LinearLayout.java[713].measureVertical 
                                                                      android.widget.LinearLayout	LinearLayout.java[606].onMeasure 
                                                                      android.view.View	View.java[16566].measure 
                                                                      com.afollestad.materialdialogs.internal.MDRootLayout	MDRootLayout.java[199].onMeasure 
                                                                      android.view.View	View.java[16566].measure 
                                                                      android.view.ViewGroup	ViewGroup.java[5147].measureChildWithMargins 
                                                                      android.widget.FrameLayout	FrameLayout.java[310].onMeasure 
                                                                      android.view.View	View.java[16566].measure 
                                                                      android.view.ViewGroup	ViewGroup.java[5147].measureChildWithMargins 
                                                                      android.widget.LinearLayout	LinearLayout.java[1427].measureChildBeforeLayout 
                                                                      android.widget.LinearLayout	LinearLayout.java[713].measureVertical 
                                                                      android.widget.LinearLayout	LinearLayout.java[606].onMeasure 
                                                                      android.view.View	View.java[16566].measure 
                                                                      android.view.ViewGroup	ViewGroup.java[5147].measureChildWithMargins 
                                                                      android.widget.FrameLayout	FrameLayout.java[310].onMeasure 
                                                                      com.android.internal.policy.impl.PhoneWindow$DecorView	PhoneWindow.java[2316].onMeasure 
                                                                      android.view.View	View.java[16566].measure 
                                                                      android.view.ViewRootImpl	ViewRootImpl.java[1979].performMeasure 
                                                                      android.view.ViewRootImpl	ViewRootImpl.java[1132].measureHierarchy 
                                                                      android.view.ViewRootImpl	ViewRootImpl.java[1339].performTraversals 
                                                                      android.view.ViewRootImpl	ViewRootImpl.java[1044].doTraversal 
                                                                      android.view.ViewRootImpl$TraversalRunnable	ViewRootImpl.java[5818].run 
                                                                      android.view.Choreographer$CallbackRecord	Choreographer.java[768].run 
                                                                      android.view.Choreographer	Choreographer.java[581].doCallbacks 
                                                                      android.view.Choreographer	Choreographer.java[551].doFrame 
                                                                      android.view.Choreographer$FrameDisplayEventReceiver	Choreographer.java[754].run 
                                                                      android.os.Handler	Handler.java[733].handleCallback 
                                                                      android.os.Handler	Handler.java[95].dispatchMessage 
                                                                      android.os.Looper	Looper.java[136].loop 
                                                                      android.app.ActivityThread	ActivityThread.java[5333].main 
                                                                      java.lang.reflect.Method	Method.java[-2].invokeNative 
                                                                      java.lang.reflect.Method	Method.java[515].invoke 
                                                                      com.android.internal.os.ZygoteInit$MethodAndArgsCaller	ZygoteInit.java[895].run 
                                                                      com.android.internal.os.ZygoteInit	ZygoteInit.java[711].main 
                                                                      dalvik.system.NativeStart	NativeStart.java[-2].main 
                                                                      
                                                                      null
                                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                      java.lang.NullPointerException
                                                                          at android.support.v4.graphics.drawable.DrawableWrapperDonut.getState(DrawableWrapperDonut.java:147)
                                                                          at android.support.v4.graphics.drawable.DrawableWrapperDonut.setTintList(DrawableWrapperDonut.java:267)
                                                                          at android.support.v4.graphics.drawable.DrawableCompatBase.setTintList(DrawableCompatBase.java:42)
                                                                          at android.support.v4.graphics.drawable.DrawableCompat$BaseDrawableImpl.setTintList(DrawableCompat.java:94)
                                                                          at android.support.v4.graphics.drawable.DrawableCompat.setTintList(DrawableCompat.java:390)
                                                                      	at com.afollestad.materialdialogs.internal`

**Comment by gao746700783** [comment]
sorry，i didn't check you release note 0.8.5.8,it's solved already !!!

**Comment by jeremyclee** [comment]
Just got the same error running core-0.8.6.2, support lib version 25.0.0

`Fatal Exception: java.lang.NullPointerException
       at android.support.v4.graphics.drawable.DrawableWrapperDonut.getState(DrawableWrapperDonut.java:147)
       at android.support.v4.graphics.drawable.DrawableWrapperDonut.setTintList(DrawableWrapperDonut.java:267)
       at android.support.v4.graphics.drawable.DrawableCompatBase.setTintList(DrawableCompatBase.java:42)
       at android.support.v4.graphics.drawable.DrawableCompat$BaseDrawableImpl.setTintList(DrawableCompat.java:94)
       at android.support.v4.graphics.drawable.DrawableCompat.setTintList(DrawableCompat.java:391)
       at com.afollestad.materialdialogs.internal.MDTintHelper.setTint(MDTintHelper.java:45)
       at com.afollestad.materialdialogs.DefaultAdapter.getView(DefaultAdapter.java:67)
       at android.widget.AbsListView.obtainView(AbsListView.java:2310)
       at android.widget.ListView.measureHeightOfChildren(ListView.java:1274)
       at android.widget.ListView.onMeasure(ListView.java:1186)
       at android.view.View.measure(View.java:16749)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5295)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:16749)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5295)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
       at android.view.View.measure(View.java:16749)
       at com.afollestad.materialdialogs.internal.MDRootLayout.onMeasure(MDRootLayout.java:199)
       at android.view.View.measure(View.java:16749)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5295)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:16749)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5295)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
       at android.view.View.measure(View.java:16749)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5295)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2439)
       at android.view.View.measure(View.java:16749)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2080)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1176)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1380)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1063)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5993)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
       at android.view.Choreographer.doCallbacks(Choreographer.java:574)
       at android.view.Choreographer.doFrame(Choreographer.java:544)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5584)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
       at dalvik.system.NativeStart.main(NativeStart.java)`
