### ISSUE TITLE
Cannot use indeterminate-dialog in midst of a fragment transaction

### ISSUE THREAD

**Issue by MSF-Jarvis** [afollestad/material-dialogs#1093]
- [ x ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ x ] I have verified that I am using the latest version of Material Dialogs.
- [ x ] I have given my issue a non-generic title.

###### Include the following:
 - Material Dialogs version: `0.8.5.8`
 - Device OS version: `6.0.1`
 - Device Manufacturer: `LAVA`
 - Device Name: `Pixelv1`

Also, please wrap Java with correct syntax highlighting.

```java
case R.id.blog:
                        drawerLayout.closeDrawers();
                        FragmentTransaction ft = getSupportFragmentManager().beginTransaction();
                        ft.replace(R.id.content_main, new BlogFragment());
                        ft.commit();
                        Context context = getApplicationContext();
                        new MaterialDialog.Builder(context)
                                .title(R.string.progress_dialog)
                                .content(R.string.please_wait)
                                .progress(true, 0)
                                .show();
                        break;
```
 
###### Reproduction Steps

1. Add above code to your project
2. Attach it to an object through an onClickListener

###### Expected Result

Indeterminate dialog

###### Actual Result

Crash with log as follows :

```
--------- beginning of crash
06-07 02:02:18.293  3462  3462 E AndroidRuntime: FATAL EXCEPTION: main
06-07 02:02:18.293  3462  3462 E AndroidRuntime: Process: me.msfjarvis.kpsconnect, PID: 3462
06-07 02:02:18.293  3462  3462 E AndroidRuntime: com.afollestad.materialdialogs.o: Bad window token, you cannot show a dialog before an Activity is created or after it's hidden.
06-07 02:02:18.293  3462  3462 E AndroidRuntime: 	at com.afollestad.materialdialogs.h.show(Unknown Source)
06-07 02:02:18.293  3462  3462 E AndroidRuntime: 	at com.afollestad.materialdialogs.m.c(Unknown Source)
06-07 02:02:18.293  3462  3462 E AndroidRuntime: 	at me.msfjarvis.kpsconnect.c.a(Unknown Source)
06-07 02:02:18.293  3462  3462 E AndroidRuntime: 	at android.support.design.widget.aw.a(Unknown Source)
06-07 02:02:18.293  3462  3462 E AndroidRuntime: 	at android.support.v7.view.menu.i.a(Unknown Source)
06-07 02:02:18.293  3462  3462 E AndroidRuntime: 	at android.support.v7.view.menu.m.b(Unknown Source)
06-07 02:02:18.293  3462  3462 E AndroidRuntime: 	at android.support.v7.view.menu.i.a(Unknown Source)
06-07 02:02:18.293  3462  3462 E AndroidRuntime: 	at android.support.design.internal.d.onClick(Unknown Source)
06-07 02:02:18.293  3462  3462 E AndroidRuntime: 	at android.view.View.performClick(View.java:5198)
06-07 02:02:18.293  3462  3462 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:21147)
06-07 02:02:18.293  3462  3462 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
06-07 02:02:18.293  3462  3462 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
06-07 02:02:18.293  3462  3462 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
06-07 02:02:18.293  3462  3462 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
06-07 02:02:18.293  3462  3462 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-07 02:02:18.293  3462  3462 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
06-07 02:02:18.293  3462  3462 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
06-07 02:02:18.293  3462  3462 E AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
06-07 02:02:18.304   629  1451 W ActivityManager:   Force finishing activity me.msfjarvis.kpsconnect/.MainActivity
06-07 02:02:18.818   629   646 W ActivityManager: Activity pause timeout for ActivityRecord{a327eb7 u0 me.msfjarvis.kpsconnect/.MainActivity t1214 f}
06-07 02:02:20.200   629   778 I WindowState: WIN DEATH: Window{4e2e187 u0 me.msfjarvis.kpsconnect/me.msfjarvis.kpsconnect.MainActivity}
06-07 02:02:20.224   629   786 I ActivityManager: Process me.msfjarvis.kpsconnect (pid 3462) has died
```

**Comment by afollestad** [comment]
It has nothing to do with the fragment transaction, you can pass `getApplicationContext()`. It needs an `Activity` context. Also, `commit()` is not an asynchronous method so it will complete **before** you ever try to show the dialog.

**Comment by MSF-Jarvis** [comment]
Thanks Aidan, I'll fix up my code.
