### ISSUE TITLE
Dialog dismiss exception: Fatal Exception: java.lang.IllegalArgumentException: View not attached to window manager

### ISSUE THREAD

**Issue by mntgoat** [afollestad/material-dialogs#1108]
###### Include the following:
 - Material Dialogs version: `0.8.5.9`
 - Device OS version: `4+`
 - Device Manufacturer: `Multiple`
 - Device Name: `Multiple`

I've been getting this crash on Crashlytics. I have no idea how to reproduce it. It doesn't look like my code is triggering the dismiss so I'm not sure how I would go about fixing it plus I don't know on which of my many dialogs it is happening. Thanks. 

```
Fatal Exception: java.lang.IllegalArgumentException: View not attached to window manager
       at android.view.WindowManagerImpl.findViewLocked(WindowManagerImpl.java:653)
       at android.view.WindowManagerImpl.removeView(WindowManagerImpl.java:349)
       at android.view.WindowManagerImpl$CompatModeWrapper.removeView(WindowManagerImpl.java:160)
       at android.app.Dialog.dismissDialog(Dialog.java:319)
       at android.app.Dialog.dismiss(Dialog.java:302)
       at com.afollestad.materialdialogs.MaterialDialog.dismiss(MaterialDialog.java:1811)
       at android.app.Dialog.cancel(Dialog.java:1104)
       at android.app.Dialog.onTouchEvent(Dialog.java:617)
       at android.app.Dialog.dispatchTouchEvent(Dialog.java:739)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1873)
       at android.view.View.dispatchPointerEvent(View.java:7307)
       at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3172)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3117)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4153)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4132)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4224)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:171)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:125)
       at android.os.Looper.loop(Looper.java:124)
       at android.app.ActivityThread.main(ActivityThread.java:4745)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by afollestad** [comment]
That happens if you show or dismiss a dialog after an Activity goes out of view. You need to dismiss dialogs in `onPause()`. There is duplicates for this issue.
