### ISSUE TITLE
colorBackgroundFloating field missing in Android 4.0.4

### ISSUE THREAD

**Issue by MisterY** [afollestad/material-dialogs#1122]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.8.6.1`
 - Device OS version: `4.0.4`
 - Device Manufacturer: `Google`
 - Device Name: `Nexus S` emulator

Also, please wrap Java with correct syntax highlighting.

```java
        new MaterialDialog.Builder(getActivity())
                .title(R.string.quote_provider)
                .items(QuoteProviders.names())
                .itemsCallbackSingleChoice(currentIndex, new MaterialDialog.ListCallbackSingleChoice() {
                    @Override
                    public boolean onSelection(MaterialDialog dialog, View itemView, int which, CharSequence text) {
                        //change provider
                        return true;
                    }
                })
                .show();
```
 
###### Reproduction Steps

1. Adding the code above to display single-choice list

###### Expected Result
single-choice list with given options

###### Actual Result

************ FIRMWARE ************
SDK: 15
Release: 4.0.4
Incremental: eng.zhangwei-linux-s.20150310.124918

************ CAUSE OF ERROR ************
java.lang.NoSuchFieldError: com.afollestad.materialdialogs.R$attr.colorBackgroundFloating
	at com.afollestad.materialdialogs.DialogInit.init(DialogInit.java:80)
	at com.afollestad.materialdialogs.MaterialDialog.<init>(MaterialDialog.java:96)
	at com.afollestad.materialdialogs.MaterialDialog$Builder.build(MaterialDialog.java:1335)
	at com.afollestad.materialdialogs.MaterialDialog$Builder.show(MaterialDialog.java:1340)
	at com.money.manager.ex.investment.WatchlistFragment.changePriceProvider(WatchlistFragment.java:373)
	at com.money.manager.ex.investment.WatchlistFragment.onOptionsItemSelected(WatchlistFragment.java:252)
	at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:2199)
	at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:2284)
	at android.support.v4.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:353)
	at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:427)
	at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:185)
	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:100)
	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:100)
	at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:69)
	at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:169)
	at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:760)
	at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:811)
	at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:958)
	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:948)
	at android.support.v7.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:191)
	at android.widget.AdapterView.performItemClick(AdapterView.java:292)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1058)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:2514)
	at android.widget.AbsListView$1.run(AbsListView.java:3168)
	at android.os.Handler.handleCallback(Handler.java:605)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4424)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by MisterY** [comment]
Just reverted back to 0.8.5.9 and the list opens.

**Comment by MisterY** [comment]
https://github.com/afollestad/material-dialogs/commit/0821d5202c65510e4cc896e44341880eeddd0cc0

**Comment by plusCubed** [comment]
colorBackgroundFloating is an AppCompat attribute. Are you using the latest AppCompat library 24.0.0?

**Comment by MisterY** [comment]
Hm, no, not yet. It is not even showing as available in the SDK Manager. Must be still in the pre-release channel?

**Comment by afollestad** [comment]
It's been available for a month or two, publicly

**Comment by MisterY** [comment]
I've added the Support library 24.0.0 but still the same exception with dialogs 0.8.6.1

**Comment by afollestad** [comment]
You need AppCompat 24.0.0, not Support Library

**Comment by MisterY** [comment]
Right. I mean, I've upgraded all the support-related version numbers to 24:
```
            , 'com.android.support:support-v4:24.0.0'
            , 'com.android.support:appcompat-v7:24.0.0',
            'com.android.support:cardview-v7:24.0.0',
            'com.android.support:design:24.0.0',    
            'com.android.support:preference-v14:24.0.0',
            'com.android.support:support-annotations:24.0.0',
```
What could be the problem in your opinion?

**Comment by Ovoke** [comment]
try changing com.afollestad.materialdialogs.R.attr.colorBackgroundFloating or R.attr.colorBackgroundFloating to 
android.R.attr.colorBackgroundFloating in the DialogInit.java file at line 80
