### ISSUE TITLE
Error: java.lang.NoSuchFieldError

### ISSUE THREAD

**Issue by nabeelpkl** [afollestad/material-dialogs#1123]
- Material Dialogs version: `0.8.6.1`
 - Device OS version: `6.0.1`
 - Device Manufacturer: `OnePlus`
 - Device Name: `OnePlus Two`

I have used material-dialogs version '0.7.3.1' library in my old app. Now I am using latest version '0.8.6.1'. and I am getting the following error in my Android Studio

```
07-08 20:47:05.702 434-434/<PACKAGE NAME> E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: <PACKAGE NAME>, PID: 434
                                                                         java.lang.NoSuchFieldError: No static field colorBackgroundFloating of type I in class Lcom/afollestad/materialdialogs/R$attr; or its superclasses (declaration of 'com.afollestad.materialdialogs.R$attr' appears in /data/app/**<PACKAGE NAME>**-1/base.apk)
                                                                             at com.afollestad.materialdialogs.DialogInit.init(DialogInit.java:80)
                                                                             at com.afollestad.materialdialogs.MaterialDialog.<init>(MaterialDialog.java:96)
                                                                             at com.afollestad.materialdialogs.MaterialDialog$Builder.build(MaterialDialog.java:1335)
                                                                             at <PACKAGE NAME>.dialog.AlertBuilder.badResponseDialog(AlertBuilder.java:254)
                                                                             at <PACKAGE NAME>.dialog.AlertBuilder.create(AlertBuilder.java:62)
                                                                             at <PACKAGE NAME>.RegistrationBaseActivity.handleMessage(RegistrationBaseActivity.java:338)
                                                                             at <PACKAGE NAME>.RegistrationBaseActivity$IncomingHandler.handleMessage(RegistrationBaseActivity.java:107)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:152)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5497)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
  In positions in the code given below. 
 
```
  private MaterialDialog badResponseDialog() {
        String message = getBundledDialogContent();
        if (TextUtils.isEmpty(message)) {
            message = "Oops! There seems to be a technical problem. Please, try again later.";
        }

        return getThemedMaterialDialogBuilder(context, R.drawable.ic_comment_alert_outline_grey600_36dp, true)
                .title("Request Failed")
                .content(message)
                .positiveText("OK")
                /*.callback(new MaterialDialog.ButtonCallback() {
                    @Override
                    public void onPositive(MaterialDialog dialog) {
                        super.onPositive(dialog);
                        dialog.dismiss();
                    }
                })*/
            .onPositive(new MaterialDialog.SingleButtonCallback() {
              @Override
              public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                dialog.dismiss();
              }
            })
            .build();
    }

 private MaterialDialog.Builder getThemedMaterialDialogBuilder(Context context, int drawableResId, boolean isCancelable) {
        if (mDialogBuilder == null)
            mDialogBuilder = new MaterialDialog.Builder(context)
                    .titleColorRes(R.color.fed_blue)
                    .positiveColorRes(R.color.fed_blue)
                    .negativeColorRes(R.color.bg_qr);

        Drawable icon = context.getResources().getDrawable(drawableResId);
        if (icon != null)
            mDialogBuilder.icon(icon);

        mDialogBuilder.cancelable(isCancelable);

        return mDialogBuilder;
    }
```

Please help.

**Comment by aaadesignstudios** [comment]
It seems there is a bug in the latest update. I just went ahead and downgraded to v0.7.9.0 adding the whole library in the project. Works perfectly. Follow this link https://github.com/afollestad/material-dialogs/releases?after=0.7.9.1

**Comment by nabeelpkl** [comment]
Thanks @aaadesignstudios it worked. saved my day

**Comment by aaadesignstudios** [comment]
No problem glad I could help!

**Comment by afollestad** [comment]
You're probably not using the correct version of the Support Library in your app, this isn't something that I've had issues with or can fix since it's not in my code.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.6.2

**Comment by Tukajo** [comment]
@afollestad Could you state what the correct Support Library would be for 9.0.0+?

**Comment by afollestad** [comment]
@Tukajo why not look? This is open source, after all.

https://github.com/afollestad/material-dialogs/blob/master/core/build.gradle

**Comment by Tukajo** [comment]
@afollestad I had looked, the reason I ask however is I still seeing similar errors to what @nabeelpkl originally commented. Despite having "matching" library versions.

Sorry if I was not clear and thanks for your prompt reply.

**Comment by DavidMont** [comment]
I experienced the same issue, 
tried setting the same compile sdk version and build tools version same error.

**Comment by ManuBabu** [comment]
java.lang.NoSuchFieldError: No static field colorBackgroundFloating of type I in class Lcom/afollestad/materialdialogs/R$attr; or its superclasses (declaration of 'com.afollestad.materialdialogs.R$attr' appears in /data/app/manu.poketcommerce.com.openofficeuser-2/base.apk)

**Comment by afollestad** [comment]
@ManuBabu update the Google support libs (e.g. AppCompat) to 25.3.0 in your app.

**Comment by afollestad** [comment]
Otherwise, use an old version of MD.

**Comment by ManuBabu** [comment]
@afollestad, i am using these libraries.. still i am getting this error 
  please help
Error: java.lang.NoSuchFieldError: No static field colorBackgroundFloating of type I in class Lcom/afollestad/materialdialogs/R$attr; or its superclasses (declaration of 'com.afollestad.materialdialogs.R$attr' appears in /data/app/manu.mobile.com.apps-2/base.apk)
  
    compile 'com.android.support:appcompat-v7:25.2.0'
    compile 'com.android.support:support-v4:25.2.0'
    compile 'com.afollestad.material-dialogs:commons:0.8.6.1'
    compile 'com.jpardogo.materialtabstrip:library:1.1.0'
    compile 'com.jakewharton:butterknife:8.1.0'

**Comment by afollestad** [comment]
@ManuBabu you are _not_ using the version I mentioned in the comment above.

**Comment by ManuBabu** [comment]
@afollestad 
    compile 'com.android.support:appcompat-v7:25.3.0'
    compile 'com.android.support:support-v4:25.3.0'
    compile 'com.afollestad.material-dialogs:commons:0.9.4.1'
    compile 'com.jpardogo.materialtabstrip:library:1.1.0'
    compile 'com.jakewharton:butterknife:8.1.0'
 :( still no luck

**Comment by afollestad** [comment]
@ManuBabu oh, you need Material Dialogs 0.9.4.2, both `core` and `commons`.

This issue is completely unrelated to Material Dialogs. It's compatibility issues with having multiple versions of the Support library referenced across dependencies.

**Comment by rudsonlive** [comment]
I am having the same problem in version 3.1.0.
Can someone help me?
Thank you.

implementation 'com.afollestad.material-dialogs:core:3.1.0'

    --------- beginning of crash
2019-07-17 22:40:42.649 19368-19368/<Pack> E/AndroidRuntime: FATAL EXCEPTION: main
    Process: <PACKAGE NAME>, PID: 19368
    java.lang.NoSuchFieldError: No static field colorBackgroundFloating of type I in class Lcom/afollestad/materialdialogs/R$attr; or its superclasses (declaration of 'com.afollestad.materialdialogs.R$attr' appears in /data/app/<PACKAGE NAME>-xHJqvrxWFbHtqswWjU3HOw==/split_profile.apk)
        at com.afollestad.materialdialogs.MaterialDialog$invalidateBackgroundColorAndRadius$backgroundColor$1.invoke(MaterialDialog.kt:426)
        at com.afollestad.materialdialogs.MaterialDialog$invalidateBackgroundColorAndRadius$backgroundColor$1.invoke(MaterialDialog.kt:56)
        at com.afollestad.materialdialogs.utils.MDUtil.resolveColor(MDUtil.kt:114)
        at com.afollestad.materialdialogs.utils.ColorsKt.resolveColor(Colors.kt:32)
        at com.afollestad.materialdialogs.utils.ColorsKt.resolveColor$default(Colors.kt:31)
        at com.afollestad.materialdialogs.MaterialDialog.invalidateBackgroundColorAndRadius(MaterialDialog.kt:425)
        at com.afollestad.materialdialogs.MaterialDialog.<init>(MaterialDialog.kt:118)
        at com.afollestad.materialdialogs.MaterialDialog.<init>(MaterialDialog.kt:58)
        at br.com.ituran.varejo.profile.edit.adapter.PhoneAdapter$onBindViewHolder$1.onClick(PhoneAdapter.kt:40)
        at android.view.View.performClick(View.java:6259)
        at android.view.View$PerformClick.run(View.java:24732)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6592)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)

**Comment by allco** [comment]
The reason could be same layout file name or same package name in `AndroidManifest.xml` in the library and in the app.
