### ISSUE TITLE
typeface() causes error on specific smart phone.

### ISSUE THREAD

**Issue by Dagzo** [afollestad/material-dialogs#1129]
Hello, 
In a particular situation below, my app crashed.

Version: com.afollestad.material-dialogs:core:0.8.5.9
Android OS: 6.0
Device: ZTE BLADE V0720

I made MaterialDialog.Builder like below.

```
MaterialDialog dialog = new MaterialDialog.Builder(activity)
                .content("content")
                .positiveText("OK")
                .onPositive(new MaterialDialog.SingleButtonCallback() {
                    @Override
                    public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                        // Something 
                    }
                })
                .build();
```

It caused this exception.
```
Fatal Exception: java.lang.IllegalArgumentException: No font asset found for 
       at com.afollestad.materialdialogs.MaterialDialog$Builder.typeface(MaterialDialog.java:653)
       at com.afollestad.materialdialogs.MaterialDialog$Builder.(MaterialDialog.java)
```

Other devices work fine.
Do you have any solutions?
Thanks.

**Comment by afollestad** [comment]
Sorry, there's probably nothing I can do. I use generic Android APIs to load typefaces, so there's not much that can go wrong.

**Comment by Dagzo** [comment]
Thanks for your quick reply.
You mean it is a bug of the device, right?

**Comment by afollestad** [comment]
Unfortunately, yes

**Comment by Dagzo** [comment]
Noted with thanks :smile:

**Comment by DIYwei** [comment]
It happened on some devices with Android 6.0.And is there one function for us to  forbidden the font？Thank you.

Fatal Exception: java.lang.IllegalArgumentException: No font asset found for 
       at com.afollestad.materialdialogs.MaterialDialog$Builder.typeface(MaterialDialog.java:653)
       at com.afollestad.materialdialogs.MaterialDialog$Builder.(MaterialDialog.java:522)
       at com.***.***.DialogManager.createButtonDialog(DialogManager.java:163)
       at com.***.***.MainActivity.onBackPressed(MainActivity.java:456)
       at android.app.Activity.onKeyUp(Activity.java:2511)
       at android.view.KeyEvent.dispatch(KeyEvent.java:2726)
       at android.app.Activity.dispatchKeyEvent(Activity.java:2764)
       at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:534)
       at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:50)
       at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:241)
       at com.android.internal.policy.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2353)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4659)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4615)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4111)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4164)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4130)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4276)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4138)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4333)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4111)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4164)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4130)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4138)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4111)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4164)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4130)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4309)
       at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4479)
       at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2330)
       at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1934)
       at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1925)
       at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2307)
       at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:328)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:5728)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
