### ISSUE TITLE
problem with collapsingtoolbar

### ISSUE THREAD

**Issue by faezesaghafi** [afollestad/material-dialogs#1130]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [ ] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.8.5.8`
 - Device OS version: `6.0.1`
 - Device Manufacturer: `Huawei`
 - Device Name: `Nexus 6P`

Also, please wrap Java with correct syntax highlighting.

```java
System.out.println("Hello, world!");
```
 
###### Reproduction Steps

1. 
2. 
3.

**Comment by faezesaghafi** [comment]
I want to use this dialogs in my apps because these can change direction of multiple choice list. I have CollapsingToolbarLayout in my app too, but when I add this lib to my gradle file this error happens. what can I do?
`FATAL EXCEPTION: main
                                                                              Process: ir.yasin.dordaneh.shahre_namha, PID: 6940
                                                                              android.view.InflateException: Binary XML file line #138: Error inflating class android.support.design.widget.CollapsingToolbarLayout
                                                                                  at android.view.LayoutInflater.createView(LayoutInflater.java:620)
                                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
                                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                                  at ir.yasin.dordaneh.shahre_namha.Show_Name.NameShowFragment.onCreateView(NameShowFragment.java:44)
                                                                                  at android.support.v4.app.Fragment.performCreateView(Fragment.java:2074)
                                                                                  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
                                                                                  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1286)
                                                                                  at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:758)
                                                                                  at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1632)
                                                                                  at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:637)
                                                                                  at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:166)
                                                                                  at android.support.v4.view.ViewPager.populate(ViewPager.java:1237)
                                                                                  at android.support.v4.view.ViewPager.populate(ViewPager.java:1085)
                                                                                  at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1611)
                                                                                  at android.view.View.measure(View.java:16538)
                                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5140)
                                                                                  at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:668)
                                                                                  at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:735)
                                                                                  at android.view.View.measure(View.java:16538)
                                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5140)
                                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                                  at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
                                                                                  at android.view.View.measure(View.java:16538)
                                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5140)
                                                                                  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1406)
                                                                                  at android.widget.LinearLayout.measureVertical(LinearLayout.java:697)
                                                                                  at android.widget.LinearLayout.onMeasure(LinearLayout.java:590)
                                                                                  at android.view.View.measure(View.java:16538)
                                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5140)
                                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                                  at android.view.View.measure(View.java:16538)
                                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5140)
                                                                                  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1406)
                                                                                  at android.widget.LinearLayout.measureVertical(LinearLayout.java:697)
                                                                                  at android.widget.LinearLayout.onMeasure(LinearLayout.java:590)
                                                                                  at android.view.View.measure(View.java:16538)
                                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5140)
                                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                                  at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2422)
                                                                                  at android.view.View.measure(View.java:16538)
                                                                                  at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1964)
                                                                                  at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1160)
                                                                                  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1342)
                                                                                  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1047)
                                                                                  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5896)
                                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
                                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:574)
                                                                                  at android.view.Choreographer.doFrame(Choreographer.java:544)
                                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
                                                                                  at android.os.Handler.handleCallback(Handler.java:733)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              	at android.os.Looper.loop(Lo`

**Comment by afollestad** [comment]
That log is completely unrelated to this library, so it doesn't belong in an issue here.
