### ISSUE TITLE
NullPointerException when try to open dialog on 4.4.4

### ISSUE THREAD

**Issue by jean2paulo** [afollestad/material-dialogs#1142]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.8.5.8`
 - Device OS version: `4.4.4`
 - Device Manufacturer: `Xiaomi`
 - Device Name: `Redmi 2`

Also, please wrap Java with correct syntax highlighting.

```java
new MaterialDialog.Builder(this)
                    .theme(Theme.LIGHT)
                    .title(R.string.payment_links)
                    .items(R.array.link_options)
                    .itemsCallbackSingleChoice(2, new MaterialDialog.ListCallbackSingleChoice() {
                        @Override
                        public boolean onSelection(MaterialDialog dialog, View itemView, int which, CharSequence text) {
                            String linkOrder = getString(R.string.omnichat_link_order);

                            if (which == 0) {  //Credit card
                                linkOrder = linkOrder.concat(getString(R.string.link_to_credit_card));
                            } else if (which == 1) {  //Boleto
                                linkOrder = linkOrder.concat(getString(R.string.link_to_boleto));
                            } else if (which == 2) {  //Credit card or Boleto

                            }
                            sharePaymentLink(linkOrder);
                            return true;
                        }
                    })
                    .positiveText(android.R.string.ok)
                    .build().show();
```
 
###### Reproduction Steps

1. When I try to open this Dialog at this device (android 4.4.4) it throws a NullPointerException;

###### Expected Result

- Open the dialog :D

###### Actual Result

```
Fatal Exception: java.lang.NullPointerException
       at android.support.v4.graphics.drawable.DrawableWrapperDonut.getState(DrawableWrapperDonut.java:147)
       at android.support.v4.graphics.drawable.DrawableWrapperDonut.setTintList(DrawableWrapperDonut.java:267)
       at android.support.v4.graphics.drawable.DrawableCompatBase.setTintList(DrawableCompatBase.java:42)
       at android.support.v4.graphics.drawable.DrawableCompat$BaseDrawableImpl.setTintList(DrawableCompat.java:94)
       at android.support.v4.graphics.drawable.DrawableCompat.setTintList(DrawableCompat.java:390)
       at com.afollestad.materialdialogs.internal.MDTintHelper.setTint(MDTintHelper.java:45)
       at com.afollestad.materialdialogs.DefaultAdapter.getView(DefaultAdapter.java:67)
       at android.widget.AbsListView.obtainView(AbsListView.java:2257)
       at android.widget.ListView.measureHeightOfChildren(ListView.java:1263)
       at android.widget.ListView.onMeasure(ListView.java:1175)
       at android.view.View.measure(View.java:16525)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:16525)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
       at android.view.View.measure(View.java:16525)
       at com.afollestad.materialdialogs.internal.MDRootLayout.onMeasure(MDRootLayout.java:199)
       at android.view.View.measure(View.java:16525)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:16525)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
       at android.view.View.measure(View.java:16525)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2291)
       at android.view.View.measure(View.java:16525)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1955)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1127)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1334)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1039)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5648)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
       at android.view.Choreographer.doCallbacks(Choreographer.java:574)
       at android.view.Choreographer.doFrame(Choreographer.java:544)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5113)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by afollestad** [comment]
You're using an old version of the library. Please actually check what the issue template asks you to check.
