### ISSUE TITLE
Error android.view.InflateException: Binary XML file line #1: Error inflating class <unknown>

### ISSUE THREAD

**Issue by aresares** [afollestad/material-dialogs#1150]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.9.0.0`
 - Device OS version: `4.4.4`
 - Device Manufacturer: `Samsung`
 - Device Name: `Galaxy S3`

Hi I'm trying to run this example

```java
ArrayList<String> sd=new ArrayList<>();
        sd.add("dffs");
        sd.add("dggggds");
        sd.add("4rfdsfc");

        new MaterialDialog.Builder(this)
                .title("TITOLO")
                .items(sd)
                .itemsCallback(new MaterialDialog.ListCallback() {
                    @Override
                    public void onSelection(MaterialDialog dialog, View view, int which, CharSequence text) {
                    }
                })
                .show()
```

but i get this error:

```bash
FATAL EXCEPTION: main
                                                                          Process: org.artoolkit.ar.samples, PID: 30051
                                                                          android.view.InflateException: Binary XML file line #1: Error inflating class <unknown>
                                                                              at android.view.LayoutInflater.createView(LayoutInflater.java:620)
                                                                              at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
                                                                              at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669)
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:469)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                              at com.afollestad.materialdialogs.DefaultRvAdapter.onCreateViewHolder(DefaultRvAdapter.java:50)
                                                                              at com.afollestad.materialdialogs.DefaultRvAdapter.onCreateViewHolder(DefaultRvAdapter.java:25)
                                                                              at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5779)
                                                                              at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5003)
                                                                              at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4913)
                                                                              at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
                                                                              at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1414)
                                                                              at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
                                                                              at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:578)
                                                                              at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3260)
                                                                              at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:2788)
                                                                              at android.view.View.measure(View.java:16521)
                                                                              at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                              at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                              at android.view.View.measure(View.java:16521)
                                                                              at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                              at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1450)
                                                                              at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                              at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                              at android.view.View.measure(View.java:16521)
                                                                              at com.afollestad.materialdialogs.internal.MDRootLayout.onMeasure(MDRootLayout.java:202)
                                                                              at android.view.View.measure(View.java:16521)
                                                                              at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                              at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                              at android.view.View.measure(View.java:16521)
                                                                              at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                              at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1450)
                                                                              at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                              at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                              at android.view.View.measure(View.java:16521)
                                                                              at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                              at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                              at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2552)
                                                                              at android.view.View.measure(View.java:16521)
                                                                              at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1915)
                                                                              at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1084)
                                                                              at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1291)
                                                                              at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
                                                                              at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5603)
                                                                              at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
                                                                              at android.view.Choreographer.doCallbacks(Choreographer.java:574)
                                                                              at android.view.Choreographer.doFrame(Choreographer.java:544)
                                                                              at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
                                                                              at android.os.Handler.handleCallback(Handler.java:733)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:136)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5146)
                                                                              at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          	at java.lang.reflect.Method.invoke(
```

**Comment by afollestad** [comment]
Sorry, I have no idea what the cause is. None of that log hints towards anything in this library.

**Comment by aresares** [comment]
Solved, just added `android:theme="@style/AppTheme"` to my application in the manifest file
