### ISSUE TITLE
android.view.InflateException: Binary XML file line #1: Error inflating class <unknown>

### ISSUE THREAD

**Issue by Vulneraria** [afollestad/material-dialogs#1158]
- [x ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x ] I have verified that I am using the latest version of Material Dialogs.
- [ x] I have given my issue a non-generic title.
- [ x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.9.0.1`
 - Device OS version: `4.4.2`
 - Device Manufacturer: `xx`
 - Device Name: `Nexus xx`

Also, please wrap Java with correct syntax highlighting.

```Gradle
android.view.InflateException: Binary XML file line #1: Error inflating class <unknown>
                                                                                    at android.view.LayoutInflater.createView(LayoutInflater.java:621)
                                                                                    at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
                                                                                    at android.view.LayoutInflater.onCreateView(LayoutInflater.java:670)
                                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:695)
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:469)
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                                    at com.afollestad.materialdialogs.DefaultRvAdapter.onCreateViewHolder(DefaultRvAdapter.java:50)
                                                                                    at com.afollestad.materialdialogs.DefaultRvAdapter.onCreateViewHolder(DefaultRvAdapter.java:25)
                                                                                    at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5779)
                                                                                    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5003)
                                                                                    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4913)
                                                                                    at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
                                                                                    at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1414)
                                                                                    at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
                                                                                    at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:578)
                                                                                    at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3260)
                                                                                    at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:2788)
                                                                                    at android.view.View.measure(View.java:16497)
                                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                                    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                                    at android.view.View.measure(View.java:16497)
                                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                                    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                                    at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                                    at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                                    at android.view.View.measure(View.java:16497)
                                                                                    at com.afollestad.materialdialogs.internal.MDRootLayout.onMeasure(MDRootLayout.java:203)
                                                                                    at android.view.View.measure(View.java:16497)
                                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                                    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                                    at android.view.View.measure(View.java:16497)
                                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                                    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                                    at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                                    at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                                    at android.view.View.measure(View.java:16497)
                                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                                    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                                    at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2291)
                                                                                    at android.view.View.measure(View.java:16497)
                                                                                    at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1916)
                                                                                    at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1088)
                                                                                    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1295)
                                                                                    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
                                                                                    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5670)
                                                                                    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
                                                                                    at android.view.Choreographer.doCallbacks(Choreographer.java:574)
                                                                                    at android.view.Choreographer.doFrame(Choreographer.java:544)
                                                                                    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
                                                                                    at android.os.Handler.handleCallback(Handler.java:733)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                    at android.os.Looper.loop(Looper.java:136)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                	at java.lang.reflect.Method.
```
 
###### Reproduction Steps

 ```java
new MaterialDialog.Builder(mContext)
                            .title(R.string.Activity)
                            .items(R.array.Activity)
                            .itemsCallbackSingleChoice(-1, new MaterialDialog.ListCallbackSingleChoice() {
                                @Override
                                public boolean onSelection(MaterialDialog dialog, View view, int which, CharSequence text) {
                                    String[] arrayActivity = getResources().getStringArray(R.array.Activity);
                                    if (text.equals(arrayActivity[5])) {
                                        Intent addactivity = new Intent(mContext, Breastfeeding.class);
                                        addactivity.putExtra("TIME", finalMills);
                                        addactivity.putExtra("NAME", namesel);
                                        startActivity(addactivity);
                                        page = i;
                                    } else {
                                        Intent addactivity = new Intent(mContext, AddActivities.class);
                                        addactivity.putExtra("ACTIVITY", text);
                                        addactivity.putExtra("TIME", finalMills);
                                        addactivity.putExtra("NAME", namesel);
                                        startActivity(addactivity);
                                        page = i;
                                    }
                                    return false;
                                }
                            })
                            .positiveText(R.string.choose)
                            .show();
```
                    
1. use single choice list dialog.

**Comment by Vandalko** [comment]
I believe it is caused by this line https://github.com/afollestad/material-dialogs/blob/0.9.0.1/core/src/main/res/layout/md_listitem.xml#L5

`selectableItemBackground` is a part of appcompat so you have to use Theme.AppCompat and if you are not... than inlfation failing because it can't find theme attribute reference.

**Comment by Vandalko** [comment]
@afollestad btw, I wonder why you don't use [AppCompatDialog](https://developer.android.com/reference/android/support/v7/app/AppCompatDialog.html) ?

It's already present in library's dependencies and the theming / customizing process it the same as aforementioned `md_listitem.xml` resource

[DialogBase](https://github.com/afollestad/material-dialogs/blob/0.9.0.1/core/src/main/java/com/afollestad/materialdialogs/DialogBase.java#L14) is an ordinary Dialog which heavily depends on current platform implementation while AppCompatDialog allow to properly theme a dialog

**Comment by afollestad** [comment]
All the proper theming is done by this library.

**Comment by Fleker** [comment]
The requirement of `AppCompatActivity` conflicts with being able to use a `LeanbackActivity` for TV.
