### ISSUE TITLE
Problem with Collapsing toolbar

### ISSUE THREAD

**Issue by AmiNadim** [afollestad/material-dialogs#1161]
- Material Dialogs version: `0.9.0.1`
 - Device OS version: `kitkat`
 - Device Manufacturer: `HTC`
 - Device Name: `Desire 820`
 - Activity Type : `AppCompatActivity`
 - Support Library : `com.android.support:design:23.4.0`
Whenever I use the dialog in my activity i encounter this exception : 

FATAL EXCEPTION: main
                                                   Process: dim.intellivase, PID: 10979
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{dim.intellivase/dim.intellivase.BaseContainer}: android.view.InflateException: Binary XML file line #18: Error inflating class android.support.design.widget.CollapsingToolbarLayout
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2439)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495)
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:153)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:157)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5633)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:896)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)
                                                       at dalvik.system.NativeStart.main(Native Method)
                                                    Caused by: android.view.InflateException: Binary XML file line #18: Error inflating class android.support.design.widget.CollapsingToolbarLayout
                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:620)
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280)
                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                       at dim.intellivase.BaseContainer.InitializeActivity(BaseContainer.java:48)
                                                       at dim.intellivase.BaseContainer.onCreate(BaseContainer.java:21)
                                                       at android.app.Activity.performCreate(Activity.java:5312)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2395)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495) 
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:153) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:157) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5633) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:896) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712) 
                                                       at dalvik.system.NativeStart.main(Native Method) 
                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                       at java.lang.reflect.Constructor.constructNative(Native Method)
                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:594)
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                       at dim.intellivase.BaseContainer.InitializeActivity(BaseContainer.java:48) 
                                                       at dim.intellivase.BaseContainer.onCreate(BaseContainer.java:21) 
                                                       at android.app.Activity.performCreate(Activity.java:5312) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2395) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495) 
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:153) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:157) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5633) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:896) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712) 
                                                       at dalvik.system.NativeStart.main(Native Method) 
                                                    Caused by: java.lang.NoSuchMethodError: android.support.v4.graphics.drawable.DrawableCompat.setLayoutDirection
                                                       at android.support.design.widget.CollapsingToolbarLayout.setStatusBarScrim(CollapsingToolbarLayout.java:663)
                                                       at android.support.design.widget.CollapsingToolbarLayout.<init>(CollapsingToolbarLayout.java:197)
                                                       at android.support.design.widget.CollapsingToolbarLayout.<init>(CollapsingToolbarLayout.java:132)
                                                       at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:594) 
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                       at dim.intellivase.BaseContainer.InitializeActivity(BaseContainer.java:48) 
                                                       at dim.intellivase.BaseContainer.onCreate(BaseContainer.java:21) 
                                                       at android.app.Activity.performCreate(Activity.java:5312) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2395) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495) 
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:153) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:157) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5633) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:896) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712) 
                                                       at dalvik.system.NativeStart.main(Native Method) 
 E/ActivityManager: App crashed! Process: dim.intellivase

**Comment by afollestad** [comment]
That log has nothing to do with my library.
