### ISSUE TITLE
android.os.IBinder android.view.View.getWindowToken()' on a null object reference

### ISSUE THREAD

**Issue by starktonys** [afollestad/material-dialogs#1218]
when i use  this repo, my device is landscape
code:
new MaterialDialog.Builder(this).title(R.string.input)
        .content(R.string.input_content)
        .inputRangeRes(2, 16, R.color.md_red_500)
        .inputType(InputType.TYPE_CLASS_TEXT)
        .input(R.string.input_hint, R.string.input_prefill, new MaterialDialog.InputCallback() {
          @Override public void onInput(MaterialDialog dialog, CharSequence input) {
            if (!TextUtils.isEmpty(input.toString())) mPresenter.changeNickName(input.toString());
          }
        })
        .show();

i click the button ,then crash the follow message

java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.IBinder android.view.View.getWindowToken()' on a null object reference
                                                                           at com.afollestad.materialdialogs.util.DialogUtils.hideKeyboard(DialogUtils.java:226)
                                                                           at com.afollestad.materialdialogs.MaterialDialog.dismiss(MaterialDialog.java:1810)
                                                                           at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:343)
                                                                           at android.view.View.performClick(View.java:5610)
                                                                           at android.view.View$PerformClick.run(View.java:22260)
                                                                           at android.os.Handler.handleCallback(Handler.java:751)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by starktonys** [comment]
# #
