### ISSUE TITLE
Bug showing list dialog

### ISSUE THREAD

**Issue by carboleda** [afollestad/material-dialogs#1226]
###### Enviroment infomation:
 - Material Dialogs version: `0.9.1.0`
 - Device OS version: `4.3`
 - Device Manufacturer: `Samsung`
 - Device Name: `Galaxy S3`

###### The array:
```xml
<string-array name="photo_source_types" translatable="false">
        <item>Take photo</item>
        <item>Choose from gallery</item>
        <item>Cancel</item>
</string-array>
```
###### The java code:
```java
new MaterialDialog.Builder(this)
                .title(R.string.photo)
                .theme(Theme.LIGHT)
                .cancelable(false)
                .autoDismiss(true)
                .items(R.array.photo_source_types)
                .itemsCallback(this)
                .show();
```

###### Expected Result
![material_dialogs_show_bug](https://cloud.githubusercontent.com/assets/4198484/20861503/dc759c92-b95f-11e6-94ff-091ac885f86a.png)

###### Actual Result
It seems that the error has to do with the attribute android:background="?selectableItemBackground" on [material-dialogs/core/src/main/res/layout/md_listitem.xml](url) layout.

On 0.8.6.2 version it work successfully.

```java
android.view.InflateException: Binary XML file line #1: Error inflating class <unknown>
at android.view.LayoutInflater.createView(LayoutInflater.java:626)
at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
at android.view.LayoutInflater.onCreateView(LayoutInflater.java:675)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:700)
at android.view.LayoutInflater.inflate(LayoutInflater.java:470)
at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
at com.afollestad.materialdialogs.DefaultRvAdapter.onCreateViewHolder(DefaultRvAdapter.java:51)
at com.afollestad.materialdialogs.DefaultRvAdapter.onCreateViewHolder(DefaultRvAdapter.java:26)
at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6078)
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5248)
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5158)
at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2061)
at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1445)
at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1408)
at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:580)
at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3379)
at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:2906)
at android.view.View.measure(View.java:16831)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
at android.view.View.measure(View.java:16831)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1410)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
at android.view.View.measure(View.java:16831)
at com.afollestad.materialdialogs.internal.MDRootLayout.onMeasure(MDRootLayout.java:200)
at android.view.View.measure(View.java:16831)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
at android.view.View.measure(View.java:16831)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1410)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
at android.view.View.measure(View.java:16831)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2586)
at android.view.View.measure(View.java:16831)
at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2189)
at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1327)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1535)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1249)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6364)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
at android.view.Choreographer.doCallbacks(Choreographer.java:591)
at android.view.Choreographer.doFrame(Choreographer.java:561)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
at android.os.Handler.handleCallback(Handler.java:730)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:176)
at android.app.ActivityThread.main(ActivityThread.java:5419)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodA
```

**Comment by AndyGu** [comment]
same question on my devices which use 25 compileSdkVersion

**Comment by afollestad** [comment]
Unable to reproduce. This is probably a Samsung issue.

**Comment by carboleda** [comment]
Thanks, probably this not work in android 4.3. I downgraded to 0.8.6.2 version and work successfully.
