### ISSUE TITLE
[BUG] You can not set Dialog's OnCancelListener or OnDismissListener

### ISSUE THREAD

**Issue by peppe130** [afollestad/material-dialogs#1230]
```java

                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
                                                                             at android.app.ActivityThread.access$1100(ActivityThread.java)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
                                                                             at android.os.Handler.dispatchMessage(Handler.java)
                                                                             at android.os.Looper.loop(Looper.java)
                                                                             at android.app.ActivityThread.main(ActivityThread.java)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
                                                                          Caused by: java.lang.IllegalStateException: You can not set Dialog's OnCancelListener or OnDismissListener
                                                                             at android.app.DialogFragment.onActivityCreated(DialogFragment.java)
                                                                             at android.app.Fragment.performActivityCreated(Fragment.java)
                                                                             at android.app.FragmentManagerImpl.moveToState(FragmentManager.java)
                                                                             at android.app.FragmentManagerImpl.moveToState(FragmentManager.java)
                                                                             at android.app.BackStackRecord.run(BackStackRecord.java)
                                                                             at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java)
                                                                             at android.app.FragmentController.execPendingActions(FragmentController.java)
                                                                             at android.app.Activity.performStart(Activity.java)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java) 
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java) 
                                                                             at android.app.ActivityThread.access$1100(ActivityThread.java) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java) 
                                                                             at android.os.Looper.loop(Looper.java) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java) 

```

Hi, I'm using the latest version of this library and I got this error. In my File Chooser dialog I've not set any dismiss or cancel listener. So I can't understand why this error occurs. Any solution? Thanks.

**Comment by afollestad** [comment]
Because it's a `DialogFragment`, not a `Dialog`. That isn't specific to this library.
