### ISSUE TITLE
App crashes, FolderChooserDialog NullPointerException while trying to exit form the device root

### ISSUE THREAD

**Issue by AndreaCioccarelli** [afollestad/material-dialogs#1244]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

### General info:
 - Material Dialogs version: `0.9.1.0`
 - Device OS version: `6.0.1`
 - Device Manufacturer: `Samsung`
 - Device Name: `Samsung Galaxy S6 edge`

```java
new FolderChooserDialog.Builder(MainActivity.this)
                .chooseButton(R.string.md_choose_label)  // changes label of the choose button
                .initialPath("/")  // changes initial path, defaults to external storage directory
                .tag("path-tag")
                .show();
```
 
### Reproduction Steps

1. Create a new FolderChooserDialog and set it's initialPath in the root directory ("/")
2. Build and open the application
3. You can now see, in the folder list, a "...", also if you are in the device root

### Expected Result
We shouldn't see these dots, infact normally you cannot go up if you are in the root folder

### Actual Result
The app crashes due to a NullPointerException because the canGoUp boolean is true at the first dialog start. if you try to enter in a random directory and to go up, you cannot see the "..." because canGoUp = false

`java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
                                                                                     at com.afollestad.materialdialogs.folderselector.FolderChooserDialog.onSelection(FolderChooserDialog.java:148)
                                                                                     at com.afollestad.materialdialogs.MaterialDialog.onItemSelected(MaterialDialog.java:175)
                                                                                     at com.afollestad.materialdialogs.DefaultRvAdapter$DefaultVH.onClick(DefaultRvAdapter.java:173)
                                                                                     at android.view.View.performClick(View.java:5702)
                                                                                     at android.view.View$PerformClick.run(View.java:22541)
                                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                     at android.os.Looper.loop(Looper.java:158)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:7229)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

### Original Code
```java
@Override
    public void onSelection(MaterialDialog materialDialog, View view, int i, CharSequence s) {
        if (canGoUp && i == 0) {
            parentFolder = parentFolder.getParentFile();
            if (parentFolder.getAbsolutePath().equals("/storage/emulated"))
                parentFolder = parentFolder.getParentFile();
            canGoUp = parentFolder.getParent() != null;
        } else {
            parentFolder = parentContents[canGoUp ? i - 1 : i];
            canGoUp = true;
            if (parentFolder.getAbsolutePath().equals("/storage/emulated"))
                parentFolder = Environment.getExternalStorageDirectory();
        }
        reload();
    }
```

**Comment by afollestad** [comment]
I'm guessing you just can't use the root directory. You need special access.

**Comment by AndreaCioccarelli** [comment]
![screenshot_20161225-133702](https://cloud.githubusercontent.com/assets/23010471/21471140/530450ee-caa7-11e6-8e0e-68b6e0cd3901.png)

**Comment by AndreaCioccarelli** [comment]
I have get ACCESS_SUPERUSER, READ_EXTERNAL_STORAGE and I've set my context as u:r:init:s0.
This is a material-dialog error because it cannot determine if you are in the root directory at the first dialogue launch. To fix you could reinforce the memory control.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.9.2.1
