### ISSUE TITLE
Dialog onClick Crash sometimes 

### ISSUE THREAD

**Issue by ankitagrawal2411** [afollestad/material-dialogs#1262]
```Gradle
java.lang.ArrayIndexOutOfBoundsException: length=1; index=-1
       at java.util.ArrayList.get(ArrayList.java:310)
       at com.afollestad.materialdialogs.DefaultRvAdapter$DefaultVH.onClick(DefaultRvAdapter.java:172)
       at android.view.View.performClick(View.java:5201)
       at android.view.View$PerformClick.run(View.java:21215)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5525)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
```

The cause:

```java
@Override
        public void onClick(View view) {
            if (adapter.callback != null) {
                CharSequence text = null;
                if (adapter.dialog.builder.items != null && getAdapterPosition() < adapter.dialog.builder.items.size())
                    text = adapter.dialog.builder.items.get(getAdapterPosition());
                adapter.callback.onItemSelected(adapter.dialog, view, getAdapterPosition(), text, false);
            }
        }

        @Override
        public boolean onLongClick(View view) {
            if (adapter.callback != null) {
                CharSequence text = null;
                if (adapter.dialog.builder.items != null && getAdapterPosition() < adapter.dialog.builder.items.size())
                    text = adapter.dialog.builder.items.get(getAdapterPosition());
                return adapter.callback.onItemSelected(adapter.dialog, view, getAdapterPosition(), text, true);
            }
            return false;
}
```

In Both onClick and onLongClick method you are using getAdapterPosition() and it can return -1 
sometimes as per docs .
Please add a check to getAdapterPosition()!=RecyclerView.NO_POSITION in both the methods 

If you want I could make a PR

**Comment by ankitagrawal2411** [comment]
resolved via merge so closing
