### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by my519820363** [afollestad/material-dialogs#1265]
0.9.2.3、0.9.2.2、0.9.2.1 版本使用：
```
new MaterialDialog.Builder(TestActivity.this)
                        .title("title")
                        .items(new String[]{"测试"})
                        .itemsCallback(new MaterialDialog.ListCallback() {

                            @Override
                            public void onSelection(MaterialDialog dialog, View view, int which, CharSequence text) {

                            }
                        })
                        .show();
```
引发崩溃：
```
catch exception when loading tinker:android.view.InflateException: Binary XML file line #1: Binary XML file line #1: Error inflating class <unknown>
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:543)
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
                                                                                  at com.afollestad.materialdialogs.DefaultRvAdapter.onCreateViewHolder(DefaultRvAdapter.java:51)
                                                                                  at com.afollestad.materialdialogs.DefaultRvAdapter.onCreateViewHolder(DefaultRvAdapter.java:25)
                                                                                  at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6290)
                                                                                  at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5478)
                                                                                  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5363)
                                                                                  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5359)
                                                                                  at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2141)
                                                                                  at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1525)
                                                                                  at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1488)
                                                                                  at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:585)
                                                                                  at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3506)
                                                                                  at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:2969)
                                                                                  at android.view.View.measure(View.java:18811)
                                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                  at android.view.View.measure(View.java:18811)
                                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                                  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                                  at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                                  at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                                  at android.view.View.measure(View.java:18811)
                                                                                  at com.afollestad.materialdialogs.internal.MDRootLayout.onMeasure(MDRootLayout.java:207)
                                                                                  at android.view.View.measure(View.java:18811)
                                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                  at android.view.View.measure(View.java:18811)
                                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                                  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                                  at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                                  at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                                  at android.view.View.measure(View.java:18811)
                                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                  at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
                                                                                  at android.view.View.measure(View.java:18811)
                                                                                  at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2127)
                                                                                  at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1243)
                                                                                  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1479)
                                                                                  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1134)
                                                                                  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6050)
                                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
                                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:672)
                                                                                  at android.view.Choreographer.doFrame(Choreographer.java:608)
                                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
                                                                                  at android.os.Handler.handleCallback(Handler.java:742)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                  at android.os.Looper.loop(Looper.java:154)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5462)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
                                                                               Caused by: android.view.InflateException: Binary XML file line #1: Error inflating class <unkn
```

同样的代码在0.8.6.2一切正常。0.9.0.0未测试

**Comment by afollestad** [comment]
Unfortunately, nothing here points to anything in this library.

**Comment by my519820363** [comment]
```
Binary XML file line #1: Binary XML file line #1: Error inflating class <unknown>
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:543)
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
                                                                                  at com.afollestad.materialdialogs.**DefaultRvAdapter**.onCreateViewHolder(DefaultRvAdapter.java:51)
                                                                                  at com.afollestad.materialdialogs.**DefaultRvAdapter**.onCreateViewHolder(DefaultRvAdapter.java:25)
```

the DefaultRvAdapter is the Library code i think:)
