### ISSUE TITLE
Crash in MDRootLayout in several devices

### ISSUE THREAD

**Issue by aritraroy** [afollestad/material-dialogs#1272]
I am getting a crash due to this library for several of my users. Here is the complete stack trace I get in CrshAnalytics.

```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=125; index=-1
       at android.text.StaticLayout.calculateEllipsis(StaticLayout.java:740)
       at android.text.StaticLayout.out(StaticLayout.java:704)
       at android.text.StaticLayout.generate(StaticLayout.java:410)
       at android.text.StaticLayout.(StaticLayout.java)
       at android.widget.TextView.makeSingleLayout(TextView.java:6299)
       at android.widget.TextView.makeNewLayout(TextView.java:6156)
       at android.widget.TextView.onMeasure(TextView.java:6513)
       at android.view.View.measure(View.java:16820)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
       at android.view.View.measure(View.java:16820)
       at android.support.v7.widget.RecyclerView$LayoutManager.measureChildWithMargins(SourceFile:8456)
       at android.support.v7.widget.LinearLayoutManager.layoutChunk(SourceFile:1551)
       at android.support.v7.widget.LinearLayoutManager.fill(SourceFile:1488)
       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(SourceFile:585)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(SourceFile:3506)
       at android.support.v7.widget.RecyclerView.onMeasure(SourceFile:2969)
       at android.view.View.measure(View.java:16820)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5156)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:16820)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5156)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
       at android.view.View.measure(View.java:16820)
       at com.afollestad.materialdialogs.internal.MDRootLayout.onMeasure(SourceFile:207)
       at android.view.View.measure(View.java:16820)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5156)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:16820)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5156)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
       at android.view.View.measure(View.java:16820)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5156)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2294)
       at android.view.View.measure(View.java:16820)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1969)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1162)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1348)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1049)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5899)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:771)
       at android.view.Choreographer.doCallbacks(Choreographer.java:574)
       at android.view.Choreographer.doFrame(Choreographer.java:544)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:757)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:149)
       at android.app.ActivityThread.main(ActivityThread.java:5268)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

Initially, I used to ignore this crash as it didn't happen for many users, but now it has started becoming more frequent. I am already on the latest version of this library.

Any idea on what is wrong here?

**Comment by afollestad** [comment]
What devices? Samsung devices?

Unfortunately there isn't anything here that makes the cause obvious.

**Comment by aritraroy** [comment]
According to CrashAnalytics, these are some of the devices having the issue.

1) ASUS_Z007
2) Lenovo A5500-HV
3) LG-K332
4) Lenovo A6020a40
5) LG-D802
6) HUAWEI Y560-L01
7) Redmi Note 3
8) Lenovo S856

and many more.

**Comment by afollestad** [comment]
Android version?

**Comment by aritraroy** [comment]
Several versions, 4.4.2, 5.1.1, 5.0.2, 5.1 and more.

**Comment by afollestad** [comment]
Well if you're able to reproduce a cause, that would be great.

But I won't be able to do anything currently.

**Comment by aritraroy** [comment]
If I could have reproduced a cause, I would have either fixed it myself or mentioned it already.

**Comment by afollestad** [comment]
I don't there's anything I'll be able to do on my end here.
