### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 

### ISSUE THREAD

**Issue by smaznet** [afollestad/material-dialogs#1273]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
       at android.support.v4.content.ContextCompat.getColor(ContextCompat.java:368)
       at com.afollestad.materialdialogs.util.DialogUtils.getColor(DialogUtils.java:125)
       at com.afollestad.materialdialogs.MaterialDialog$Builder.(MaterialDialog.java)
       at org.telegram.ui.LoginActivity.needFinishActivity(LoginActivity.java:555)
       at org.telegram.ui.LoginActivity.access$800(LoginActivity.java:105)
       at org.telegram.ui.LoginActivity$LoginActivitySmsView$8$1.run(LoginActivity.java:1683)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5910)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)

device samsung SM-G361H

android ver 5.1.1

library :
 PUBLISH_ARTIFACT_ID = 'core'
    PUBLISH_VERSION = '0.9.1.0'

**Comment by smaznet** [comment]
Error:(24, 13) Failed to resolve: com.afollestad.material-dialogs:core:0.9.2.3


when i want update it i got this error

offline mode is disabled
