### ISSUE TITLE
how to add scrollbar to input dialog?

### ISSUE THREAD

**Issue by or-dvir** [afollestad/material-dialogs#1355]
- [ ] I looked through the "issues" section and did not see a duplicate.
- [ ] I have verified that I am using the latest version of Material Dialogs.
- [ ] I have given my issue a non-generic title.
- [ ] I have read over the documentation and did not find an answer.

###### Include the following:
 - Material Dialogs version: 0.9.4.3
 - Device OS version: 6.0
 - Device Manufacturer: LG
 - Device Name: G3
 
i can't seem to be able to add a scrollbar to my input dialog.

this is my code:

```
EditText et = dialog.getInputEditText();
et.setMaxLines(4);
et.setVerticalScrollBarEnabled(true);
et.setMovementMethod(new ScrollingMovementMethod());
```
but it is not working.

if i add this line `et.setScrollbarFadingEnabled(false);` i get the following exception:

```
FATAL EXCEPTION: main
                                                                                Process: or_dvir.hotmail.com.arislist.dev, PID: 6178
                                                                                java.lang.NullPointerException: Attempt to invoke virtual method 'android.widget.ScrollBarDrawable android.widget.ScrollBarDrawable.mutate()' on a null object reference
                                                                                    at android.view.View.onDrawScrollBars(View.java:13931)
                                                                                    at android.view.View.onDrawForeground(View.java:17729)
                                                                                    at android.view.View.draw(View.java:16249)
                                                                                    at android.view.View.updateDisplayListIfDirty(View.java:15235)
                                                                                    at android.view.View.draw(View.java:16008)
                                                                                    at android.view.ViewGroup.drawChild(ViewGroup.java:3653)
                                                                                    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3443)
                                                                                    at android.view.View.updateDisplayListIfDirty(View.java:15230)
                                                                                    at android.view.View.draw(View.java:16008)
                                                                                    at android.view.ViewGroup.drawChild(ViewGroup.java:3653)
                                                                                    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3443)
                                                                                    at android.view.View.updateDisplayListIfDirty(View.java:15230)
                                                                                    at android.view.View.draw(View.java:16008)
                                                                                    at android.view.ViewGroup.drawChild(ViewGroup.java:3653)
                                                                                    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3443)
                                                                                    at android.view.View.draw(View.java:16241)
                                                                                    at android.view.View.updateDisplayListIfDirty(View.java:15235)
                                                                                    at android.view.View.draw(View.java:16008)
                                                                                    at android.view.ViewGroup.drawChild(ViewGroup.java:3653)
                                                                                    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3443)
                                                                                    at android.view.View.updateDisplayListIfDirty(View.java:15230)
                                                                                    at android.view.View.draw(View.java:16008)
                                                                                    at android.view.ViewGroup.drawChild(ViewGroup.java:3653)
                                                                                    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3443)
                                                                                    at android.view.View.updateDisplayListIfDirty(View.java:15230)
                                                                                    at android.view.View.draw(View.java:16008)
                                                                                    at android.view.ViewGroup.drawChild(ViewGroup.java:3653)
                                                                                    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3443)
                                                                                    at android.view.View.draw(View.java:16241)
                                                                                    at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2709)
                                                                                    at android.view.View.updateDisplayListIfDirty(View.java:15235)
                                                                                    at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
                                                                                    at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
                                                                                    at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
                                                                                    at android.view.ViewRootImpl.draw(ViewRootImpl.java:2681)
                                                                                    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2495)
                                                                                    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2124)
                                                                                    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1140)
                                                                                    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6232)
                                                                                    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                                    at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                                    at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                                    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                                    at android.os.Handler.handleCallback(Handler.java:739)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5551)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
```

**Comment by afollestad** [comment]
This isn't really an issue specific to this library. 

You should just wrap an `EditText` in a `ScrollView` in a custom view dialog.
