### ISSUE TITLE
Why I always use this time when the wrong report

### ISSUE THREAD

**Issue by l5892005** [afollestad/material-dialogs#1360]
```gradle
 Process: com.ld.weighttable, PID: 10201
 android.view.InflateException: Binary XML file line #1: Binary XML file line #1: Error inflating class <unknown>
at android.view.LayoutInflater.inflate(LayoutInflater.java:551)
at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
at com.afollestad.materialdialogs.DefaultRvAdapter.onCreateViewHolder(DefaultRvAdapter.java:42)
at com.afollestad.materialdialogs.DefaultRvAdapter.onCreateViewHolder(DefaultRvAdapter.java:23)
 at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6367)
```

I just want to use the dialog box to pop up a list，

E.g.
```java
new MaterialDialog.Builder(this)
                .title("你大爷永远都是你大爷")
                .items("条目1","条目2")
                .itemsCallback(new MaterialDialog.ListCallback() {
                    @Override
                    public void onSelection(MaterialDialog dialog, View view, int which, CharSequence text) {
                    }
                })
                .show();
```

**Comment by afollestad** [comment]
There's not enough information here to see any obvious problems in my code.

I'm not able to reproduce any issues here.

**Comment by 19861125** [comment]
same error
