### ISSUE TITLE
Null Context is passed in from Fragment

### ISSUE THREAD

**Issue by jlelse** [afollestad/material-dialogs#1392]
Firebase reports me crashes on multiple devices with API >= 23 with this Stacktrace:

```gradle
Exception java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Context.getColor(int)' on a null object reference
android.support.v4.content.ContextCompatApi23.getColor (ContextCompatApi23.java:32)
android.support.v4.content.ContextCompat.getColor (ContextCompat.java:432)
com.afollestad.materialdialogs.util.DialogUtils.getColor (DialogUtils.java:126)
com.afollestad.materialdialogs.MaterialDialog$Builder.<init> (MaterialDialog.java:1180)
jlelse.newscatchr.ui.fragments.SettingsFragment.onPreferenceClick (SettingsFragment.kt:161)
android.support.v7.preference.Preference.performClick (Preference.java:982)
android.support.v7.preference.Preference.performClick (Preference.java:965)
android.support.v7.preference.Preference$1.onClick (Preference.java:149)
android.view.View.performClick (View.java:5685)
android.view.View$PerformClick.run (View.java:22481)
android.os.Handler.handleCallback (Handler.java:751)
android.os.Handler.dispatchMessage (Handler.java:95)
```

I guess there's an issue somewhere in your code. I just use this code (Kotlin) to show a simple dialog:

```kotlin
MaterialDialog.Builder(context)
						.title(R.string.used_libraries)
						.content(html.toHtml())
						.positiveText(android.R.string.ok)
						.build()
						.apply {
							contentView?.applyLinks(false)
							show()
						}
```

**Comment by Mauker1** [comment]
I was about to open an issue with this problem. I'm getting crash reports through Crashlytics with *almost* the same stack trace.

**Device where it happened:** Galaxy Tab3 Lite 7.0 (SM-G530H)
**Android version:** 4.4.4 (API 19)

Stacktrace
---
```java
Fatal Exception: java.lang.NullPointerException
       at com.afollestad.materialdialogs.util.DialogUtils.getColor(DialogUtils.java:126)
       at com.afollestad.materialdialogs.MaterialDialog$Builder.<init>(MaterialDialog.java:491)
       at br.com.pentagrama.vuptonline.fragments.NotificationsFragment.getNotifications(NotificationsFragment.java:134)
       at br.com.pentagrama.vuptonline.fragments.NotificationsFragment.access$100(NotificationsFragment.java:41)
       at br.com.pentagrama.vuptonline.fragments.NotificationsFragment$2.onClick(NotificationsFragment.java:235)
       at android.support.design.widget.Snackbar$1.onClick(Snackbar.java:250)
       at android.view.View.performClick(View.java:4496)
       at android.view.View$PerformClick.run(View.java:18603)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5426)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by AdamMc331** [comment]
Are you 100% sure the context you're using isn't null at the time this is called?

**Comment by Mauker1** [comment]
I'm not 100% sure of that. Is it possible for an attached fragment to return `null` on `getActivity()`? As for OP, we can't be sure on which context he's using.

**Comment by jlelse** [comment]
Any progress on this issue?

**Comment by vivek50** [comment]
my app going to be crash...
And show me this error..

FATAL EXCEPTION: main
Process: com.xmxsolutions.firstapplication, PID: 30494                                                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'int com.afollestad.materialdialogs.DialogAction.ordinal()' on a null object reference                                                                                       at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:402)                                                                                      at android.view.View.performClick(View.java:5210)                                                                                       
at android.view.View$PerformClick.run(View.java:21169)                                                                                       at android.os.Handler.handleCallback(Handler.java:739)                                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)                                                                                       at android.os.Looper.loop(Looper.java:148)                                                                                       
at android.app.ActivityThread.main(ActivityThread.java:5451)                                                                                       at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

i am also passing right context,
here is my code...

getEdtMarital(view).setOnClickListener(new MaterialDialog.Builder(getActivity())
                .title("Select Marital Status")
                .items(R.array.array_marital_status)
                .typeface(getEdtName(view).getTypeface(), getEdtName(view).getTypeface())
                .itemsCallback(new MaterialDialog.ListCallback() {
        @Override
         public void onSelection(MaterialDialog dialog, View itemView, int position, CharSequencetext) {
                        
           }
    }).show());

**Comment by afollestad** [comment]
@jlelse your log at the top indicates you are passing a null context into `MaterialDialog.Builder`'s constructor.

**Comment by vivek50** [comment]
Ok...Thank You....Silly MIstake from me..
