### ISSUE TITLE
NPE android.os.IBinder android.view.View.getWindowToken()

### ISSUE THREAD

**Issue by bootstraponline** [afollestad/material-dialogs#1467]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.IBinder android.view.View.getWindowToken()' on a null object reference
FATAL EXCEPTION: main
Process: com.instructure.parentapp, PID: 7385
java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.IBinder android.view.View.getWindowToken()' on a null object reference
    at com.afollestad.materialdialogs.util.DialogUtils.hideKeyboard(DialogUtils.java:226)
    at com.afollestad.materialdialogs.MaterialDialog.dismiss(MaterialDialog.java:1810)
    at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:363)
    at android.view.View.performClick(View.java:5637)
    at android.view.View$PerformClick.run(View.java:22429)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6119)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

I'm seeing this NPE on `Low-resolution MDPI phone, Virtual, API Level 25`. 

[DialogUtils](https://github.com/afollestad/material-dialogs/blob/1ce3af634402f61fc0afb4d026c9480cf8302a35/core/src/main/java/com/afollestad/materialdialogs/util/DialogUtils.java#L259) is calling `getWindowToken()` without checking `getView` is non-null.
>  currentFocus != null ? currentFocus.getWindowToken() : dialog.getView().getWindowToken();

Version: `com.github.afollestad.material-dialogs:core:0.8.5.2@aar`

In version 0.8.5.2 the above is:

> imm.hideSoftInputFromWindow(dialog.getCurrentFocus().getWindowToken(), 0);

The latest version is less likely to trigger the crash due to the additional null guard.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.9.5.0
