### ISSUE TITLE
Sporadic IllegalStateException while creating ProgressDialog

### ISSUE THREAD

**Issue by kamyll2** [afollestad/material-dialogs#1473]
- Material Dialogs version: `0.8.5.3`
 - Device OS version: `6.0.1`
 - Device Manufacturer: `motorola`
 - Device Name: `Moto X Play`
 
I get this error from crash reporting system. It happened only once on single device described above.
Stacktrace:

`Fatal Exception: java.lang.ExceptionInInitializerError
       at me.zhanghai.android.materialprogressbar.Animators.createIndeterminate(Animators.java:149)
       at me.zhanghai.android.materialprogressbar.IndeterminateProgressDrawable.(IndeterminateProgressDrawable.java)
       at com.afollestad.materialdialogs.DialogInit.setupProgressDialog(DialogInit.java:369)
       at com.afollestad.materialdialogs.DialogInit.init(DialogInit.java:297)
       at com.afollestad.materialdialogs.MaterialDialog.(MaterialDialog.java)
       at com.afollestad.materialdialogs.MaterialDialog$Builder.build(MaterialDialog.java:1335)
       at ---Activity.showProgressDialog(---Activity.java:213)
       at ---Activity.onOptionsItemSelected(---Activity.java:151)
       at android.app.Activity.onMenuItemSelected(Activity.java:2918)
       at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:361)
       at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
       at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
       at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
       at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:65)
       at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:202)
       at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:780)
       at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
       at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:171)
       at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:973)
       at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:963)
       at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:624)
       at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:150)
       at android.view.View.performClick(View.java:5207)
       at android.view.View$PerformClick.run(View.java:21168)
       at android.os.Handler.handleCallback(Handler.java:746)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5443)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
Caused by java.lang.IllegalArgumentException: The Path must start at (0,0) and end at (1,1)
       at android.view.animation.PathInterpolator.initPath(PathInterpolator.java:164)
       at android.view.animation.PathInterpolator.(PathInterpolator.java)
       at android.support.v4.view.animation.PathInterpolatorCompat.create(PathInterpolatorCompat.java:49)
       at me.zhanghai.android.materialprogressbar.Interpolators$TRIM_PATH_END.(Interpolators.java)
       at me.zhanghai.android.materialprogressbar.Animators.createIndeterminate(Animators.java:149)
       at me.zhanghai.android.materialprogressbar.IndeterminateProgressDrawable.(IndeterminateProgressDrawable.java)
       at com.afollestad.materialdialogs.DialogInit.setupProgressDialog(DialogInit.java:369)
       at com.afollestad.materialdialogs.DialogInit.init(DialogInit.java:297)
       at com.afollestad.materialdialogs.MaterialDialog.(MaterialDialog.java)
       at com.afollestad.materialdialogs.MaterialDialog$Builder.build(MaterialDialog.java:1335)
       at ---Activity.showProgressDialog(---Activity.java:213)
       at ---Activity.onOptionsItemSelected(---Activity.java:151)
       at android.app.Activity.onMenuItemSelected(Activity.java:2918)
       at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:361)
       at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
       at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
       at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
       at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:65)
       at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:202)
       at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:780)
       at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
       at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:171)
       at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:973)
       at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:963)
       at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:624)
       at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:150)
       at android.view.View.performClick(View.java:5207)
       at android.view.View$PerformClick.run(View.java:21168)
       at android.os.Handler.handleCallback(Handler.java:746)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5443)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)`

My java code:
```java
        progressDialog = new MaterialDialog.Builder(this)
                .theme(Theme.LIGHT)
                .content(R.string.in_progress)
                .progress(true, 0)
                .cancelable(false)
                .keyListener(new DialogInterface.OnKeyListener() {
                    @Override
                    public boolean onKey(DialogInterface dialog, int keyCode, KeyEvent event) {
                        if (keyCode == KeyEvent.KEYCODE_BACK) {
                            if (event.getAction() == KeyEvent.ACTION_UP) {
                                //some code
                            }
                            return true;
                        }
                        return false;
                    }
                })
                .build();
        progressDialog.show();
```

**Comment by afollestad** [comment]
I think you'd need to report this to https://github.com/DreaminginCodeZH/MaterialProgressBar.
