### ISSUE TITLE
NoSuchMethodError: No static method MDTintHelper

### ISSUE THREAD

**Issue by AyupovIlgam** [afollestad/material-dialogs#1515]
I'v seen strange issue in my bug tracker, could U please take a look?
Device : Huawei P8 Lite
OS: 5.0.1100

Fatal Exception: java.lang.NoSuchMethodError: No static method printStackTrace(Ljava/lang/Throwable;)V in class Lcom/google/devtools/build/android/desugar/runtime/ThrowableExtension; or its super classes (declaration of 'com.google.devtools.build.android.desugar.runtime.ThrowableExtension' appears in /data/app/com.google.android.apps.mtaas.crawler-1/base.apk)
       at com.afollestad.materialdialogs.internal.MDTintHelper.setCursorTint(MDTintHelper.java:193)
       at com.afollestad.materialdialogs.internal.MDTintHelper.setTint(MDTintHelper.java:171)
       at com.afollestad.materialdialogs.DialogInit.setupInputDialog(DialogInit.java:527)
       at com.afollestad.materialdialogs.DialogInit.init(DialogInit.java:346)
       at com.afollestad.materialdialogs.MaterialDialog.<init>(MaterialDialog.java:92)
       at com.afollestad.materialdialogs.MaterialDialog$Builder.build(MaterialDialog.java:2183)
       at kz.rahmet.app.presenters.activities.auth.ActivitySignIn.onForgotPasswordClick(ActivitySignIn.java:113)
       at kz.rahmet.app.presenters.activities.auth.ActivitySignIn_ViewBinding$4.doClick(ActivitySignIn_ViewBinding.java:77)
       at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
       at android.view.View.performClick(View.java:4766)
       at android.view.View$PerformClick.run(View.java:19683)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.support.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:148)
       at android.support.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:465)
       at android.support.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:421)
       at android.support.test.espresso.base.UiControllerImpl.injectMotionEvent(UiControllerImpl.java:235)
       at android.support.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:140)
       at android.support.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:123)
       at android.support.test.espresso.action.Tap.sendSingleTap(Tap.java:170)
       at android.support.test.espresso.action.Tap.access$100(Tap.java:31)
       at android.support.test.espresso.action.Tap$1.sendTap(Tap.java:47)
       at android.support.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:136)
       at android.support.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:355)
       at android.support.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:242)
       at android.support.test.espresso.ViewInteraction.access$100(ViewInteraction.java:62)
       at android.support.test.espresso.ViewInteraction$1.call(ViewInteraction.java:149)
       at android.support.test.espresso.ViewInteraction$1.call(ViewInteraction.java:146)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5538)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by afollestad** [comment]
It sounds like your Proguard is removing the static method, or something.
