### ISSUE TITLE
MDTintHelper prints exception, which does not affect anything..

### ISSUE THREAD

**Issue by devjta** [afollestad/material-dialogs#1539]
Hi!

It is still there with the latest version of your AMAZING library, that the MDTintHelper prints its exception stacktrace..
Could it be mutable?

Also I dont get it, why your example doesnt throw an exception.
My stacktrace:
`W/ResourceType: No package identifier when getting value for resource number 0x00000000
W/System.err: android.content.res.Resources$NotFoundException: Resource ID #0x0
W/System.err:     at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:224)
W/System.err:     at android.content.res.Resources.getDrawableForDensity(Resources.java:876)
W/System.err:     at android.content.res.Resources.getDrawable(Resources.java:819)
W/System.err:     at android.content.Context.getDrawable(Context.java:605)
W/System.err:     at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:351)
W/System.err:     at com.afollestad.materialdialogs.internal.MDTintHelper.setCursorTint(MDTintHelper.java:152)
W/System.err:     at com.afollestad.materialdialogs.internal.MDTintHelper.setTint(MDTintHelper.java:119)
`

**Comment by devjta** [comment]
Stacktrace with newest version:

`04-04 18:29:25.002 21293-21293/com.defectradar.dev2 W/ResourceType: No package identifier when getting value for resource number 0x00000000
04-04 18:29:25.003 21293-21293/com.defectradar.dev2 W/System.err: android.content.res.Resources$NotFoundException: Resource ID #0x0
        at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:224)
        at android.content.res.Resources.getDrawableForDensity(Resources.java:876)
        at android.content.res.Resources.getDrawable(Resources.java:819)
        at android.content.Context.getDrawable(Context.java:605)
04-04 18:29:25.004 21293-21293/com.defectradar.dev2 W/System.err:     at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:351)
        at com.afollestad.materialdialogs.internal.MDTintHelper.setCursorTint(MDTintHelper.java:186)
        at com.afollestad.materialdialogs.internal.MDTintHelper.setTint(MDTintHelper.java:171)
        at com.afollestad.materialdialogs.DialogInit.setupInputDialog(DialogInit.java:527)
        at com.afollestad.materialdialogs.DialogInit.init(DialogInit.java:346)
        at com.afollestad.materialdialogs.MaterialDialog.<init>(MaterialDialog.java:92)
        at com.afollestad.materialdialogs.MaterialDialog$Builder.build(MaterialDialog.java:2183)
        at com.afollestad.materialdialogs.MaterialDialog$Builder.show(MaterialDialog.java:2188)
`

**Comment by afollestad** [comment]
Will no longer apply with upcoming version 2.0, this class is going away
