### ISSUE TITLE
PreferenceFragmentCompat show ColorPicker Error

### ISSUE THREAD

**Issue by tcqq** [afollestad/material-dialogs#1543]
@askfor I added the palette code in `PreferenceFragmentCompat` and I implemented `ColorChooserDialog.ColorCallback` but have error. What did I do wrong? How should I correct it is right?

### Code: 
```
public class ThemeSettingsFragment extends PreferenceFragmentCompat implements Preference.OnPreferenceClickListener, ColorChooserDialog.ColorCallback{

    private int mPrimaryPreselect;

    @Override
    protected int getPrefLayoutId() {
        return R.xml.preference_theme;
    }

    @Override
    protected void startUi(Bundle state) {
        super.startUi(state);
        initializePreference();
    }

    private void initializePreference() {
        ColorPickerPreference colorPickerPrefPrimaryColor = (ColorPickerPreference) getPreferenceManager().findPreference("color_picker_pref_primary_color");

        colorPickerPrefPrimaryColor.setOnPreferenceClickListener(this);
    }

    @Override
    public boolean onPreferenceClick(Preference preference) {
        switch (preference.getKey()) {
            case "color_picker_pref_primary_color":
                new ColorChooserDialog.Builder(getActivity(), R.string.theme_settings_select_a_color)
                        .titleSub(R.string.theme_settings_select_a_color)
                        .preselect(mPrimaryPreselect)
                        .show(getActivity());
                break;
        }
        return super.onPreferenceClick(preference);
    }

    @Override
    public void onColorSelection(@NonNull ColorChooserDialog dialog, int selectedColor) {
        if (dialog.isAccentMode()) {
        } else {
            mPrimaryPreselect = selectedColor;
        }
    }

    @Override
    public void onColorChooserDismissed(@NonNull ColorChooserDialog dialog) {

    }
```

### Error:

```
    java.lang.IllegalStateException: ColorChooserDialog needs to be shown from an Activity/Fragment implementing ColorCallback.
        at com.afollestad.materialdialogs.color.ColorChooserDialog.onAttach(ColorChooserDialog.java:118)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1372)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by afollestad** [comment]
Will no longer apply with upcoming version 2.0
