### ISSUE TITLE
use version：2.0.0-beta2 display error， but use vesion：0.9.5.0，no problem

### ISSUE THREAD

**Issue by gyb3320** [afollestad/material-dialogs#1637]
step1： implementation 'com.afollestad.material-dialogs:core:2.0.0-beta2'

step2：rebuild
display error：
Caused by: com.android.builder.internal.aapt.v2.Aapt2Exception: AAPT2 error: check logs for details
	at com.android.builder.png.AaptProcess$NotifierProcessOutput.handleOutput(AaptProcess.java:443)
	at com.android.builder.png.AaptProcess$NotifierProcessOutput.err(AaptProcess.java:395)
	at com.android.builder.png.AaptProcess$ProcessOutputFacade.err(AaptProcess.java:312)
	at com.android.utils.GrabProcessOutput$1.run(GrabProcessOutput.java:104) 

but，implementation 'com.afollestad.material-dialogs:core:0.9.5.0'
rebuild success

i want use lasters version，How to Solve？

**Comment by afollestad** [comment]
Well first of all, the latest of 2.0 is beta3. The latest of 0.9 is 0.9.6.0. 

The problem listed above is not a problem with the library - you probably need to update Android Studio and your Gradle plugin.
