### ISSUE TITLE
IllegalStateException with customdialog

### ISSUE THREAD

**Issue by dri94** [afollestad/material-dialogs#1717]
*Please consider making a Pull Request if you are capable of doing so.*

**Library Version:**

2.0.0-rc10
 
**Affected Device(s):**
 
Google Pixel 3 XL with Android 9.0
 
**Describe the Bug:**

I use a custom dialog in my PreferenceFragment. After updating the library I am getting crashes in production with the error. This only happens for me with this customDialog. Other dialogs in the fragment behave correctly.
```
Fatal Exception: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
       at android.view.ViewGroup.addViewInner(ViewGroup.java:5161)
       at android.view.ViewGroup.addView(ViewGroup.java:4991)
       at android.view.ViewGroup.addView(ViewGroup.java:4931)
       at android.view.ViewGroup.addView(ViewGroup.java:4904)
       at com.afollestad.materialdialogs.internal.main.DialogContentLayout.addCustomView(DialogContentLayout.kt:103)
       at com.afollestad.materialdialogs.customview.DialogCustomViewExtKt.customView(DialogCustomViewExt.kt:38)
       at com.afollestad.materialdialogs.customview.DialogCustomViewExtKt.customView$default(DialogCustomViewExt.kt:34)
       at com.expapp.atlas.account.UserSettingsFragment$setupUserCreditCard$3.onPreferenceClick(UserSettingsFragment.kt:159)
       at androidx.preference.Preference.performClick(Preference.java:1165)
       at androidx.preference.Preference.performClick(Preference.java:1148)
       at androidx.preference.Preference$1.onClick(Preference.java:172)
       at android.view.View.performClick(View.java:6930)
       at android.view.View$PerformClick.run(View.java:26211)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6958)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
```

**To Reproduce:**
1. Create a custom dialog in a fragment
2. show it when a user clicks on a preference
3. reload the fragment
4. observe random crash

Dialog
```
val builder = MaterialDialog(this)
builder.title(text = getString(R.string.update_credit_card_dialog_title))
builder.positiveButton(text = getString(R.string.update_credit_card_positive_text), click ={})
builder.customView(view = view, scrollable = true)
.negativeButton(R.string.nevermind)
.show()
```

**Expected Behavior:**
Custom dialog to display

**Comment by afollestad** [comment]
Will take a look when I get a chance. FYI, you can cleanup your declaration a lot:

```kotlin
MaterialDialog(this).show {
    title(R.string.update_credit_card_dialog_title)
    positiveButton(R.string.update_credit_card_positive_text) { }
    customView(view = view, scrollable = true)
    negativeButton(R.string.nevermind)
}
```

You don't need `text = getString()` or `onClick=`

**Comment by afollestad** [comment]
@dri94 this isn't an issue with this library actually - you're passing `view` from your own code which has already been adding to another parent. You need to remove it. 

Although, I can add a workaround in the library which removes it from the internal parent when the dialog is done with it.
