### ISSUE TITLE
3.0.0 in Java, how to create basic dialog?

### ISSUE THREAD

**Issue by Obsttube** [afollestad/material-dialogs#1812]
Hello, I am trying to use this library in Java, I have read this is not pleasant with 3.0.0, but I can't even display the basic Dialog!
I tried

`
MaterialDialog md=new MaterialDialog(this, new DialogBehavior() {
            @Override
            public int getThemeRes(boolean b) {
                return 0;
            }

            @Override
            public ViewGroup createView(Context context, Window window, LayoutInflater layoutInflater, MaterialDialog materialDialog) {
                return null;
            }

            @Override
            public DialogLayout getDialogLayout(ViewGroup viewGroup) {
                return null;
            }

            @Override
            public void setWindowConstraints(Context context, Window window, DialogLayout dialogLayout, Integer integer) {

            }

            @Override
            public void setBackgroundColor(Context context, Window window, DialogLayout dialogLayout, int i, float v) {

            }

            @Override
            public void onPreShow(MaterialDialog materialDialog) {

            }

            @Override
            public void onPostShow(MaterialDialog materialDialog) {

            }

            @Override
            public boolean onDismiss() {
                return false;
            }
        });
        md.show();`

but it gives me

`Caused by: java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup
        at android.view.ViewGroup.addView(ViewGroup.java:4250)
        at android.view.ViewGroup.addView(ViewGroup.java:4230)
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:443)
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:424)
        at android.app.Dialog.setContentView(Dialog.java:523)
        at com.afollestad.materialdialogs.MaterialDialog.<init>(MaterialDialog.kt:108)
        at (MY PACKAGE).MainActivity.onCreate(MainActivity.java:54)
        at android.app.Activity.performCreate(Activity.java:6679)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6119) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) `

It is probably because I return null in new DialogBehavior() {...}
Can you tell me what is the default behavior? I don't really want to create my own behavior. I can't pass null instead off DialogBehavior() cause it is @NonNull
So MaterialDialog md=new MaterialDialog(this, null); won't work.
It seams like in Kotlin there is only context required, but weirdly in java I have to pass context and DialogBehavior. What should I pass as second argument if I want the default behavior?

**Comment by Obsttube** [comment]
I can't use MaterialDialog md=new MaterialDialog(this, new ModalDialog()); either, because ModalDialog is private

**Comment by afollestad** [comment]
It's not intended to be used from Java.

**Comment by afollestad** [comment]
ModalDialog is a Kotlin `object` Singleton, it can't be constructed.
