### ISSUE TITLE
Bottom Sheets: WindowManager: android.view.WindowLeaked

### ISSUE THREAD

**Issue by dkrivoruchko** [afollestad/material-dialogs#1825]
**Library Version:**
3.0.2
 
**Describe the Bug:**
WindowManager: android.view.WindowLeaked

**To Reproduce:**
MaterialDialog(this, BottomSheet())
Open BottomSheetDialog, rotate device.

```
WindowManager: android.view.WindowLeaked: Activity ...AppActivity has leaked window com.android.internal.policy.PhoneWindow$DecorView{910b88f V.ED..... R....... 0,0-1080,1920} that was originally added here
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:368)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:299)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
        at android.app.Dialog.show(Dialog.java:319)
        at com.afollestad.materialdialogs.MaterialDialog.show(MaterialDialog.kt:368)
```

**Comment by afollestad** [comment]
This can be true for any dialog. You need to dismiss dialogs when your Activity is pausing or being destroyed. The lifecycle module if this library can help automate that.

**Comment by dkrivoruchko** [comment]
It's already in code and it crash with it.
```
MaterialDialog(this, BottomSheet()).show{
lifecycleOwner(viewLifecycleOwner)
}
```
If remove BottomSheet() - all is ok

**Comment by lucazin** [comment]
Java Version ?

**Comment by afollestad** [comment]
This is reproducible _without_ bottom sheets as well.

**Comment by dkrivoruchko** [comment]
[BottomSheet.onDismiss](https://github.com/afollestad/material-dialogs/blob/20d5dfd16404af0a6fcdf662bd54a63a4e4826e0/bottomsheets/src/main/java/com/afollestad/materialdialogs/bottomsheets/BottomSheet.kt#L226) should always return true or by itself call ` hideKeyboard();  super.dismiss()` from [MatedialDialog.dismiss](https://github.com/afollestad/material-dialogs/blob/20d5dfd16404af0a6fcdf662bd54a63a4e4826e0/core/src/main/java/com/afollestad/materialdialogs/MaterialDialog.kt#L413)
Currently BottomSheet does not call Dialog,dismiss() and that lead to WindowLeaked

**Comment by jmhabuild** [comment]
Solution.
1. Make a subclass inherited from MaterialDialog and LifecycleObserver interface.
2. Dismiss the subclass instance at the device orientation change, using like @OnLifecycleEvent(Lifecycle.Event.ON_STOP) annotation on the dismiss function, so that it is called at onPause() or onStop() from underlying fragment or activity which is Lifecycle Owner.

**Comment by afollestad** [comment]
There is already a lifecycle extension for this library that does that.

**Comment by dkrivoruchko** [comment]
@afollestad Any reason why my proposal is not implemented yet?

**Comment by afollestad** [comment]
Time.
