### ISSUE TITLE
After adding the library to my gradle configuration, appears a lot of errors and cannot compile.

### ISSUE THREAD

**Issue by forlayo** [afollestad/material-dialogs#184]
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/home/mike/android-sdk-linux/build-tools/21.1.2/aapt package -f --no-crunch -I /home/mike/android-sdk-linux/platforms/android-21/android.jar -M /home/mike/workspace/Android/build/intermediates/manifests/full/debug/AndroidManifest.xml -S /home/mike/workspace/Android/build/intermediates/res/debug -A /home/mike/workspace/Android/build/intermediates/assets/debug -m -J /home/mike/workspace/Android/build/generated/source/r/debug -F /home/mike/workspace/Android/build/intermediates/res/resources-debug.ap_ --debug-mode --custom-package com.yuilop -0 apk --output-text-symbols /home/mike/workspace/Android/build/intermediates/symbols/debug
  Error Code:
  	1
  Output:
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:400: error: Attribute "titleTextStyle" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:400: error: Attribute "subtitleTextStyle" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:400: error: Attribute "divider" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:400: error: Attribute "background" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:400: error: Attribute "backgroundSplit" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:425: error: Attribute "navigationMode" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:425: error: Attribute "displayOptions" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:425: error: Attribute "title" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:425: error: Attribute "subtitle" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:425: error: Attribute "icon" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:425: error: Attribute "logo" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:425: error: Attribute "backgroundStacked" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:425: error: Attribute "customNavigationLayout" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:425: error: Attribute "homeLayout" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:425: error: Attribute "progressBarStyle" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:425: error: Attribute "indeterminateProgressStyle" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:425: error: Attribute "progressBarPadding" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:425: error: Attribute "itemPadding" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:428: error: Attribute "initialActivityCount" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:428: error: Attribute "expandActivityOverflowButtonDrawable" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:431: error: Attribute "preserveIconSpacing" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:432: error: Attribute "iconifiedByDefault" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:432: error: Attribute "queryHint" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:442: error: Attribute "windowActionBar" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:442: error: Attribute "windowActionBarOverlay" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:442: error: Attribute "windowActionModeOverlay" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:442: error: Attribute "actionBarTabStyle" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:442: error: Attribute "actionBarTabBarStyle" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:442: error: Attribute "actionBarTabTextStyle" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:442: error: Attribute "actionOverflowButtonStyle" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:442: error: Attribute "actionBarStyle" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:442: error: Attribute "actionBarSplitStyle" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:442: error: Attribute "actionBarWidgetTheme" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:442: error: Attribute "actionBarSize" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:442: error: Attribute "actionBarDivider" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:442: error: Attribute "actionBarItemBackground" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:442: error: Attribute "actionMenuTextAppearance" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:442: error: Attribute "actionMenuTextColor" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:442: error: Attribute "actionModeStyle" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:442: error: Attribute "actionModeCloseButtonStyle" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:442: error: Attribute "actionModeBackground" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:442: error: Attribute "actionModeSplitBackground" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:442: error: Attribute "actionModeCloseDrawable" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:442: error: Attribute "actionModeShareDrawable" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:442: error: Attribute "actionModePopupWindowStyle" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:442: error: Attribute "textAppearanceLargePopupMenu" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:442: error: Attribute "textAppearanceSmallPopupMenu" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:442: error: Attribute "actionDropDownStyle" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:442: error: Attribute "dropdownListPreferredItemHeight" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:442: error: Attribute "spinnerDropDownItemStyle" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:442: error: Attribute "homeAsUpIndicator" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:442: error: Attribute "actionButtonStyle" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:442: error: Attribute "selectableItemBackground" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:442: error: Attribute "dividerVertical" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:442: error: Attribute "activityChooserViewStyle" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:442: error: Attribute "popupMenuStyle" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:442: error: Attribute "textAppearanceSearchResultTitle" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:442: error: Attribute "textAppearanceSearchResultSubtitle" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:442: error: Attribute "textColorSearchUrl" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:442: error: Attribute "listPreferredItemHeightSmall" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:442: error: Attribute "listPreferredItemPaddingLeft" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:442: error: Attribute "listPreferredItemPaddingRight" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:442: error: Attribute "dropDownListViewStyle" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:442: error: Attribute "listPopupWindowStyle" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:442: error: Attribute "textAppearanceListItemSmall" has already been defined
  	
  	/home/mike/workspace/Android/build/intermediates/res/debug/values/values.xml:460: error: Attribute "textAllCaps" has already been defined
```

**Comment by forlayo** [comment]
Apparently is because I'm using ActionbarSherlock and your library is using appcompat-v7, someone knows any workaround ? right now I cannot replace actionbarsherlock..

**Comment by msmozafari** [comment]
Hi @forlayo ,
You must exclude appcompat-v7 from material-dialog:
compile ("com.afollestad:material-dialogs:0.6.0"){
        exclude group: 'com.google.android', module: 'appcompat-v7'
    }

**Comment by forlayo** [comment]
Hi @msmozafari ,

First of all thanks a lot for your support and also for your incredible work with this library, well I've tried to do it in the way that you point, everything works and now compile correctly but when I try to launch a dialog, I got a new crash:
```
01-13 18:18:32.799    3484-3484/com.yuilop E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.yuilop, PID: 3484
    java.lang.NoSuchFieldError: com.afollestad.materialdialogs.R$attr.colorAccent
            at com.afollestad.materialdialogs.MaterialDialog$Builder.<init>(MaterialDialog.java:898)
            at com.yuilop.registering.signup.SignUpProcess.onCreate(SignUpProcess.java:251)
            at android.app.Activity.performCreate(Activity.java:5451)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2452)
            at android.app.ActivityThread.access$900(ActivityThread.java:172)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1302)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5586)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
            at dalvik.system.NativeStart.main(Native Method)
```

Code used to launch the dialog is the one from example:

```
        new MaterialDialog.Builder(this)
                .title("Use Google's Location Services?")
                .content("Let Google help apps determine location. This means sending anonymous location data to Google, even when no apps are running.")
                .positiveText("Agree")
                .negativeText("Disagree")
                .show();
```

**Comment by afollestad** [comment]
@forlayo what? He didn't make this library

**Comment by afollestad** [comment]
@forlayo what he mentioned should work. But why are you using ActionBarSherlock? AppCompat is a much newer and better replacement that uses Material design.

**Comment by msmozafari** [comment]
@forlayo , I didn't make this library. This incredible library created by @afollestad.

**Comment by forlayo** [comment]
@msmozafari, @afollestad Sorry about the "little" confusion haha.

@afollestad I'm using ActionBarSherlock because I'm working in a company project that has few years.. and at this mommnet I cannot switch to AppCompat one..

There's not any workarount to be able to use your library ?
