### ISSUE TITLE
NPE when using maxDate on datePicker without selecting date

### ISSUE THREAD

**Issue by MenilV** [afollestad/material-dialogs#1863]
**Library Version:**

3.1.0
 
**Affected Device(s):**
 
Samsung Galaxy S8 with Android 9.0 and every other device tested on
 
**Describe the Bug:**

When invoking a MaterialDialog with date selection, if the config has `maxDate` set, the dialog crashes if the user didn't select any date before hitting the positive button.

**To Reproduce:**
1. ` MaterialDialog(context).show{
datePicker(currentDate = startDate, maxDate = endDate, dateCallback = listener)}`
2.  User selects date greater than max date
3.  User presses positive button

``` kotlin.KotlinNullPointerException
        at com.afollestad.materialdialogs.datetime.DatePickerExtKt$datePicker$2.invoke(DatePickerExt.kt:64)
        at com.afollestad.materialdialogs.datetime.DatePickerExtKt$datePicker$2.invoke(Unknown Source:2)
        at com.afollestad.materialdialogs.callbacks.DialogCallbackExtKt.invokeAll(DialogCallbackExt.kt:68)
        at com.afollestad.materialdialogs.MaterialDialog.onActionButtonClicked$com_afollestad_material_dialogs_core(MaterialDialog.kt:403)
        at com.afollestad.materialdialogs.internal.button.DialogActionButtonLayout$onFinishInflate$1.onClick(DialogActionButtonLayout.kt:84)
        at android.view.View.performClick(View.java:7352)
        at android.widget.TextView.performClick(TextView.java:14177)
        at android.view.View.performClickInternal(View.java:7318)
        at android.view.View.access$3200(View.java:846)
        at android.view.View$PerformClick.run(View.java:27800)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

**Expected Behavior:**
 The dialog should not crash at least

**Comment by VMadalin** [comment]
@MenilV Thanks for the detailed issue, I reproduce it. It's important to remark that only happens when you set-up the `dateCallback` param. 

In my case I reproduced it by setting an incoherent dates: 
- currentDate(26/1/2000)
- endDate(25/1/2000)

As you see the `currentDate` is later than `endDate`, this create an internal error of library when forcing the date by `dateCallback?.invoke(it, getDatePicker().getDate()!!)`. By default if the dates are correct the calendar select the `currentDate` and is imposible to unselected it. But in the oposite case don't select any date making and this behaviour is unexpected. 

Please check your dates, before care the dialog. However it's a good practice to add a specific check for avoid this case
