### ISSUE TITLE
Crashing with app bundle

### ISSUE THREAD

**Issue by h4h13** [afollestad/material-dialogs#1878]
*Please consider making a Pull Request if you are capable of doing so.*

**Library Version:**

3.0.0-alpha1
 
**Affected Device(s):**
 
LG V20 with Android 7.0, POCO F1 Android 9.0
 
**Describe the Bug:**

When you publish an app with the app-bundle feature it's crashing for some devices

**Comment by afollestad** [comment]
I've never experienced this sort of issue in any production apps. This issue needs more information, e.g. crash stacktraces.

**Comment by hemanthStack** [comment]
**Crash Report:**
 
<<< log_count = 74 >>>
[09-09 20:06:14.317 3730:3730 I/Timeline]
Timeline: Activity_launch_request id:code.name.monkey.retromusic time:422709

[09-09 20:06:14.319 1659:3480 I/ActivityManager]
START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=code.name.monkey.retromusic/.activities.MainActivity bnds=[576,82][864,417] (has extras)} from uid 10404 on display 0

[09-09 20:06:14.338 1659:3480 D/ActivityManager]
setTaskToReturnTo : TaskRecord{d2db495 #2615 A=code.name.monkey.retromusic U=0 StackId=1 sz=0} / mTaskToReturnTo = 1

[09-09 20:06:14.338 1659:3480 D/ActivityManager]
setTaskToReturnTo : TaskRecord{d2db495 #2615 A=code.name.monkey.retromusic U=0 StackId=1 sz=0} / mTaskToReturnTo = 1

[09-09 20:06:14.338 1659:3480 D/ActivityManager]
setTaskToReturnTo : TaskRecord{d2db495 #2615 A=code.name.monkey.retromusic U=0 StackId=1 sz=0} / mTaskToReturnTo = 1

[09-09 20:06:14.339 1659:3480 D/ActivityManager]
setTaskToReturnTo : TaskRecord{d2db495 #2615 A=code.name.monkey.retromusic U=0 StackId=1 sz=1} / mTaskToReturnTo = 1

[09-09 20:06:14.339 2692:2729 D/LGImageQualityEnhancementService]
activityStarting: code.name.monkey.retromusic/code.name.monkey.retromusic.activities.MainActivity

[09-09 20:06:14.383 2692:5641 D/LGImageQualityEnhancementService]
activityResuming: code.name.monkey.retromusic/code.name.monkey.retromusic.activities.MainActivity

[09-09 20:06:14.397 1659:2607 I/ActivityManager]
Start proc 21614:code.name.monkey.retromusic/u0a324 for activity code.name.monkey.retromusic/.activities.MainActivity

[09-09 20:06:14.484 21614:21614 W/System]
ClassLoader referenced unknown path: /data/app/code.name.monkey.retromusic-1/lib/arm64

[09-09 20:06:14.702 21614:21614 I/art]
  at android.view.View code.name.monkey.retromusic.activities.base.AbsSlidingMusicPanelActivity.wrapSlidingMusicPanel(int) ((null):-1)

[09-09 20:06:14.702 21614:21614 I/art]
  at android.view.View code.name.monkey.retromusic.activities.MainActivity.createContentView() ((null):-1)

[09-09 20:06:14.702 21614:21614 I/art]
  at void code.name.monkey.retromusic.activities.base.AbsSlidingMusicPanelActivity.onCreate(android.os.Bundle) ((null):-1)

[09-09 20:06:14.702 21614:21614 I/art]
  at void code.name.monkey.retromusic.activities.MainActivity.onCreate(android.os.Bundle) ((null):-1)

[09-09 20:06:14.702 21614:21614 I/art]
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/code.name.monkey.retromusic-1/base.apk", zip file "/data/app/code.name.monkey.retromusic-1/split_config.en.apk", zip file "/data/app/code.name.monkey.retromusic-1/split_config.xxxhdpi.apk"],nativeLibraryDirectories=[/data/app/code.name.monkey.retromusic-1/lib/arm64, /system/lib64, /vendor/lib64]]

[09-09 20:06:14.703 21614:21614 I/art]
  at android.view.View code.name.monkey.retromusic.activities.base.AbsSlidingMusicPanelActivity.wrapSlidingMusicPanel(int) ((null):-1)

[09-09 20:06:14.703 21614:21614 I/art]
  at android.view.View code.name.monkey.retromusic.activities.MainActivity.createContentView() ((null):-1)

[09-09 20:06:14.703 21614:21614 I/art]
  at void code.name.monkey.retromusic.activities.base.AbsSlidingMusicPanelActivity.onCreate(android.os.Bundle) ((null):-1)

[09-09 20:06:14.703 21614:21614 I/art]
  at void code.name.monkey.retromusic.activities.MainActivity.onCreate(android.os.Bundle) ((null):-1)

[09-09 20:06:14.858 21614:21614 I/Timeline]
Timeline: Activity_launch_request id:code.name.monkey.retromusic time:423250

[09-09 20:06:14.858 1659:2734 I/ActivityManager]
START u0 {cmp=code.name.monkey.retromusic/.activities.WhatsNewActivity} from uid 10324 on display 0

[09-09 20:06:14.864 2692:2729 D/LGImageQualityEnhancementService]
activityStarting: code.name.monkey.retromusic/code.name.monkey.retromusic.activities.WhatsNewActivity

[09-09 20:06:15.156 6593:6798 I/Finsky]
[186] fpk.d(24): code.name.monkey.retromusic: Account determined from installer data - [w-7FUscgtc3px3kwAKwlJpvcIJ0]

[09-09 20:06:15.157 6593:6798 I/Finsky]
[186] fpk.d(20): code.name.monkey.retromusic: Account from preferred account - [w-7FUscgtc3px3kwAKwlJpvcIJ0]

[09-09 20:06:15.191 6593:6604 I/Finsky]
[137] fpk.d(24): code.name.monkey.retromusic: Account determined from installer data - [w-7FUscgtc3px3kwAKwlJpvcIJ0]

[09-09 20:06:15.224 6593:6604 I/Finsky]
[137] fpk.d(20): code.name.monkey.retromusic: Account from preferred account - [w-7FUscgtc3px3kwAKwlJpvcIJ0]

[09-09 20:06:15.234 2907:3413 V/Avrcp]
[BTUI] onActiveSessionsChanged: pkgName[0]: code.name.monkey.retromusic

[09-09 20:06:15.235 3439:3439 I/MusicController]
[MusicControllerMediaSessionManager.java:73:updateMediaController()] oooooo MediaController recived packageName code.name.monkey.retromusic

[09-09 20:06:15.287 3803:3803 W/PackageManager]
Failure retrieving resources for code.name.monkey.retromusic: Resource ID #0x7f0f0000

[09-09 20:06:15.793 21614:21614 E/chromium]
[ERROR:filesystem_posix.cc(89)] stat /data/user/0/code.name.monkey.retromusic/cache/WebView/Crashpad: No such file or directory (2)

[09-09 20:06:15.794 21614:21614 E/chromium]
[ERROR:filesystem_posix.cc(62)] mkdir /data/user/0/code.name.monkey.retromusic/cache/WebView/Crashpad: No such file or directory (2)

[09-09 20:06:16.640 1659:1883 I/ActivityManager]
Displayed code.name.monkey.retromusic/.activities.WhatsNewActivity: +1s328ms

[09-09 20:06:16.654 1659:1883 V/WindowManager]
Not removing Window{1ead113 u0 Starting code.name.monkey.retromusic EXITING} due to exit animation 

[09-09 20:06:16.671 1659:1883 D/InputDispatcher]
Window went away: Window{1ead113 u0 Starting code.name.monkey.retromusic}

[09-09 20:06:16.772 1659:1883 I/WindowManager]
Destroying surface Surface(name=Starting code.name.monkey.retromusic) called by com.android.server.wm.WindowStateAnimator.destroySurface:2177 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:960 com.android.server.wm.WindowState.destroyOrSaveSurface:2151 com.android.server.wm.AppWindowToken.destroySurfaces:381 com.android.server.wm.WindowStateAnimator.finishExit:593 com.android.server.wm.WindowStateAnimator.stepAnimationLocked:519 com.android.server.wm.WindowAnimator.updateWindowsLocked:323 com.android.server.wm.WindowAnimator.animateLocked:739 

[09-09 20:06:17.671 2692:18166 D/LGImageQualityEnhancementService]
activityResuming: code.name.monkey.retromusic/code.name.monkey.retromusic.activities.WhatsNewActivity

[09-09 20:06:17.731 1659:3216 D/InputDispatcher]
Focus entered window: Window{6cd796c u0 code.name.monkey.retromusic/code.name.monkey.retromusic.activities.WhatsNewActivity}

[09-09 20:06:19.124 1659:1883 W/AppOps]
Finishing op nesting under-run: uid 10324 pkg code.name.monkey.retromusic code 45 time=0 duration=0 nesting=0

[09-09 20:06:24.434 1659:2255 D/InputTransport]
channel '6cd796c code.name.monkey.retromusic/code.name.monkey.retromusic.activities.WhatsNewActivity (server)' : action=ACTION_DOWN(0), id=0, tooltype=1, deviceId=3, source=0x1002, flags=0x1, edgeFlags=0x0, metaState=0x0, buttonState=0x0, downTime=432825870000, eventTime=432825870000, pointerCount=1

[09-09 20:06:24.508 1659:2255 D/InputTransport]
channel '6cd796c code.name.monkey.retromusic/code.name.monkey.retromusic.activities.WhatsNewActivity (server)' : action=ACTION_UP(0), id=0, tooltype=1, deviceId=3, source=0x1002, flags=0x1, edgeFlags=0x0, metaState=0x0, buttonState=0x0, downTime=432825870000, eventTime=432900185000, pointerCount=1

[09-09 20:06:24.534 2692:5641 D/LGImageQualityEnhancementService]
activityResuming: code.name.monkey.retromusic/code.name.monkey.retromusic.activities.MainActivity

[09-09 20:06:24.670 1659:3562 D/InputDispatcher]
Focus left window: Window{6cd796c u0 code.name.monkey.retromusic/code.name.monkey.retromusic.activities.WhatsNewActivity}

[09-09 20:06:24.670 1659:3562 D/InputDispatcher]
Focus entered window: Window{4864001 u0 code.name.monkey.retromusic/code.name.monkey.retromusic.activities.MainActivity}

[09-09 20:06:24.980 1659:1883 I/ActivityManager]
Displayed code.name.monkey.retromusic/.activities.MainActivity: +446ms (total +7s308ms)

[09-09 20:06:25.295 1659:3479 I/WindowManager]
Destroying surface Surface(name=code.name.monkey.retromusic/code.name.monkey.retromusic.activities.WhatsNewActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2177 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:960 com.android.server.wm.WindowState.destroyOrSaveSurface:2151 com.android.server.wm.WindowManagerService.tryStartExitingAnimation:3456 com.android.server.wm.WindowManagerService.relayoutWindow:3321 com.android.server.wm.WindowManagerServiceEx.relayoutWindow:520 com.android.server.wm.Session.relayout:216 android.view.IWindowSession$Stub.onTransact:286 

[09-09 20:06:25.930 1659:3560 D/InputDispatcher]
Window went away: Window{6cd796c u0 code.name.monkey.retromusic/code.name.monkey.retromusic.activities.WhatsNewActivity}

[09-09 20:06:26.020 1659:2255 D/InputTransport]
channel '4864001 code.name.monkey.retromusic/code.name.monkey.retromusic.activities.MainActivity (server)' : action=ACTION_DOWN(0), id=0, tooltype=1, deviceId=3, source=0x1002, flags=0x1, edgeFlags=0x0, metaState=0x0, buttonState=0x0, downTime=434412105000, eventTime=434412105000, pointerCount=1

[09-09 20:06:26.061 1659:2255 D/InputTransport]
channel '4864001 code.name.monkey.retromusic/code.name.monkey.retromusic.activities.MainActivity (server)' : action=ACTION_UP(0), id=0, tooltype=1, deviceId=3, source=0x1002, flags=0x1, edgeFlags=0x0, metaState=0x0, buttonState=0x0, downTime=434412105000, eventTime=434453468000, pointerCount=1

[09-09 20:06:26.174 21614:21614 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: code.name.monkey.retromusic, PID: 21614
android.content.res.Resources$NotFoundException: Resource ID #0x7f0f0003
	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:207)
	at android.content.res.Resources.getDrawable(Resources.java:775)
	at android.content.Context.getDrawable(Context.java:525)
	at androidx.core.content.ContextCompat.getDrawable(Unknown Source)
	at com.afollestad.materialdialogs.utils.MDUtil.resolveDrawable(Unknown Source)
	at com.afollestad.materialdialogs.utils.MDUtil.resolveDrawable$default(Unknown Source)
	at com.afollestad.materialdialogs.utils.DialogsKt.populateIcon(Unknown Source)
	at com.afollestad.materialdialogs.MaterialDialog.icon(Unknown Source)
	at com.afollestad.materialdialogs.MaterialDialog.icon$default(Unknown Source)
	at code.name.monkey.retromusic.dialogs.OptionsSheetDialogFragment.onCreateDialog(Unknown Source)
	at androidx.fragment.app.DialogFragment.onGetLayoutInflater(Unknown Source)
	at androidx.fragment.app.Fragment.performGetLayoutInflater(Unknown Source)
	at androidx.fragment.app.FragmentManager.moveToState(Unknown Source)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(Unknown Source)
	at androidx.fragment.app.FragmentManager.moveToState(Unknown Source)
	at androidx.fragment.app.BackStackRecord.executeOps(Unknown Source)
	at androidx.fragment.app.FragmentManager.executeOps(Unknown Source)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(Unknown Source)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(Unknown Source)
	at androidx.fragment.app.FragmentManager.execPendingActions(Unknown Source)
	at androidx.fragment.app.FragmentManager$3.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6247)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)

[09-09 20:06:26.191 1659:2151 W/ActivityManager]
  Force finishing activity code.name.monkey.retromusic/.activities.MainActivity

[09-09 20:06:26.197 1659:2151 D/InputDispatcher]
Focus left window: Window{4864001 u0 code.name.monkey.retromusic/code.name.monkey.retromusic.activities.MainActivity}

[09-09 20:06:26.317 1659:1778 D/InputDispatcher]
Focus entered window: Window{3ffd2e1 u0 Application Error: code.name.monkey.retromusic}

[09-09 20:06:26.554 1659:1883 I/WindowManager]
Window{3ffd2e1 u0 Application Error: code.name.monkey.retromusic} start dimming: flags=1820002 effectFlags=0, layer=111000

[09-09 20:06:26.570 1659:1883 I/WindowManager]
Window{3ffd2e1 u0 Application Error: code.name.monkey.retromusic} start dimming: flags=1820002 effectFlags=0, layer=111000

[09-09 20:06:26.703 1659:1777 W/ActivityManager]
Activity pause timeout for ActivityRecord{9b979aa u0 code.name.monkey.retromusic/.activities.MainActivity t2615 f}

[09-09 20:06:26.936 2446:2446 W/PackageManager]
Failure retrieving resources for code.name.monkey.retromusic: Resource ID #0x7f0f0000

[09-09 20:06:30.444 6593:6593 I/Finsky]
[1] pjw.d(7): Invalidating cached PackageState for code.name.monkey.retromusic

[09-09 20:06:30.485 6593:6593 I/Finsky]
[1] jtv.c(1): Package first launch for code.name.monkey.retromusic

[09-09 20:06:31.559 1659:2255 D/InputTransport]
channel '3ffd2e1 Application Error: code.name.monkey.retromusic (server)' : action=ACTION_DOWN(0), id=0, tooltype=1, deviceId=3, source=0x1002, flags=0x0, edgeFlags=0x0, metaState=0x0, buttonState=0x0, downTime=439950711000, eventTime=439950711000, pointerCount=1

[09-09 20:06:31.563 1659:2151 W/ActivityManager]
  Force finishing activity code.name.monkey.retromusic/.activities.MainActivity

[09-09 20:06:31.571 1659:2151 I/WindowManager]
Destroying surface Surface(name=code.name.monkey.retromusic/code.name.monkey.retromusic.activities.MainActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2177 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:960 com.android.server.wm.WindowState.removeLocked:1513 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2843 com.android.server.wm.WindowManagerService.removeWindowLocked:2798 com.android.server.wm.WindowManagerService.removeWindowLocked:2661 com.android.server.wm.WindowManagerServiceEx.removeWindowLocked:492 com.android.server.wm.AppWindowToken.removeAllWindows:548 

[09-09 20:06:31.587 1659:2151 D/InputDispatcher]
Window went away: Window{4864001 u0 code.name.monkey.retromusic/code.name.monkey.retromusic.activities.MainActivity}

[09-09 20:06:31.590 1659:1778 V/WindowManager]
Not removing Window{3ffd2e1 u0 Application Error: code.name.monkey.retromusic EXITING} due to exit animation 

[09-09 20:06:31.594 1659:2255 D/InputDispatcher]
Waiting for application to become ready for input: Window{3ffd2e1 u0 Application Error: code.name.monkey.retromusic}.  Reason: Waiting because the touched window's input channel is not registered with the input dispatcher.  The window may be in the process of being removed.

[09-09 20:06:31.602 1659:1778 D/InputDispatcher]
Focus left window: Window{3ffd2e1 u0 Application Error: code.name.monkey.retromusic}

[09-09 20:06:31.602 1659:1778 D/InputDispatcher]
Touched window was removed: Window{3ffd2e1 u0 Application Error: code.name.monkey.retromusic}

[09-09 20:06:31.602 1659:1778 D/InputDispatcher]
Window went away: Window{3ffd2e1 u0 Application Error: code.name.monkey.retromusic}

[09-09 20:06:31.607 1659:2151 I/ActivityManager]
Killing 21614:code.name.monkey.retromusic/u0a324 (adj 0): crash

[09-09 20:06:31.722 1659:1883 I/WindowManager]
Destroying surface Surface(name=Application Error: code.name.monkey.retromusic) called by com.android.server.wm.WindowStateAnimator.destroySurface:2177 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:960 com.android.server.wm.WindowState.destroyOrSaveSurface:2151 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementInner:432 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop:235 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement:183 com.android.server.wm.WindowManagerService$H.handleMessage:9185 android.os.Handler.dispatchMessage:102 

[09-09 20:06:31.729 2446:2446 W/PackageManager]
Failure retrieving resources for code.name.monkey.retromusic: Resource ID #0x7f0f0000

[09-09 20:06:33.380 1659:2736 I/ActivityManager]
START u0 {act=android.settings.APPLICATION_DETAILS_SETTINGS dat=package:code.name.monkey.retromusic flg=0x10008000 cmp=com.android.settings/.applications.InstalledAppDetails bnds=[625,540][1373,730]} from uid 1000 on display 0

[09-09 20:06:33.812 2544:2544 D/LDBHelper]
LDBHelper : Bundle[{extend_text=code.name.monkey.retromusic, pkg_name=com.android.settings, app_name=LGSettings, feature_name=LGSettings_ClickAppItem}]

[09-09 20:06:33.953 2544:2544 W/PackageManager]
Failure retrieving resources for code.name.monkey.retromusic: Resource ID #0x7f0f0000

[09-09 20:06:37.437 2544:2544 W/PackageManager]
Failure retrieving resources for code.name.monkey.retromusic: Resource ID #0x7f0f0000
