### ISSUE TITLE
Null pointer in DatePicker Dialog when selecting a date in a year outside of the defined scope

### ISSUE THREAD

**Issue by peterhav** [afollestad/material-dialogs#1915]
*Please consider making a Pull Request if you are capable of doing so.*

**Library Version:**

3.1.1
 
**Affected Device(s):**
 
All
 
**Describe the Bug:**

When setting a min and max date, if you select a year outside of the defined min and max dates, a NPE is thrown as soon as the user clicks the OK button:

```
kotlin.KotlinNullPointerException
        at com.afollestad.materialdialogs.datetime.DatePickerExtKt$datePicker$2.invoke(DatePickerExt.kt:64)
        at com.afollestad.materialdialogs.datetime.DatePickerExtKt$datePicker$2.invoke(DatePickerExt.kt)
        at com.afollestad.materialdialogs.callbacks.DialogCallbackExtKt.invokeAll(DialogCallbackExt.kt:68)
        at com.afollestad.materialdialogs.MaterialDialog.onActionButtonClicked$com_afollestad_material_dialogs_core(MaterialDialog.kt:424)
        at com.afollestad.materialdialogs.internal.button.DialogActionButtonLayout$onFinishInflate$1.onClick(DialogActionButtonLayout.kt:84)
        at android.view.View.performClick(View.java:6261)
        at android.widget.TextView.performClick(TextView.java:11163)
        at android.view.View$PerformClick.run(View.java:23748)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6776)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
```

**To Reproduce:**
1. Initiate the datePicker Dialog with a defined minDate and maxDate argument
2. In the opened dialog select a year before the minDate or after the maxDate
3. Press the OK button of the dialog

**Expected Behavior:**

A clear description of what you expected to happen: 
no NPE should be thrown. Either the OK button could be disabled in case no valid date has been selected by the user, or the dialog should just close without calling the dateCallback method.

**Comment by peterhav** [comment]
I tried to fix this bug today, but apparently it's already fixed in the codebase, just not released. The released code causing the NPE (in 3.1.1):

positiveButton(string.ok) {
  dateCallback?.invoke(it, getDatePicker().getDate()!!)
}

Same method in the current Git repo:

positiveButton(string.ok) {
  getDatePicker().getDate()?.let { datetime ->
    dateCallback?.invoke(it, datetime)
  }
}

Can a new release be created? Or is there a way to create the library locally?

**Comment by abeemukthees** [comment]
Encountred the same issue :(
Waiting for a update.
