### ISSUE TITLE
BottomSheet dismiss 

### ISSUE THREAD

**Issue by kmshack** [afollestad/material-dialogs#1946]
*Please consider making a Pull Request if you are capable of doing so.*

**Library Version:**

com.afollestad.material-dialogs:bottomsheets:3.2.1
 
**Affected Device(s):**
 
All older versions of android 10
 
**Describe the Bug:**

When the activity finishes at the time the bottomsheet is automatically dissmissed (comes in after the onHide callback completes)

Error Log
```
 java.lang.IllegalArgumentException: View=com.android.internal.policy.PhoneWindow$DecorView{db2aa8a V.ED..... R.....ID 0,0-1080,1920} not attached to window manager
        at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:424)
        at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:350)
        at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)
        at android.app.Dialog.dismissDialog(Dialog.java:362)
        at android.app.Dialog.dismiss(Dialog.java:345)
        at com.afollestad.materialdialogs.MaterialDialog.dismiss(MaterialDialog.kt:416)
        at com.afollestad.materialdialogs.bottomsheets.BottomSheet$setupBottomSheetBehavior$$inlined$apply$lambda$2.invoke(BottomSheet.kt:133)
        at com.afollestad.materialdialogs.bottomsheets.BottomSheet$setupBottomSheetBehavior$$inlined$apply$lambda$2.invoke(BottomSheet.kt:46)
        at com.afollestad.materialdialogs.bottomsheets.UtilKt$setCallbacks$1.onStateChanged(Util.kt:59)
        at com.google.android.material.bottomsheet.BottomSheetBehavior.setStateInternal(BottomSheetBehavior.java:1044)
        at com.google.android.material.bottomsheet.BottomSheetBehavior$SettleRunnable.run(BottomSheetBehavior.java:1454)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**To Reproduce:**
Try to finish the activity on the action of the button, such as positiveButton or negativeButton.

**Expected Behavior:**

A clear description of what you expected to happen.

**Comment by afollestad** [comment]
Hmmm, strange. I'm not able to reproduce this in the sample project.

**Comment by kmshack** [comment]
> Hmmm, strange. I'm not able to reproduce this in the sample project.

"com.google.android.material: material: 1.2.0-alpha04" 
Did you confirm this?

Let me write sample code.

**Comment by MFlisar** [comment]
I have a very similar problem and can reproduce it in my library.

My repo is here: https://github.com/MFlisar/MaterialDialogFragments

Reproduction steps:

* start the demo app in my repo
* simply check the chechbox at the top
* click the first list entry to open a very simply info dialog (it's wrapped inside a `DialogFragment`)
* turn the phone and see the app crash on the second turn mostly

Repeat the test without the bottom sheet style and you'll see that everything works perfectly fine. No leaks or crashes.

**Stacktrace 1 - on rotation sometimes**

     2020-03-07 18:45:13.099 11128-11128/com.michaelflisar.dialogs.app E/WindowManager: android.view.WindowLeaked: Activity com.michaelflisar.dialogs.MainActivity has leaked window DecorView@e10cfa7[MainActivity] that was originally added here
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:701)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:365)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
        at android.app.Dialog.show(Dialog.java:470)
        at com.afollestad.materialdialogs.MaterialDialog.show(MaterialDialog.kt:357)
        at androidx.fragment.app.DialogFragment.onStart(DialogFragment.java:486)
        at androidx.fragment.app.Fragment.performStart(Fragment.java:2632)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:915)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
        at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6986)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
