### ISSUE TITLE
Can not show dialog from an Service

### ISSUE THREAD

**Issue by tungthanhss** [afollestad/material-dialogs#1947]
Caused by: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.AppCompat (or a descendant).
        at com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:248)
        at com.google.android.material.internal.ThemeEnforcement.checkAppCompatTheme(ThemeEnforcement.java:218)

**Comment by enricocid** [comment]
You can't.
You need to provide a context attached to a window to be able to show a dialog
