### ISSUE TITLE
IllegalStateException when using fileChooser

### ISSUE THREAD

**Issue by DerrickRocha** [afollestad/material-dialogs#1969]
Library Version:

com.afollestad.material-dialogs:files:3.2.1
 
Affected Device(s):
 
Galaxy s9 with android 10
 
The app is crashing as soon as you try to show a MaterialDialog with a fileChooser:

  override fun onCreateDialog(savedInstanceState: Bundle?): Dialog {

        return MaterialDialog(activity!!).show {

            fileChooser(activity!!) { dialog, file -> // Crashes here

            }
        }
  }

Here is the error:
2020-03-27 12:37:03.490 32517-32517/com.example.filingcabinet E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.filingcabinet, PID: 32517
    java.lang.IllegalStateException: Module with the Main dispatcher is missing. Add dependency providing the Main dispatcher, e.g. 'kotlinx-coroutines-android'
        at kotlinx.coroutines.internal.MissingMainCoroutineDispatcher.missing(MainDispatchers.kt:90)
        at kotlinx.coroutines.internal.MissingMainCoroutineDispatcher.isDispatchNeeded(MainDispatchers.kt:71)
        at kotlinx.coroutines.DispatchedKt.resumeCancellable(Dispatched.kt:420)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:154)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
        at com.afollestad.materialdialogs.files.FileChooserAdapter.switchDirectory(FileChooserAdapter.kt:132)
        at com.afollestad.materialdialogs.files.FileChooserAdapter.<init>(FileChooserAdapter.kt:88)
        at com.afollestad.materialdialogs.files.DialogFileChooserExtKt.fileChooser(DialogFileChooserExt.kt:108)
        at com.afollestad.materialdialogs.files.DialogFileChooserExtKt.fileChooser$default(DialogFileChooserExt.kt:73)
        at com.example.filingcabinet.ui.dialogs.FilePickerDialog.onCreateDialog(FilePickerDialog.kt:26)
        at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:380)
        at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1412)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
        at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7811)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)

I'm using this coroutine library: 
org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.2

**Comment by gcantoni** [comment]
Did you give `READ_EXTERNAL_STORAGE` permission?

**Comment by DerrickRocha** [comment]
This works in version 3.3.0
