### ISSUE TITLE
cant recreate activity from MaterialDialog 

### ISSUE THREAD

**Issue by ghost1372** [afollestad/material-dialogs#1990]
**Library Version:**
3.3.0
 
**Describe the Bug:**

If we want to use `recreate()` in the MaterialDialog , the program crashes

```
MaterialDialog(context, BottomSheet(LayoutMode.WRAP_CONTENT)).show {
                listItems(R.array.skin) { _, index, text ->
                    activity.recreate()
                }
                positiveButton(R.string.select_theme)
                negativeButton(R.string.NegativeButton)
            }
```
error:
`java.lang.IllegalArgumentException: View=DecorView@3f0a3fb[MainActivity] not attached to window manager at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:517) at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:426) at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:126) at android.app.Dialog.dismissDialog(Dialog.java:389) at android.app.Dialog.dismiss(Dialog.java:371) at com.afollestad.materialdialogs.MaterialDialog.dismiss(MaterialDialog.kt:400) at com.afollestad.materialdialogs.bottomsheets.BottomSheet$setupBottomSheetBehavior$$inlined$apply$lambda$2.invoke(BottomSheet.kt:133) at com.afollestad.materialdialogs.bottomsheets.BottomSheet$setupBottomSheetBehavior$$inlined$apply$lambda$2.invoke(BottomSheet.kt:46) at com.afollestad.materialdialogs.bottomsheets.UtilKt$setCallbacks$1.onStateChanged(Util.kt:59) at com.google.android.material.bottomsheet.BottomSheetBehavior.setStateInternal(BottomSheetBehavior.java:1089) at com.google.android.material.bottomsheet.BottomSheetBehavior$SettleRunnable.run(BottomSheetBehavior.java:1505) at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)`

**Comment by enricocid** [comment]
I think you should dismiss the dialog before recreating the activity. The same crash can be reproduced also with standard dialogs.

**Comment by ghost1372** [comment]
@enricocid  i dismiss dialog but issue still exist
