### ISSUE TITLE
Crash in LinkTransformationMethod.onFocusChanged

### ISSUE THREAD

**Issue by strooooke** [afollestad/material-dialogs#2020]
**Library Version:**

3.1.1 (not on 3.3.0 because of #2946)
 
**Affected Device(s):**
 
ALCATEL ONETOUCH IDOL 3 (5.5) with Android 6.0.1
 
**Describe the Bug:**

Got crash report(s) (same user, apparently) in production:

```
Fatal Exception: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter previouslyFocusedRect
       at com.afollestad.materialdialogs.internal.message.LinkTransformationMethod.onFocusChanged(LinkTransformationMethod.java)
       at android.widget.TextView.onFocusChanged(TextView.java:8226)
       at android.view.View.handleFocusGainInternal(View.java:5483)
  ...
```

Makes sense - `android.text.method.TransformationMethod` claims nothing about the nullability of the parameters of `onFocusChanged` - should just be nullable here, doesn't care about it anyway.

**Comment by goforbg** [comment]
@strooooke I'm trying to work on this, can you tell me how to replicate the crash?

**Comment by strooooke** [comment]
Nope, sorry - just something I saw from crash reporting of the production version of our app. I don't have such a device, and judging from the fact that the app uses material-dialogs since forever and I've never seen this before, it might be a very, very specific constellation where `previouslyFocusedRect` takes in fact value `null`. But it is allowed to, and the crash message is quite clear about what the problem is.

**Comment by goforbg** [comment]
Aww, that's sad! I use it on one of my apps in production too haven't come across such an issue.

**Comment by strooooke** [comment]
As I said - first time I've seen it. But the fix is trivial; I'd do it myself if I had the time.
