### ISSUE TITLE
SingleChoiceDialogAdapter.kt line 160 com.afollestad.materialdialogs.internal.list.SingleChoiceDialogAdapter.positiveButtonClicked

### ISSUE THREAD

**Issue by devmichaelgirgis** [afollestad/material-dialogs#2023]
*Please consider making a Pull Request if you are capable of doing so. Note that versions before 2.0.0 are no longer supported.*

**Library Version:**

3.2.1
 
**Affected Device(s):**
 
 Huawei MediaPad T5
 
**Describe the Bug:**

Fatal Exception: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
       at java.util.ArrayList.get(ArrayList.java:437)
       at com.afollestad.materialdialogs.internal.list.SingleChoiceDialogAdapter.positiveButtonClicked(SingleChoiceDialogAdapter.kt:160)
       at com.afollestad.materialdialogs.MaterialDialog.onActionButtonClicked$core(MaterialDialog.kt:424)
       at com.afollestad.materialdialogs.internal.button.DialogActionButtonLayout$onFinishInflate$1.onClick(DialogActionButtonLayout.kt:84)
       at android.view.View.performClick(View.java:6291)
       at android.view.View$PerformClick.run(View.java:24931)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:101)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7529)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**To Reproduce:**
1. 
2. 
3. 

**Expected Behavior:**

A clear description of what you expected to happen.

**Comment by mik629** [comment]
[Here](https://github.com/afollestad/material-dialogs/pull/2025) is an idea (in the form of PR) of how this might be fixed. Though, I guess the case when input array is empty should be handled separately.
