### ISSUE TITLE
datePicker: Your `maxDate` must be bigger than `currentDate` error when dates are equal.

### ISSUE THREAD

**Issue by pchmielowski** [afollestad/material-dialogs#2036]
**Library Version:**

3.3.0
 
**Affected Device(s):**
 
All
 
**Describe the Bug:**

Application crashes when showing `MaterialDialog` with `datePicker` when `maxDate == currentDate`.

**To Reproduce:**
Run the following code:
```
MaterialDialog(context, BottomSheet()).show {
    val calendar = Calendar.getInstance()
    datePicker(
        maxDate = calendar,
        currentDate = calendar,
    )
}
```
An exception is thrown:
```
    java.lang.IllegalStateException: Your `maxDate` must be bigger than `currentDate`.
        at com.afollestad.materialdialogs.datetime.DatePickerExtKt.datePicker(DatePickerExt.kt:52)
        at com.afollestad.materialdialogs.datetime.DatePickerExtKt.datePicker$default(DatePickerExt.kt:41)
```

**Expected Behavior:**

The exception should not be thrown as this is a valid situation to have `currentDate` set to the same values as `maxDate`.
The only invalid value for `currentDate` should be being *after* `maxDate`.

**Comment by m-i-n-a-r** [comment]
I have this exact same code in my app [here](https://github.com/m-i-n-a-r/birday/blob/master/app/src/main/java/com/minar/birday/fragments/HomeFragment.kt) at line 467. I had some suspicious crashes of the date picker in my Play Store crash report to be honest, and this bug could be involved in some way. But I tested the app on many devices from api 26 to 30 and it seems to work.

**Comment by gobrien37** [comment]
I submitted a small pull request that I think should fix this. I agree that logically, the minimum and maximum dates should be considered valid for the current date. One thing that will still crash after this change is when min and max dates are the same, although at that point there would only be one available date anyway and a picker would not be necessary. Also, this comparison is done in the function validateMinAndMax() in MinMaxController.kt, which is read-only.

All I did was change the following lines in DatePickerExt.kt if you want to change it for yourself without waiting for another official release.

Original:
```
check(minDate == null || currentDate == null || minDate.before(currentDate)) {
    "Your `minDate` must be less than `currentDate`."
}
  check(maxDate == null || currentDate == null || maxDate.after(currentDate)) {
    "Your `maxDate` must be bigger than `currentDate`."
}
```
Changed:
  ```
check(minDate == null || currentDate == null || !minDate.after(currentDate)) {
    "Your `minDate` cannot be greater than `currentDate`."
  }
  check(maxDate == null || currentDate == null || !maxDate.before(currentDate)) {
    "Your `maxDate` cannot be less than `currentDate`."
  }
```

**Comment by codeversed** [comment]
I personally had to revert back to `3.1.1`. This logic really does need to be fixed for any practical use case where the min or max date is the same as the current date. From what I see, there is no way you can accomplish this with `3.2.x`+. 

@afollestad Any chance this will get a fix anytime soon?

**Comment by m-i-n-a-r** [comment]
Friendly advice: use the Material Components Datepicker, it's bugfree, better in any possible way and has two input modes. I don't want to sound rude, but at this point I think this library is kinda dead or poorly active.
