### ISSUE TITLE
ClassCastException: Button Cannot be Cast to FrameLayout

### ISSUE THREAD

**Issue by KevinColemanInc** [afollestad/material-dialogs#238]
I get error sometimes.  Not really sure whats going on:

    java.lang.ClassCastException: android.widget.Button cannot be cast to android.widget.FrameLayout
            at com.afollestad.materialdialogs.MaterialDialog.invalidateActions(MaterialDialog.java:707)
            at com.afollestad.materialdialogs.MaterialDialog.<init>(MaterialDialog.java:268)
            at com.afollestad.materialdialogs.MaterialDialog$Builder.build(MaterialDialog.java:1445)
            at com.afollestad.materialdialogs.MaterialDialog$Builder.show(MaterialDialog.java:1449)

Running latest release

**Comment by afollestad** [comment]
Hmm. Just checked my code, this shouldn't happen. You should make sure you have the latest code.
