### ISSUE TITLE
Loading MaterialDialog in old PreferenceActivity

### ISSUE THREAD

**Issue by fncapps** [afollestad/material-dialogs#279]
I would like to use a MaterialDialog on a ``Preference.OnPreferenceClickListener()`` but the app crashes giving an error in the first line which is:  ``new MaterialDialog.Builder(getApplicationContext())``.

Let me know if there is something I'm doing wrong!
Thanks

(NOTE: I know I should update my Preferences and also I shouldn't be mixing up a holo-themed app with MaterialDialogs, but the redesign will come later.)

**Comment by afollestad** [comment]
Well, I can't really guess. I would need to see a LogCat to understand the issue.

**Comment by fncapps** [comment]
Here you go:

``02-26 23:17:50.528  29177-29177/z.myapp.debug E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: z.myapp.debug, PID: 29177
    android.view.WindowManager$BadTokenException: Unable to add window -- token null is not for an application
            at android.view.ViewRootImpl.setView(ViewRootImpl.java:685)
            at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:288)
            at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
            at android.app.Dialog.show(Dialog.java:312)
            at com.afollestad.materialdialogs.MaterialDialog.show(MaterialDialog.java:1463)
            at com.afollestad.materialdialogs.MaterialDialog$Builder.show(MaterialDialog.java:1454)
            at z.myapp.packageOne.ClassOne$6.onPreferenceClick(WebBrowserSettings.java:178)
            at android.preference.Preference.performClick(Preference.java:1123)
            at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:214)
            at android.widget.AdapterView.performItemClick(AdapterView.java:334)
            at android.widget.AbsListView.performItemClick(AbsListView.java:1545)
            at android.widget.AbsListView$PerformClick.run(AbsListView.java:3683)
            at android.widget.AbsListView$3.run(AbsListView.java:5597)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:5834)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)``

Thanks for the help

**Comment by afollestad** [comment]
Oh, that means you tried to show the dialog before the Activity was actually open. You can only show dialogs after a call to super.onCreate() and before the Activity is hidden.

**Comment by fncapps** [comment]
Didn't manage to solve the problem..

**Comment by afollestad** [comment]
There must be something different from what's used in the sample project.

Now that I look at your code at the top again, I wouldn't recommend using getApplicationContext(); that doesn't contain a window to attach to. You should be passing an Activity object in general. 

E.g.

```java
new MaterialDialog.Builder(this)
       ...
```

If it's within a callback, e.g. onChangeListeners or something:

```java
new MaterialDialog.Builder(ActivityName.this)
       ...
```

**Comment by afollestad** [comment]
Please try release 0.6.3.2, available now.
