### ISSUE TITLE
Edit Text Preference doesn't work

### ISSUE THREAD

**Issue by timoabi** [afollestad/material-dialogs#284]
java.lang.NullPointerException
            at com.afollestad.materialdialogs.prefs.MaterialEditTextPreference.showDialog(MaterialEditTextPreference.java:62)
            at android.preference.DialogPreference.onClick(DialogPreference.java:266)
            at android.preference.Preference.performClick(Preference.java:952)
            at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:215)
            at android.widget.AdapterView.performItemClick(AdapterView.java:299)
            at android.widget.AbsListView.performItemClick(AbsListView.java:1113)
            at android.widget.AbsListView$PerformClick.run(AbsListView.java:2911)
            at android.widget.AbsListView$3.run(AbsListView.java:3645)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by afollestad** [comment]
Well, the logcat doesn't help too much. 

Does the sample project run on your phone?

**Comment by afollestad** [comment]
However, the code for the `MaterialEditTextPreference` was changed around quite a bit in the current code base so it will most likely be fixed in the next release.

**Comment by afollestad** [comment]
Please try release 0.6.3.2, available now.
