### ISSUE TITLE
java.lang.UnsupportedOperationException when using MaterialDialog

### ISSUE THREAD

**Issue by airk000** [afollestad/material-dialogs#311]
as following logcat:

```
Caused by: android.view.InflateException: Binary XML file line #105: Error inflating class 
	at android.view.LayoutInflater.createView(LayoutInflater.java:606)
	at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:653)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:678)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:739)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:742)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
	at com.a.a.c.(MaterialDialog.java:104)
	at com.a.a.g.a(MaterialDialog.java:1449)
        ... 11 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.constructNative(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
	at android.view.LayoutInflater.createView(LayoutInflater.java:586)
	... 28 more
Caused by: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x12
	at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:463)
	at android.view.View.(View.java:2846)
	at android.view.ViewGroup.(ViewGroup.java:385)
	at android.widget.FrameLayout.(FrameLayout.java:99)
	at android.widget.FrameLayout.(FrameLayout.java:95)
	... 31 more
```

so, I'm not sure is this issue caused by material-dialogs, but it really seems be. Can anyone help me?

And by the way, it's not always happen for all devices, only one Device(OPPO Finder).

**Comment by afollestad** [comment]
You might need to research this a bit yourself. Unfortunately I have no way to solve this from the logcat.

**Comment by airk000** [comment]
:( OK, I'll try my best for it. Thanks all the same.

**Comment by shufeike** [comment]
Hi, I have met the same exception on OPPO, have you fixed it?

**Comment by airk000** [comment]
@shufeike not yet.

**Comment by afollestad** [comment]
Any news on this?

**Comment by eneim** [comment]
why don't you post the place you use MaterialDialog and its xml?

**Comment by afollestad** [comment]
Does this crash still happen with the latest versions of the library?

**Comment by airk000** [comment]
@afollestad I'll try it later and tell u the result ASAP.

**Comment by afollestad** [comment]
There's a possibility that release 0.7.0.0 fixes this issue, since large internal parts of the library were pretty much redone. Let me know.

https://github.com/afollestad/material-dialogs/releases/tag/v0.7.0.0

**Comment by airk000** [comment]
It has been in testing process, let's waiting for the result. @afollestad

**Comment by airk000** [comment]
@afollestad I have to say: Nice shot! It's fixed.
