### ISSUE TITLE
MaterialMultiSelectListPreference should inherit from MultiSelectListPreference

### ISSUE THREAD

**Issue by askfor** [afollestad/material-dialogs#339]
Now it inherit from `ListPreference`, But `ListPreference` read persisted value as String in `onSetInitialValue`. so `onSetInitialValue` will throw exception.

```Bash
Caused by: java.lang.ClassCastException: java.util.HashSet cannot be cast to java.lang.String
       at android.app.SharedPreferencesImpl.getString(SharedPreferencesImpl.java:223)
       at android.preference.Preference.getPersistedString(Preference.java:1460)
       at android.preference.ListPreference.onSetInitialValue(ListPreference.java:294)
       at android.preference.Preference.dispatchSetInitialValue(Preference.java:1376)
       at android.preference.Preference.onAttachedToHierarchy(Preference.java:1171)
       at android.preference.PreferenceGroup.addPreference(PreferenceGroup.java:167)
       at android.preference.PreferenceGroup.addItemFromInflater(PreferenceGroup.java:108)
       at android.preference.PreferenceGroup.addItemFromInflater(PreferenceGroup.java:45)
       at android.preference.GenericInflater.rInflate(GenericInflater.java:488)
```

And `MaterialMultiSelectListPreference` missing `getValues` too.

**Comment by afollestad** [comment]
Let me know if https://github.com/afollestad/material-dialogs/commit/31618d2191adc7d69b73c09f8dc8c76d7dcf744d fixes this.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.6.4.6

**Comment by askfor** [comment]
for (Integer i : selectedIndicesList) {
            selectedTitles.add(mBuilder.items[i]);
}

should be mBuilder.items[i-1]

**Comment by askfor** [comment]
In the sample if I change preference_values like this:
    <string-array name="preference_values">
        <item>0</item>
        <item>1</item>
        <item>2</item>
        <item>3</item>
        <item>4</item>
    </string-array>
MaterialMultiSelectListPreference won't work anymore. It will throw an exception like this:

Process: com.afollestad.materialdialogssample, PID: 31400
java.lang.ArrayIndexOutOfBoundsException: length=5; index=-1
	at com.afollestad.materialdialogs.MaterialDialog.sendMultichoiceCallback(MaterialDialog.java:859)
	at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:876)
	at android.view.View.performClick(View.java:4754)
	at android.view.View$PerformClick.run(View.java:19605)


It seems mBuilder.selectedIndices was set to [-1]  in  MaterialDialog line 265 , I don't know where this value come from.

**Comment by afollestad** [comment]
Feel free to attempt this yourself. I'm on spring break from college right now.
