### ISSUE TITLE
Sample app crash with API 10: Preference Fragment

### ISSUE THREAD

**Issue by Kuitsi** [afollestad/material-dialogs#361]
java.lang.NoSuchMethodError: com.afollestad.materialdialogssample.PreferenceActivity.getFragmentManager
    at com.afollestad.materialdialogssample.PreferenceActivity.onCreate(PreferenceActivity.java:23)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1660)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1716)
    at android.app.ActivityThread.access$1500(ActivityThread.java:124)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:968)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:130)
    at android.app.ActivityThread.main(ActivityThread.java:3806)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:507)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by afollestad** [comment]
The other two are fixed, this one is a little harder since `PreferenceFragment` cannot be used on lower API levels.

**Comment by afollestad** [comment]
@Kuitsi I should mention that this isn't a Material Dialogs issue. This is an issue specific to the sample project.

**Comment by Kuitsi** [comment]
This is not working either. App does not crash but the screen is empty, only ActionBar is visible.

**Comment by afollestad** [comment]
Not sure if there's much I can do about this then, I might have to disable the Settings Activity on API 10. The preferences themselves aren't affected, but there's no AppCompat variation of `PreferenceActivity` (which extends `ActionBarActivity`) so I have to use `PreferenceFragment`s.

**Comment by Kuitsi** [comment]
We have in [Bitbeaker](https://bitbucket.org/bitbeaker-dev-team/bitbeaker/src/a37e2afa6c7426bb4d1ea61b0de9d63e05141ebf/app/src/main/java/fi/iki/kuitsi/bitbeaker/activities/SettingsActivity.java?at=default) something that may help. It can fall back to old style preferences but it can use fragments too.

**Comment by afollestad** [comment]
Well like I said above, PreferenceActivity can't be used because it won't work correctly with AppCompat theming.

**Comment by afollestad** [comment]
Alright, the latest commit should be a more complete solution.

The sample will use PreferenceActivity on API 10 and below, which won't display an action bar due to AppCompat not supporting it. Above API 10, the regular solution (ActionBarActivity with API 11+ PreferenceFragments) will be used. 

The sample project is a reflection of the library, obviously, but this PreferenceActivity sample is independent from the Material preferences themselves.

**Comment by Kuitsi** [comment]
Nope. The first crash is a classic

    android.content.ActivityNotFoundException: Unable to find explicit activity class {com.afollestad.materialdialogssample/com.afollestad.materialdialogssample.PreferenceActivityCompat}; have you declared this activity in your AndroidManifest.xml?

After it is fixed, the next crash is

    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.afollestad.materialdialogssample/com.afollestad.materialdialogssample.PreferenceActivityCompat}: android.view.InflateException: Binary XML file line #13: Error inflating class com.afollestad.materialdialogs.prefs.MaterialMultiSelectListPreference

Your MaterialMultiSelectListPreference requires API 11 as stated in it's source code. I tried what happens if I just comment it out from `res/xml/preferences.xml`. Everything seems to be ok until you click the last one, MaterialEditTextPreference.

    java.lang.ClassCastException: android.widget.TextView
            at com.afollestad.materialdialogs.MaterialDialog.canViewOrChildScroll(MaterialDialog.java:366)
            at com.afollestad.materialdialogs.MaterialDialog.canViewOrChildScroll(MaterialDialog.java:366)
            at com.afollestad.materialdialogs.MaterialDialog.invalidateCustomViewAssociations(MaterialDialog.java:206)
            at com.afollestad.materialdialogs.DialogInit$1.onGlobalLayout(DialogInit.java:266)

**Comment by afollestad** [comment]
I didn't register then activity for API 10 in the manifest. Feel free to do
it yourself, my personal life is more busy on the weekend.

**Comment by afollestad** [comment]
Nevermind already got it with the latest release

https://github.com/afollestad/material-dialogs/releases/tag/v0.6.6.2

**Comment by Kuitsi** [comment]
I guess you did not see my commit https://github.com/Kuitsi/material-dialogs/commit/a446b59f11747ea0ee9fb9dea02cabde2d0cef5c (in my fork, referenced in this issue but I did not create a pull request for it yet) from this morning. You can't even try to load MaterialMultiSelectListPreference in preferences.xml when opening PreferenceActivityCompat or the app will crash.

**Comment by afollestad** [comment]
Oh sorry, good catch.

Fixed that by using `xml-v11` instead: https://github.com/afollestad/material-dialogs/commit/8ac9c0374bd06ee5e15d0aaa99750a6102b3c2d3

**Comment by Kuitsi** [comment]
Thanks. No more issues at this point :)

**Comment by afollestad** [comment]
Cool :) thanks for your bug reports
