### ISSUE TITLE
Sample app crash with API 10: Custom View No Scroll #2

### ISSUE THREAD

**Issue by Kuitsi** [afollestad/material-dialogs#363]
java.lang.NoClassDefFoundError: com.afollestad.materialdialogssample.ColorChooserDialog
    at com.afollestad.materialdialogssample.MainActivity.showCustomColorChooser(MainActivity.java:477)
    at com.afollestad.materialdialogssample.MainActivity.access$1600(MainActivity.java:36)
    at com.afollestad.materialdialogssample.MainActivity$17.onClick(MainActivity.java:173)
    at android.view.View.performClick(View.java:2494)
    at android.view.View$PerformClick.run(View.java:9122)
    at android.os.Handler.handleCallback(Handler.java:587)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:130)
    at android.app.ActivityThread.main(ActivityThread.java:3806)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:507)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by afollestad** [comment]
All three of these crash reports are basically the same thing. I'll have a fix in a minute or two.

**Comment by afollestad** [comment]
@Kuitsi https://github.com/afollestad/material-dialogs/releases/tag/v0.6.5.2

**Comment by Kuitsi** [comment]
Still not working: GridLayout in /sample/src/main/res/layout/dialog_color_chooser.xml requires API 14.

    E/AndroidRuntime﹕ FATAL EXCEPTION: main
    android.view.InflateException: Binary XML file line #9: Error inflating class GridLayout
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:581)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:623)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:408)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:276)
            at com.afollestad.materialdialogs.MaterialDialog$Builder.customView(MaterialDialog.java:1112)
            at com.afollestad.materialdialogssample.ColorChooserDialog.onCreateDialog(ColorChooserDialog.java:48)
    ...
    Caused by: java.lang.ClassNotFoundException: android.view.GridLayout in loader dalvik.system.PathClassLoader[/data/app/com.afollestad.materialdialogssample-1.apk]
    ...
