### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by fredyrincon** [afollestad/material-dialogs#367]
Hi, It happens sometimes, but I have not be able to get the steps to reproduce it. But if happens it crash the app. so it is anyway you can control or handle it. 

Thank you

```
java.lang.NullPointerException
at android.widget.TextView.append(TextView.java:3951)
at com.afollestad.materialdialogs.prefs.MaterialEditTextPreference.onBindDialogView(MaterialEditTextPreference.java:56)
at com.afollestad.materialdialogs.prefs.MaterialEditTextPreference.showDialog(MaterialEditTextPreference.java:76)
at android.preference.DialogPreference.onClick(DialogPreference.java:278)
at android.preference.Preference.performClick(Preference.java:958)
at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:229)
at android.widget.AdapterView.performItemClick(AdapterView.java:301)
at android.widget.AbsListView.performItemClick(AbsListView.java:1508)
at android.widget.AbsListView$PerformClick.run(AbsListView.java:3331)
at android.os.Handler.handleCallback(Handler.java:730)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5414)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1187)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by afollestad** [comment]
Well the log makes it pretty easy to trace it; line 56 of MaterialEditTextPreference. I'll fix it in a bit.

**Comment by afollestad** [comment]
I looked through my code and this is literally impossible. This log suggests `getEditText()` is returning null, it can't, because that's a method from the Android framework and there's no way it can ever be null.

Make sure you're using the latest version of the library (0.6.5.2).

**Comment by fredyrincon** [comment]
Thank you. I just updated it. Ill keep and eye in it.

**Comment by afollestad** [comment]
This will be fully repaired in the upcoming update
