### ISSUE TITLE
NullPointerException on orientation change with ColorChooserDialog

### ISSUE THREAD

**Issue by kenumir** [afollestad/material-dialogs#373]
Stack trace:

```
com.afollestad.materialdialogssample E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.afollestad.materialdialogssample, PID: 20391
    java.lang.NullPointerException: Attempt to invoke interface method 'void com.afollestad.materialdialogssample.ColorChooserDialog$Callback.onColorSelection(int, int, int)' on a null object reference
            at com.afollestad.materialdialogssample.ColorChooserDialog.onClick(ColorChooserDialog.java:34)
            at android.view.View.performClick(View.java:4780)
            at android.view.View$PerformClick.run(View.java:19866)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

I prepare pull request to fix this error.
YT: https://www.youtube.com/watch?v=mIUvEejpmJE

Edit: no pull request permission :(

**Comment by afollestad** [comment]
Pull request permission? You make a Fork of the repository and make a pull request to this one. No permission needed.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.6.6.2

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.6.6.2
