### ISSUE TITLE
java.lang.NullPointerException at MaterialEditTextPreference.onBindDialogView when Preference is null

### ISSUE THREAD

**Issue by dgyuri** [afollestad/material-dialogs#383]
Preference is not initialized yet and it has no default value.

EditText/TextView.append called with null.

```
FATAL EXCEPTION: main
    java.lang.NullPointerException
        at android.widget.TextView.append(TextView.java:3118)
        at com.afollestad.materialdialogs.prefs.MaterialEditTextPreference.onBindDialogView(MaterialEditTextPreference.java:56)
        at com.afollestad.materialdialogs.prefs.MaterialEditTextPreference.showDialog(MaterialEditTextPreference.java:77)
        at android.preference.DialogPreference.onClick(DialogPreference.java:266)
        at android.preference.Preference.performClick(Preference.java:942)
        at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:208)
```

**Comment by afollestad** [comment]
Were you planning to make a pull request for this? I don't think it's necessary to add all that extra stuff, it's only really necessary to change the text at all if `getText()` is not null. Otherwise the text would be empty anyways.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.6.7.1
