### ISSUE TITLE
Dialog doesn't dismiss in protected void onPostExecute(Result result)

### ISSUE THREAD

**Issue by jianminglok** [afollestad/material-dialogs#393]
I cannot dismiss the material progress dialog during the onPostExecute.

Here is my code below:

```java
    protected Command<Result> command;
    protected Context context;
    protected ResultListener<Result> resultListener;
    protected Exception exception;
    MaterialDialog dialogue;
    protected HookUpProgressDialog progressDialog;
    protected boolean showMaterialDialog = false;
    private static int taskCount;

    public ProcyonAsyncTask(Command<Result> command, ResultListener<Result> resultListener, Context context, boolean showMaterialDialog) {
        super();
        this.command = command;
        this.resultListener = resultListener;
        this.context = context;
        this.showMaterialDialog = showMaterialDialog;
    }

    @Override
    protected void onPreExecute() {
        if (SpikaApp.hasNetworkConnection()) {
            super.onPreExecute();
            if (showMaterialDialog) {
                MaterialDialog dialogue = new MaterialDialog.Builder(context)
                        .title(R.string.loading_progress_dialog_title)
                        .content(R.string.loading_progress_dialog_content)
                        .progress(true, 0)
                        .show();
            }
        } else {
            this.cancel(false);
            Log.e(Const.ERROR, Const.OFFLINE);
            new AlertDialogWrapper.Builder(context)
                    .setTitle(R.string.no_internet_connection_title)
                    .setMessage(R.string.no_internet_connection)
                    .setNegativeButton(R.string.OK, new DialogInterface.OnClickListener() {
                        @Override
                        public void onClick(DialogInterface dialog, int which) {
                            dialog.dismiss();
                        }
                    }).show();
        }
    }

    @Override
    protected Result doInBackground(Params... params) {
        Result result = null;
        try {
            result = (Result) command.execute();
        } catch (JSONException e) {
            exception = e;
            e.printStackTrace();
        } catch (IOException e) {
            exception = e;
            e.printStackTrace();
        } catch (SpikaException e) {
            exception = e;
            e.printStackTrace();
        } catch (IllegalStateException e) {
            exception = e;
            e.printStackTrace();
        } catch (NullPointerException e) {
            exception = e;
            e.printStackTrace();
        } catch (SpikaForbiddenException e) {
            exception = e;
            e.printStackTrace();
        }
        return result;
    }

    @Override
    protected void onPostExecute(Result result) {
        super.onPostExecute(result);

        try{
            if((this.dialogue != null) && this.dialogue.isShowing()) {
                dialogue.dismiss();
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
        finally
        {
            dialogue.dismiss();
        }

            if (exception != null) {
                String error = (exception.getMessage() != null) ? exception.getMessage() : context.getString(R.string.an_internal_error_has_occurred);

                Log.e(Const.ERROR, error);

                final HookUpDialog dialog = new HookUpDialog(context);
                String errorMessage = null;
                if (exception instanceof IOException) {
                    errorMessage = context.getString(R.string.can_not_connect_to_server) + "\n" + exception.getClass().getName() + " " + error;
                } else if (exception instanceof JSONException) {
                    errorMessage = context.getString(R.string.an_internal_error_has_occurred) + "\n" + exception.getClass().getName() + " " + error;
                } else if (exception instanceof NullPointerException) {
                    errorMessage = context.getString(R.string.an_internal_error_has_occurred) + "\n" + exception.getClass().getName() + " " + error;
                } else if (exception instanceof SpikaException) {
                    errorMessage = error;
                } else if (exception instanceof SpikaForbiddenException) {
                    errorMessage = context.getString(R.string.an_internal_error_has_occurred) + "\n" + error;
                } else {
                    errorMessage = context.getString(R.string.an_internal_error_has_occurred) + "\n" + exception.getClass().getName() + " " + error;
                }

                if (context instanceof Activity) {
                    if (!((Activity) context).isFinishing()) {
                        if (exception instanceof SpikaForbiddenException) {
                            //token expired
                            errorMessage = context.getString(R.string.token_expired_error);
                            dialog.setOnDismissListener(new OnDismissListener() {

                                @Override
                                public void onDismiss(DialogInterface dialog) {
                                    context.startActivity(new Intent(context, SignInActivity.class)
                                            .putExtra(context.getString(R.string.token_expired_error), true));
                                    ((Activity) context).finish();
                                }
                            });
                        }
                        dialog.showOnlyOK(errorMessage);
                    }
                }

                if (resultListener != null) resultListener.onResultsFail();
            } else {
                if (resultListener != null) resultListener.onResultsSucceded(result);
            }
        }
    }
```

The logcat : 
```Gradle
 28086-28086/com.cloverstudio.spika E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NullPointerException
            at com.rhytion.procyon.couchdb.ProcyonAsyncTask.onPostExecute(ProcyonAsyncTask.java:126)
            at android.os.AsyncTask.finish(AsyncTask.java:631)
            at android.os.AsyncTask.access$600(AsyncTask.java:177)
            at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:176)
            at android.app.ActivityThread.main(ActivityThread.java:5317)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
            at dalvik.system.NativeStart.main(Native Method)
```

And this is my full code on Github: https://github.com/jianminglok/procyon-Android

Any help would be appreciated. Thanks in advance.

**Comment by afollestad** [comment]
Updated your comment to add syntax highlighting.

`dismiss()` is a method of `AlertDialog` (which is at the base of `MaterialDialog`), so if this is a bug it's a bug with Android's `AlertDialog`.

Generally, any issue with dismissal will be due to the `Activity` (window) the dialog was attached to no longer being open, or not calling `dismiss()` on the UI thread.
