### ISSUE TITLE
Material Dialog From Fragment

### ISSUE THREAD

**Issue by ferenczAndras** [afollestad/material-dialogs#409]
Hy. I want to show a dialog from a Fragment and how I see is  not possible yet, using Material Dialog.
I am getting  the following exception:

  android.view.WindowManager$BadTokenException: Unable to add window -- token null is not for an application
            at android.view.ViewRootImpl.setView(ViewRootImpl.java:755)
            at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:278)
            at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
            at android.app.Dialog.show(Dialog.java:288)
            at com.afollestad.materialdialogs.MaterialDialog.show(MaterialDialog.java:1510)
            at com.afollestad.materialdialogs.MaterialDialog$Builder.show(MaterialDialog.java:1501)

**Comment by afollestad** [comment]
You need to show the dialog after the Activity and Fragment are both visible. E.g. in onViewCreated or onResume of your Fragment. 

This isn't a bug of this library.
