### ISSUE TITLE
Application crash with custom View

### ISSUE THREAD

**Issue by TomasValenta** [afollestad/material-dialogs#439]
Hi,

I use customView layout with listview and edittext with filterable ability like this:

```java
	MaterialDialog dialog = new MaterialDialog.Builder(mActivity)
			.title(R.string.selecting_by_name)
			.customView(R.layout.manual_selection_dialog, false)
			.callback(new MaterialDialog.ButtonCallback() {
				@Override
				public void onPositive(MaterialDialog dialog) {

					new manualSelectionBackgroundTask().execute();
				}

			})
			.positiveText(R.string.import_selected)
			.build();
```

When the list is blank, then app crash with this errors in log:

```gradle
	java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getBottom()' on a null object reference
	at com.afollestad.materialdialogs.internal.MDRootLayout.invalidateDividersForScrollingView(MDRootLayout.java:439)
	at com.afollestad.materialdialogs.internal.MDRootLayout.access$000(MDRootLayout.java:34)
	at com.afollestad.materialdialogs.internal.MDRootLayout$1.onScrollChanged(MDRootLayout.java:411)
	.....
```

It is bug or not?

**Comment by afollestad** [comment]
Updated your code/log for syntax highlighting.

Yes, this is definitely a bug lol. Fixing it now.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.1.2

**Comment by TomasValenta** [comment]
Ok,
but I think, issue is not fixed. New crash report:

```gradle
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getBottom()' on a null object reference
at com.afollestad.materialdialogs.internal.MDRootLayout.invalidateDividersForScrollingView(MDRootLayout.java:442)
at com.afollestad.materialdialogs.internal.MDRootLayout.access$000(MDRootLayout.java:34)
at com.afollestad.materialdialogs.internal.MDRootLayout$1.onScrollChanged(MDRootLayout.java:414)
```

**Comment by jaredrummler** [comment]
Added a check if the ViewGroup has children did nothing. You can see the error is in [`invalidateDividersForScrollingView`](https://github.com/afollestad/material-dialogs/blob/master/library/src/main/java/com/afollestad/materialdialogs/internal/MDRootLayout.java#L427-446)

I would change

```java
if (bottom || topAndBottom) {
```

to

```java
if ((bottom || topAndBottom) && view.getChildCount() > 0) {
```

**Comment by afollestad** [comment]
@jaredrummler that was one of them, but there was a few others too. Thanks :)
