### ISSUE TITLE
Combine items with customView = Crash

### ISSUE THREAD

**Issue by Ph1b** [afollestad/material-dialogs#482]
When using a custom view combined with items, I get a crash. Without the customView everything is fine.

```java
    new MaterialDialog.Builder(getActivity())
        .title(R.string.pref_support_title)
        .items(R.array.pref_support_values)
        .customView(new EditText(getActivity()), true)
        .show();
```

```groovy
    java.lang.NullPointerException: Attempt to invoke virtual method 'void  android.widget.ListView.setAdapter(android.widget.ListAdapter)' on a null object reference
            at com.afollestad.materialdialogs.MaterialDialog.invalidateList(MaterialDialog.java:146)
            at com.afollestad.materialdialogs.DialogInit.init(DialogInit.java:330)
            at com.afollestad.materialdialogs.MaterialDialog.<init>(MaterialDialog.java:84)
            at com.afollestad.materialdialogs.MaterialDialog$Builder.build(MaterialDialog.java:1031)
            at com.afollestad.materialdialogs.MaterialDialog$Builder.show(MaterialDialog.java:1035)
            at de.ph1b.audiobook.fragment.SettingsFragment$2.onPreferenceClick(SettingsFragment.java:109)
            at android.preference.Preference.performClick(Preference.java:985)
            at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:214)
            at android.widget.AdapterView.performItemClick(AdapterView.java:305)
            at android.widget.AbsListView.performItemClick(AbsListView.java:1148)
            at android.widget.AbsListView$PerformClick.run(AbsListView.java:3059)
            at android.widget.AbsListView$3.run(AbsListView.java:3866)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5293)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

**Comment by afollestad** [comment]
You can't use them together anyways but I'll prevent the crash.

**Comment by afollestad** [comment]
Btw, you're using an EditText as a custom view? Why?

**Comment by Ph1b** [comment]
Thats a placeholder. I always make a stub to see if the base works. (which didn't ;-)

**Comment by Ph1b** [comment]
Btw. if that combination is not allowed, isnt it better to throw an Exception like new IllegalArgumentException("It is not supported to use .items() combined with .customView()?
That would cause less confusion for developers. A silently failing code is always weird.

**Comment by afollestad** [comment]
You're right, https://github.com/afollestad/material-dialogs/commit/c319098bf681a0196c60fd342c9832090f33dd49 should help with that

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.3.0

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.3.1
