### ISSUE TITLE
AppCompatTextView cannot be cast to android.widget.CheckBox

### ISSUE THREAD

**Issue by smemamian** [afollestad/material-dialogs#526]
Hi

I would like to set checkbox's gravity value from default left to right using `.itemsGravity(GravityEnum.END)` and `.contentGravity(GravityEnum.END)` method, but when I call it I get these errors:

```gradle
 java.lang.ClassCastException: android.support.v7.widget.AppCompatTextView cannot be cast to android.widget.CheckBox
            at com.afollestad.materialdialogs.MaterialDialog.onItemClick(MaterialDialog.java:174)
            at android.widget.AdapterView.performItemClick(AdapterView.java:301)
            at android.widget.AbsListView.performItemClick(AbsListView.java:1519)
            at android.widget.AbsListView$PerformClick.run(AbsListView.java:3278)
            at android.widget.AbsListView$1.run(AbsListView.java:4327)
            at android.os.Handler.handleCallback(Handler.java:725)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5293)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
            at dalvik.system.NativeStart.main(Native Method)
```

```java
new MaterialDialog.Builder(getActivity())
    .title(r.getString(R.string.str_title_categories_simple_search))
    .items(array_categories)
    .itemsCallbackMultiChoice(null, new MaterialDialog.ListCallbackMultiChoice() {
        @Override
        public boolean onSelection(MaterialDialog dialog, Integer[] which, CharSequence[] text) {
            /**
             * If you use alwaysCallMultiChoiceCallback(), which is discussed below,
             * returning false here won't allow the newly selected check box to actually be selected.
             * See the limited multi choice dialog example in the sample project for details.
             **/
            return true;
        }
    })
    .itemsGravity(GravityEnum.END)
    .contentGravity(GravityEnum.END)
    .positiveText(android.R.string.ok)
    .show();
```

**Comment by afollestad** [comment]
I'll look into this.

However, I updated your comment to use correct syntax highlighting (indentation doesn't do that). I'd also recommend using string resources (like `android.R.string.ok`), because they are/can be translated.

**Comment by afollestad** [comment]
I'll try both, but I should ask to make sure: are you using a RTL language (e.g. Arabic)?

**Comment by afollestad** [comment]
You might be using an old version. The error log doesn't match up with where code actually is now.
