### ISSUE TITLE
Virtual method invoke on a null reference 

### ISSUE THREAD

**Issue by Jdruwe** [afollestad/material-dialogs#540]
I am using Otto message bus to do some background processing and when it reports back to the fragment I close the progress dialog. But it gives this error sometimes:

```
05-22 13:37:25.861    1866-1866/adevador.babysit E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: adevador.babysit, PID: 1866
    java.lang.RuntimeException: Could not dispatch event: class adevador.babysit.task.result.GeoTaskResultEvent to handler [EventHandler public void adevador.babysit.fragment.SettingsFragment.onAsyncTaskResult(adevador.babysit.task.result.AsyncTaskResultEvent)]: Attempt to invoke virtual method 'void com.afollestad.materialdialogs.MaterialDialog.hide()' on a null object reference
            at com.squareup.otto.Bus.throwRuntimeException(Bus.java:458)
            at com.squareup.otto.Bus.dispatch(Bus.java:388)
            at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:369)
            at com.squareup.otto.Bus.post(Bus.java:338)
            at adevador.babysit.task.GeoTask.onPostExecute(GeoTask.java:37)
            at adevador.babysit.task.GeoTask.onPostExecute(GeoTask.java:14)
            at android.os.AsyncTask.finish(AsyncTask.java:632)
            at android.os.AsyncTask.access$600(AsyncTask.java:177)
            at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.afollestad.materialdialogs.MaterialDialog.hide()' on a null object reference
            at adevador.babysit.fragment.SettingsFragment.onAsyncTaskResult(SettingsFragment.java:319)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.squareup.otto.EventHandler.handleEvent(EventHandler.java:89)
            at com.squareup.otto.Bus.dispatch(Bus.java:386)
            at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:369)
            at com.squareup.otto.Bus.post(Bus.java:338)
            at adevador.babysit.task.GeoTask.onPostExecute(GeoTask.java:37)
            at adevador.babysit.task.GeoTask.onPostExecute(GeoTask.java:14)
            at android.os.AsyncTask.finish(AsyncTask.java:632)
            at android.os.AsyncTask.access$600(AsyncTask.java:177)
            at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
```

Am I doing something wrong or is there a bug in the library?

**Comment by Jdruwe** [comment]
I am sorry I had nothing to do with your awesome library! I had to unregister otto in a different fragment (it was still reporting back to it and causing a nullpointer over there). Close pls
