### ISSUE TITLE
java.lang.IllegalAccessError: setContentView() is not supported in MaterialDialog. Specify a custom view in the Builder instead.

### ISSUE THREAD

**Issue by MrBrightside29** [afollestad/material-dialogs#550]
Hey Aidan,

I'm getting that error since I've uploaded to 0.7.5.0 when creating an indeterminate progress dialog like this: 
```
pd = new MaterialDialog.Builder(context)
					.cancelable(false)
					.content(R.string.action_signin)
					.progress(true, 0)
					.show();
```
I understand what it says, but I don't know if this is the intended behavior or is just a bug of the new version.

Thanks in advance.

**Comment by Ph1b** [comment]
Same for me.

````java
new MaterialDialog.Builder(getActivity())
                .title(R.string.no_audiobook_folders_title)
                .content(getString(R.string.no_audiobook_folders_summary_start) + "\n\n" +
                        getString(R.string.no_audiobook_folders_end))
                .positiveText(R.string.dialog_confirm)
                .callback(new MaterialDialog.ButtonCallback() {
                    @Override
                    public void onPositive(MaterialDialog dialog) {
                        startActivity(new Intent(getActivity(), FolderOverviewActivity.class));
                    }
                })
                .cancelable(false)
                .build();
````

````java
05-31 21:46:30.108    9504-9504/de.ph1b.audiobook.debug E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: de.ph1b.audiobook.debug, PID: 9504
    java.lang.IllegalAccessError: setContentView() is not supported in MaterialDialog. Specify a custom view in the Builder instead.
            at com.afollestad.materialdialogs.DialogBase.setContentView(DialogBase.java:56)
            at com.afollestad.materialdialogs.MaterialDialog.setContentView(MaterialDialog.java:55)
            at com.afollestad.materialdialogs.DialogBase.setViewInternal(DialogBase.java:38)
            at com.afollestad.materialdialogs.DialogInit.init(DialogInit.java:324)
            at com.afollestad.materialdialogs.MaterialDialog.<init>(MaterialDialog.java:87)
            at com.afollestad.materialdialogs.MaterialDialog$Builder.build(MaterialDialog.java:1101)
            at de.ph1b.audiobook.fragment.BookShelfFragment.onCreate(BookShelfFragment.java:219)
            at android.support.v4.app.Fragment.performCreate(Fragment.java:1766)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:917)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:551)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1236)
            at android.app.Activity.performStart(Activity.java:6006)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2319)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2418)
            at android.app.ActivityThread.access$900(ActivityThread.java:154)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5289)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
````

**Comment by Obsttube** [comment]
same for me...

**Comment by afollestad** [comment]
You guys happened to get the second iteration of version 0.7.5.0, it wasn't there the first time I pushed 0.7.5.0. I missed this bug.

Pushing 0.7.5.1 now.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.5.1

**Comment by Ph1b** [comment]
Thanks, works.
