### ISSUE TITLE
ResourceNotFoundException when method .content(R.string.content) is used

### ISSUE THREAD

**Issue by TomasValenta** [afollestad/material-dialogs#562]
```Gradle
E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: app, PID: 29737
    android.content.res.Resources$NotFoundException: String resource ID #0x0
            at android.content.res.Resources.getText(Resources.java:321)
            at android.widget.TextView.setText(TextView.java:4135)
            at com.afollestad.materialdialogs.DialogInit.init(DialogInit.java:199)
            at com.afollestad.materialdialogs.MaterialDialog.<init>(MaterialDialog.java:88)
            at com.afollestad.materialdialogs.MaterialDialog$Builder.build(MaterialDialog.java:1102)
            at com.afollestad.materialdialogs.MaterialDialog$Builder.show(MaterialDialog.java:1107)
            at app.settings.SettingsFragment$4.onPreferenceClick(SettingsFragment.java:285)
            at android.preference.Preference.performClick(Preference.java:985)
            at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:214)
            at android.widget.AdapterView.performItemClick(AdapterView.java:305)
            at android.widget.AbsListView.performItemClick(AbsListView.java:1148)
            at android.widget.AbsListView$PerformClick.run(AbsListView.java:3059)
            at android.widget.AbsListView$3.run(AbsListView.java:3866)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5289)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

**Comment by afollestad** [comment]
That's not an issue with this library, this is from this line: 

https://github.com/afollestad/material-dialogs/blob/master/library/src/main/java/com/afollestad/materialdialogs/MaterialDialog.java#L614

This exception means the string you specified doesn't exist when retrieved using the context you passed to the `Builder`.

**Comment by afollestad** [comment]
Which means you need to clean and rebuild your project most likely. This is a very common Android error.

**Comment by TomasValenta** [comment]
Are you sure? Beacause with version 0.7.5.3 my dialogs works and with 0.7.5.4 not. Clean and rebuild completed...

**Comment by afollestad** [comment]
I haven't changed anything within the `content` method since the very first release of the library.

But yeah, that line is made up of 100% Android framework methods.

**Comment by afollestad** [comment]
Well wait, I don't think it's directly related to the `content` method.

It looks like it might be from the preference classes.

**Comment by TomasValenta** [comment]
It also crashing from non preference classes.

**Comment by TomasValenta** [comment]
Rolling back to 0.7.5.3 and dialogs working again.

**Comment by TomasValenta** [comment]
When switching between versions, clean and rebuild executed.

**Comment by afollestad** [comment]
Found the issue

**Comment by afollestad** [comment]
Thanks for reporting this, more people would've discovered it if it was out there for any longer.

https://github.com/afollestad/material-dialogs/releases/tag/v0.7.5.5

**Comment by TomasValenta** [comment]
You're welcome, now it's working, thank you too.
