### ISSUE TITLE
android:paddingStart attribute without API level qualifier caused crashes on some API < 17 devices

### ISSUE THREAD

**Issue by yukuku** [afollestad/material-dialogs#589]
In files like `library/src/main/res/layout/md_listitem_singlechoice.xml`

There is a `android:paddingStart` attribute, that looks harmless. But actually it's not harmless, that's why lint warns us that that attribute should not be used unless you put the xml file inside the `-v17` qualifier.

The reference is this bug: https://code.google.com/p/android/issues/detail?id=60055

In my app, which uses material-dialogs, there has been around 30 reports of crashes with the following stack traces:

    android.view.InflateException: Binary XML file line #23: Error inflating class TextView
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:710)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
    at android.view.LayoutInflater.inflate(Native Method)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
    at android.widget.ArrayAdapter.createViewFromResource(ArrayAdapter.java:371)
    at android.widget.ArrayAdapter.getView(ArrayAdapter.java:362)
    at com.afollestad.materialdialogs.MaterialDialogAdapter.getView(Somewhere:45)
    at android.widget.AbsListView.obtainView(AbsListView.java:2472)
    at android.widget.ListView.measureHeightOfChildren(ListView.java:1250)
    at android.widget.ListView.onMeasure(ListView.java:1162)
    at android.view.View.measure(View.java:15562)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5107)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
    at android.view.View.measure(View.java:15562)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5107)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1396)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:681)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:574)
    at android.view.View.measure(View.java:15562)
    at com.afollestad.materialdialogs.internal.MDRootLayout.onMeasure(Somewhere:194)
    at android.view.View.measure(View.java:15562)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5107)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
    at android.view.View.measure(View.java:15562)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5107)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1396)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:681)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:574)
    at android.view.View.measure(View.java:15562)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5107)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
    at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2423)
    at android.view.View.measure(View.java:15562)
    at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2031)
    at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1224)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1425)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1142)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4709)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
    at android.view.Choreographer.doCallbacks(Choreographer.java:555)
    at android.view.Choreographer.doFrame(Choreographer.java:525)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
    at android.os.Handler.handleCallback(Handler.java:615)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4947)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    at dalvik.system.NativeStart.main(Native Method)
    Caused by: java.lang.NumberFormatException: Invalid int: "6.0dip"
    at java.lang.Integer.invalidInt(Integer.java:138)
    at java.lang.Integer.parse(Integer.java:375)
    at java.lang.Integer.parseInt(Integer.java:366)
    at com.android.internal.util.XmlUtils.convertValueToInt(XmlUtils.java:123)
    at android.content.res.TypedArray.getInt(TypedArray.java:254)
    at android.content.res.XResources$XTypedArray.getInt(XResources.java:1002)
    at android.widget.TextView.<init>(TextView.java:1072)
    at android.support.v7.widget.AppCompatTextView.<init>(Somewhere:44)
    at android.support.v7.widget.AppCompatTextView.<init>(Somewhere:40)
    at android.support.v7.internal.app.AppCompatViewInflater.createView(Somewhere:99)
    at android.support.v7.app.AppCompatDelegateImplV7.createView(Somewhere:782)
    at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(Somewhere:810)
    at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(Somewhere:44)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:681)
    ... 54 more

The solution should be removing the `android:paddingStart` from the file mentioned above and similar files, and use the `-ldrtl` qualifier to support RTL.

**Comment by yukuku** [comment]
By the way, you can't test this on an emulator, because this is caused by unspecified behavior on older Android versions. Prior to 4.2 (I think), Google didn't disallow OEMs to add their own attributes. Hence, paddingStart was mapped to some manufacturer-specific attributes that expects an int value, that's why it crashes when parsing '6.0dip'.

The crash report of my app from Google Play shows me 2 devices with this behavior:

* Galaxy Tab 7.7 (GT-P6810) Android 4.1
* Galaxy Note 10.1 (p4noterf) Android 4.1

**Comment by Sivanga** [comment]
Same here - about 160 crashes only for the latest version. 
For now we don't use this library for devices with Samsung brand.

**Comment by hzsweers** [comment]
This isn't a bug as much as it is yet another issue with samsung. Google should be helping us here though, IIRC build tools 22+ automatically fixes this in layout files by removing `paddingStart` attributes in the main file and creating copies of them in `-v17` resource directories where that attribute is safe to use. @yukuku @Sivanga what build tools versions are you using?

**Comment by Sivanga** [comment]
@hzsweers We are using buildTools version 21.1.1

**Comment by hzsweers** [comment]
Ah, yeah I believe you'll solve your problem when you update to 22.0.1.

**Comment by yukuku** [comment]
I see, I was also using build tools 21.1.2. I didn't know build tools 22+ removes paddingStart attributes etc. Any reference on the web?

**Comment by hzsweers** [comment]
No official references (classic Google...), but a redditor and I talked and confirmed it when I [posted about it awhile back](https://www.reddit.com/r/androiddev/comments/3037ba/does_build_tools_2201_the_latest_bloat_anyone/cpovwah).

Basically any xml file that has one of those problematic attributes gets copied completely into a new file under `-v17` and the attributes are removed in the original file.

**Comment by Sivanga** [comment]
I'll check , thanks!

**Comment by yukuku** [comment]
@hzsweers  Thanks! Confirmed with building material-dialogs with Build Tools 22.0.1:

    	   android:paddingStart="@dimen/md_listitem_control_margin"

does not appear in `layout/md_listitem_singlechoice.xml`, and then a copy of the original file is generated at `layout-v17` folder. 

Same with the original `layout-ldrtl` variant — the original is automatically located at `layout-ldrtl-v17`, and the one without the `paddingStart` is at `layout-ldrtl` folder.

**Comment by hzsweers** [comment]
Cool! Glad that worked. I think it's probably best to just close this since
the solution is a build tools version. 22 has been out for awhile, so
hopefully people can update to it soon enough.
