### ISSUE TITLE
Issue with extending the MaterialDialogPreference

### ISSUE THREAD

**Issue by adaneam** [afollestad/material-dialogs#600]
I have a custom NumberPickerPreference which was extended from DialogPreference. 
`public class NumberPickerPreference extends DialogPreference`
It was working fine. But when I extend it from MaterialDialogPreference, I get a runtime exception
`public class NumberPickerPreference extends MaterialDialogPreference`

```
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.app.AlertDialog$Builder.getContext()' on a null object reference
            at android.preference.DialogPreference.onCreateDialogView(DialogPreference.java:357)
            at com.afollestad.materialdialogs.prefs.MaterialDialogPreference.showDialog(MaterialDialogPreference.java:61)
            at android.preference.DialogPreference.onClick(DialogPreference.java:274)
            at android.preference.Preference.performClick(Preference.java:983)
            at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:214)
            at android.widget.AdapterView.performItemClick(AdapterView.java:300)
            at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
            at android.widget.AbsListView$PerformClick.run(AbsListView.java:3046)
            at android.widget.AbsListView$3.run(AbsListView.java:3835)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
```

Any idea how to solve this?

**Comment by SimonKinds** [comment]
NOTE: I'm far from an Android wizard, so excuse me if I'm wrong.

I've gone through the source of DialogPreference and it seems that the object that you're getting a NullPointerException from is the mBuilder object. This object is only instantiated in the DialogPreference.showDialog() method, which means that I'll always be null when calling onCreateDialogView(). 

This is the code of DialogPreference.onCreateDialogView():
```
protected View onCreateDialogView() {
        if (mDialogLayoutResId == 0) {
            return null;
        }
        
        LayoutInflater inflater = LayoutInflater.from(mBuilder.getContext());
        return inflater.inflate(mDialogLayoutResId, null);
}
```

My example solution would be to override the DialogPreference.onCreateDialogView() in your NumberPickerPreference class like this:
```
@Override
protected View onCreateDialogView() {
     if(getDialogLayoutResource() == 0)
             return null;

     //getContext() is a method from Preference so there should be no problem using it here
     LayoutInflater inflater = LayoutInflater.from(getContext());
     return inflater.inflate(getDialogLayoutResource(), null);
}
```

NOTE 2: The source code of DialogPreference that I looked through does not seem to be the same one you're using (which I noted thanks to line numbering). Hopefully this works though.

**Comment by adaneam** [comment]
Thanks it worked :)
