### ISSUE TITLE
illegalStateException App Crashes on Creating a new dialog

### ISSUE THREAD

**Issue by taimur97** [afollestad/material-dialogs#613]
I am showing the dialog with an editText field. If I click the cancel button in the dialog and then try to again show the dialog by creating a new dialog the app crashes

```java
  LinearLayout.LayoutParams lp = new LinearLayout.LayoutParams(
                LinearLayout.LayoutParams.WRAP_CONTENT,
                LinearLayout.LayoutParams.WRAP_CONTENT);
        input.setLayoutParams(lp);
        floating_button = (FloatingActionButton) findViewById(R.id.fab_pick_album);
        floating_button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                new MaterialDialog.Builder(MainActivity.this)
                        .title(getString(R.string.new_album_dialog_title))
                        .positiveText(R.string.agree)
                        .negativeText(R.string.disagree)
                        .customView(input, true)
                        .callback(new MaterialDialog.ButtonCallback() {
                            @Override
                            public void onPositive(MaterialDialog dialog) {
                                super.onPositive(dialog);

                            }
                        })
                        .show();
                Toast.makeText(MainActivity.this, "OnClicked", Toast.LENGTH_SHORT).show();

            }
        });
        if (value_addes == true) {
            initValues();
        } else {
            new MaterialDialog.Builder(MainActivity.this)
                    .title(getString(R.string.new_album_dialog_title))
                    .positiveText(R.string.agree)
                    .negativeText(R.string.disagree)
                    .customView(input, true)
                    .callback(new MaterialDialog.ButtonCallback() {


                        @Override
                        public void onPositive(MaterialDialog dialog) {
                            super.onPositive(dialog);

                            Intent i = new Intent(MainActivity.this, Photos.class);
                            i.putExtra("album_title", input.getText().toString());
                            i.putExtra(ViewPhotos.CREATE_NEW_ALBUM_EXTRA, true);
                            Toast.makeText(MainActivity.this,input.getText().toString(), Toast.LENGTH_SHORT).show();
                            startActivity(i);
                      

                        }
```

Log: 
```Gradle
19:44:17 E AndroidRuntime : FATAL EXCEPTION: main

19:44:17 E AndroidRuntime : java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.

19:44:17 E AndroidRuntime : at android.view.ViewGroup.addViewInner(ViewGroup.java:3506)

19:44:17 E AndroidRuntime : at android.view.ViewGroup.addView(ViewGroup.java:3377)

19:44:17 E AndroidRuntime : at android.widget.ScrollView.addView(ScrollView.java:262)

19:44:17 E AndroidRuntime : at android.view.ViewGroup.addView(ViewGroup.java:3353)

19:44:17 E AndroidRuntime : at android.widget.ScrollView.addView(ScrollView.java:253)

19:44:17 E AndroidRuntime : at com.afollestad.materialdialogs.DialogInit.init(DialogInit.java:322)

19:44:17 E AndroidRuntime : at com.afollestad.materialdialogs.MaterialDialog.<init>(MaterialDialog.java:89)

19:44:17 E AndroidRuntime : at com.afollestad.materialdialogs.MaterialDialog$Builder.build(MaterialDialog.java:1153)

19:44:17 E AndroidRuntime : at com.afollestad.materialdialogs.MaterialDialog$Builder.show(MaterialDialog.java:1158)

19:44:17 E AndroidRuntime : at com.sample.exampe.MainActivity$1.onClick(MainActivity.java:85)

19:44:17 E AndroidRuntime : at android.view.View.performClick(View.java:4240)

19:44:17 E AndroidRuntime : at android.view.View$PerformClick.run(View.java:17721)

19:44:17 E AndroidRuntime : at android.os.Handler.handleCallback(Handler.java:730)

19:44:17 E AndroidRuntime : at android.os.Handler.dispatchMessage(Handler.java:92)

19:44:17 E AndroidRuntime : at android.os.Looper.loop(Looper.java:137)

19:44:17 E AndroidRuntime : at android.app.ActivityThread.main(ActivityThread.java:5103)

19:44:17 E AndroidRuntime : at java.lang.reflect.Method.invokeNative(Native Method)

19:44:17 E AndroidRuntime : at java.lang.reflect.Method.invoke(Method.java:525)

19:44:17 E AndroidRuntime : at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)

19:44:17 E AndroidRuntime : at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)

19:44:17 E AndroidRuntime : at dalvik.system.NativeStart.main(Native Method)
```

**Comment by afollestad** [comment]
This is because you're re-using the same `EditText` for both dialogs. It belongs to the previous layout when it's added to the new one.

**Comment by taimur97** [comment]
I tried creating two edittext views for two dialogs but if I click the cancel button and recreate the dialog the error is show again.
I solved it by creating a layout for edittext and setting it as the view.

**Comment by afollestad** [comment]
If you're manually inflating the View that's used as a custom view, the views aren't gonna change when the dialog shows again. That's not even a bug, that's how things work.

**Comment by afollestad** [comment]
Just like with a ListView or RecyclerView adapter, you have to reset the views to their default state before you show the dialog again.
