### ISSUE TITLE
MD does not work in Genymotions

### ISSUE THREAD

**Issue by paularodriguez** [afollestad/material-dialogs#615]
Hi! I'm working with MD using a Genymotions simulator. My application breaks when needs some components.

Here is the stack trace:

```Gradle
 java.lang.NullPointerException: Attempt to invoke virtual method 'void com.gc.materialdesign.views.ProgressBarCircularIndeterminate.setVisibility(int)' on a null object reference
            at fragments.DetallePreguntaFragment$5.onClick(DetallePreguntaFragment.java:236)
            at android.view.View.performClick(View.java:4756)
            at android.view.View$PerformClick.run(View.java:19749)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by afollestad** [comment]
It works fine for me in Genymotion, but I'll look into it

**Comment by AzureusSme** [comment]
It works fine with me too.

**Comment by afollestad** [comment]
I'm guessing it's an issue with your custom `DialogFragment` code
