### ISSUE TITLE
Erros messages from Android Studio if use MaterialDialog

### ISSUE THREAD

**Issue by MrThiago** [afollestad/material-dialogs#627]
When I use your MaterialDialog, I am getting error message :

-----------
private void createProgressDialog() {

        dialog = new MaterialDialog.Builder(LandingActivity.this)
                .title(getString(R.string.loading))
                .content(R.string.please_wait)
                .progress(true, 0)
                .progressIndeterminateStyle(true)
                .show();
    }
---------

I get these Error messages in Android Studio:

------------
E/WindowManager﹕ android.view.WindowLeaked: Activity MyApp.activity.LandingActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{3c2db487 V.E..... R......D 0,0-684,381} that was originally added here
            at android.view.ViewRootImpl.<init>(ViewRootImpl.java:479)
            at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:277)
            at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
            at android.app.Dialog.show(Dialog.java:312)
            at com.afollestad.materialdialogs.MaterialDialog.show(MaterialDialog.java:1168)
            at com.afollestad.materialdialogs.MaterialDialog$Builder.show(MaterialDialog.java:1159)

-----------

**Comment by afollestad** [comment]
That's not an issue with this library. You need to dismiss any dialogs when your Activity pauses. Use a DialogFragment to wrap MaterialDialog in order to survive orientation changes.

**Comment by MrThiago** [comment]
thank you.
