### ISSUE TITLE
NPE on Custom Dialog View

### ISSUE THREAD

**Issue by mrkhozam** [afollestad/material-dialogs#628]
Ever since I updated from an older version (0.6.7.4) to the newest one in gradle (0.7.6.0), I've been getting a problem launching a dialog with my custom view. It works fine on the old version, and the minute I update my gradle, the dialog refuses to display and my app freezes.

Here is the code I'm using to inflate and launch the dialog:
```Java
final View dialogView = getLayoutInflater().inflate(R.layout.customview, 
    (ViewGroup) v.getParent(), false);
final MaterialDialog mdb = new MaterialDialog.Builder(getActivity())
                    .customView(dialogView, false)
                    .negativeText(R.string.dialog_cancel)
                    .cancelable(false)
                    .title(dialogTitle)
                    .build();
// Some code here to initialize elements
mdb.show();
```

And this is the stacktrace:
```Java
07-25 16:36:26.667  16334-16334/com.mrkhozam.myapp W/System.err﹕ java.lang.NullPointerException: Attempt to invoke virtual method 'int android.support.v7.widget.RecyclerView$Adapter.getItemCount()' on a null object reference
07-25 16:36:26.668  16334-16334/com.mrkhozam.myapp W/System.err﹕ at com.afollestad.materialdialogs.internal.MDRootLayout.canRecyclerViewScroll(MDRootLayout.java:489)
07-25 16:36:26.669  16334-16334/com.mrkhozam.myapp W/System.err﹕ at com.afollestad.materialdialogs.internal.MDRootLayout.setUpDividersVisibility(MDRootLayout.java:412)
07-25 16:36:26.669  16334-16334/com.mrkhozam.myapp W/System.err﹕ at com.afollestad.materialdialogs.internal.MDRootLayout.setUpDividersVisibility(MDRootLayout.java:419)
07-25 16:36:26.669  16334-16334/com.mrkhozam.myapp W/System.err﹕ at com.afollestad.materialdialogs.internal.MDRootLayout.setUpDividersVisibility(MDRootLayout.java:422)
07-25 16:36:26.670  16334-16334/com.mrkhozam.myapp W/System.err﹕ at com.afollestad.materialdialogs.internal.MDRootLayout.setUpDividersVisibility(MDRootLayout.java:419)
07-25 16:36:26.670  16334-16334/com.mrkhozam.myapp W/System.err﹕ at com.afollestad.materialdialogs.internal.MDRootLayout.onLayout(MDRootLayout.java:343)
07-25 16:36:26.670  16334-16334/com.mrkhozam.myapp W/System.err﹕ at android.view.View.layout(View.java:15678)
07-25 16:36:26.670  16334-16334/com.mrkhozam.myapp W/System.err﹕ at android.view.ViewGroup.layout(ViewGroup.java:5039)
07-25 16:36:26.670  16334-16334/com.mrkhozam.myapp W/System.err﹕ at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
07-25 16:36:26.675  16334-16334/com.mrkhozam.myapp W/System.err﹕ at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
07-25 16:36:26.675  16334-16334/com.mrkhozam.myapp W/System.err﹕ at android.view.View.layout(View.java:15678)
07-25 16:36:26.675  16334-16334/com.mrkhozam.myapp W/System.err﹕ at android.view.ViewGroup.layout(ViewGroup.java:5039)
07-25 16:36:26.676  16334-16334/com.mrkhozam.myapp W/System.err﹕ at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
07-25 16:36:26.676  16334-16334/com.mrkhozam.myapp W/System.err﹕ at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
07-25 16:36:26.676  16334-16334/com.mrkhozam.myapp W/System.err﹕ at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
07-25 16:36:26.678  16334-16334/com.mrkhozam.myapp W/System.err﹕ at android.view.View.layout(View.java:15678)
07-25 16:36:26.678  16334-16334/com.mrkhozam.myapp W/System.err﹕ at android.view.ViewGroup.layout(ViewGroup.java:5039)
07-25 16:36:26.678  16334-16334/com.mrkhozam.myapp W/System.err﹕ at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
07-25 16:36:26.679  16334-16334/com.mrkhozam.myapp W/System.err﹕ at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
07-25 16:36:26.679  16334-16334/com.mrkhozam.myapp W/System.err﹕ at android.view.View.layout(View.java:15678)
07-25 16:36:26.679  16334-16334/com.mrkhozam.myapp W/System.err﹕ at android.view.ViewGroup.layout(ViewGroup.java:5039)
07-25 16:36:26.679  16334-16334/com.mrkhozam.myapp W/System.err﹕ at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
07-25 16:36:26.679  16334-16334/com.mrkhozam.myapp W/System.err﹕ at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
07-25 16:36:26.679  16334-16334/com.mrkhozam.myapp W/System.err﹕ at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
07-25 16:36:26.679  16334-16334/com.mrkhozam.myapp W/System.err﹕ at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5891)
07-25 16:36:26.679  16334-16334/com.mrkhozam.myapp W/System.err﹕ at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
07-25 16:36:26.679  16334-16334/com.mrkhozam.myapp W/System.err﹕ at android.view.Choreographer.doCallbacks(Choreographer.java:580)
07-25 16:36:26.679  16334-16334/com.mrkhozam.myapp W/System.err﹕ at android.view.Choreographer.doFrame(Choreographer.java:550)
07-25 16:36:26.679  16334-16334/com.mrkhozam.myapp W/System.err﹕ at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
07-25 16:36:26.679  16334-16334/com.mrkhozam.myapp W/System.err﹕ at android.os.Handler.handleCallback(Handler.java:739)
07-25 16:36:26.679  16334-16334/com.mrkhozam.myapp W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:95)
07-25 16:36:26.679  16334-16334/com.mrkhozam.myapp W/System.err﹕ at android.os.Looper.loop(Looper.java:135)
07-25 16:36:26.679  16334-16334/com.mrkhozam.myapp W/System.err﹕ at android.app.ActivityThread.main(ActivityThread.java:5289)
07-25 16:36:26.679  16334-16334/com.mrkhozam.myapp W/System.err﹕ at java.lang.reflect.Method.invoke(Native Method)
07-25 16:36:26.679  16334-16334/com.mrkhozam.myapp W/System.err﹕ at java.lang.reflect.Method.invoke(Method.java:372)
07-25 16:36:26.682  16334-16334/com.mrkhozam.myapp W/System.err﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
07-25 16:36:26.682  16334-16334/com.mrkhozam.myapp W/System.err﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

It's possible that something in the updated API version has a bug with RecyclerView?

Thank you for this brilliant mod.

**Comment by afollestad** [comment]
Well, first of all, the latest version on Cradle is 0.7.7.0. 

Does your custom layout have a RecyclerView in it? It looks like the library is trying to check if your RecyclerView is empty or not but there's no adapter attached to it.

**Comment by mrkhozam** [comment]
My mistake about the latest version. I just updated gradle with it, but it still produces the same error.

After seeing your insight, I tried setting an empty adapter (which is weird because I still set the dataset object to null) right after initializing the RecyclerView, like so:

```Java
mRecyclerViewMyList = (RecyclerView) dialogView.findViewById(R.id.mylist);
mRecyclerViewMyList.setLayoutManager(new LinearLayoutManager(getActivity()));
mAdapterMyList = new MyListAdapter(null, R.layout.mylist_row, getActivity());
```

And sure enough, this solved the problem. I apologize for the bother, but I never thought I had to set an adapter right after I inflate a RecyclerView. Usually since I have multiple conditions to check before doing so, I never set an empty adapter.

**Comment by afollestad** [comment]
I'll have it fixed for the next release ☺

**Comment by mrkhozam** [comment]
Thank you, sir!

**Comment by afollestad** [comment]
You're welcome!
