### ISSUE TITLE
Simple Dialogs (Guidelines spec) crashes on RTL languages (Arabic)

### ISSUE THREAD

**Issue by akbarsha03** [afollestad/material-dialogs#693]
Please check your sample app. To reproduce the error change the device language to **Arabic** then tab on **Simple Dialogs (Guidelines spec)** da!da! crash. 

Android Device doesn't flip the **MaterialSimpleListAdapter**'s layout for RTL language which causes the error.

**Crash log:**

```Gradle
java.lang.ClassCastException: android.widget.ImageView cannot be cast to android.widget.CompoundButton
           at com.afollestad.materialdialogs.simplelist.MaterialSimpleListAdapter.setupGravity(MaterialSimpleListAdapter.java:89)
           at com.afollestad.materialdialogs.simplelist.MaterialSimpleListAdapter.getView(MaterialSimpleListAdapter.java:64)
           at android.widget.AbsListView.obtainView(AbsListView.java:2347)
           at android.widget.ListView.measureHeightOfChildren(ListView.java:1270)
           at android.widget.ListView.onMeasure(ListView.java:1182)
           at android.view.View.measure(View.java:17547)
           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
           at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
           at android.view.View.measure(View.java:17547)
           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
           at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
           at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
           at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
           at android.view.View.measure(View.java:17547)
           at com.afollestad.materialdialogs.internal.MDRootLayout.onMeasure(MDRootLayout.java:199)
           at android.view.View.measure(View.java:17547)
           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
           at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
           at android.view.View.measure(View.java:17547)
           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
           at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
           at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
           at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
           at android.view.View.measure(View.java:17547)
           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
           at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
           at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2615)
           at android.view.View.measure(View.java:17547)

```

My workaround to fix this issue is I have set the **itemsGravity()** to **Gravity.END** which made the crash gone but the **MaterialDialog**'s **MaterialSimpleListAdapter's** items are supposed to appear from Right to Left which looks uglier on RTL.

**Comment by afollestad** [comment]
Looking into it now. I should note you don't need to switch device languages to Arabic in order to test RTL, there's a "Force RTL Layout" option in the Developer Options.

**Comment by akbarsha03** [comment]
Even if I set the "Force RTL Layout" in Developer option still it is crashing. @afollestad

**Comment by afollestad** [comment]
I know, that's expected.

**Comment by akbarsha03** [comment]
@afollestad Yep, Apart from Activity layout android doesn't flip the layout for dialogs I guess

**Comment by afollestad** [comment]
Fixed for the next release.

**Comment by akbarsha03** [comment]
Thank you @afollestad :+1: :smiley: Waiting for the update.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.0.1

**Comment by akbarsha03** [comment]
@afollestad Thank you. Got the update :smile:

**Comment by afollestad** [comment]
You're welcome 😀
