### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by RubenGees** [afollestad/material-dialogs#700]
Hi, On some devices the following Error occures:

```java
java.lang.NoSuchMethodError: com.afollestad.materialdialogs.internal.a.r.getLayoutDirection
       at com.afollestad.materialdialogs.internal.progress.ProgressDrawableBase.needMirroring(ProgressDrawableBase.java:1122)
       at com.afollestad.materialdialogs.internal.progress.IndeterminateProgressDrawableBase.draw(IndeterminateProgressDrawableBase.java:27)
       at com.afollestad.materialdialogs.internal.progress.IndeterminateProgressDrawable.draw(IndeterminateProgressDrawable.java:18)
       at android.widget.ProgressBar.onDraw(ProgressBar.java:1069)
```

It looks like a Proguard Issue (I have it enabled for release builds), but I couldn't find specific Proguard rules for this lib.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.0.1
