### ISSUE TITLE
accentMode Exception

### ISSUE THREAD

**Issue by marbat87** [afollestad/material-dialogs#771]
Hi,

with version 0.8.4.2 I get an exception when setting `allowUserColorInput` to false in a accentMode `ColorChooserDialog`.

If I set `allowUserColorInput` to true, it works.

Below my code:

```java
new ColorChooserDialog.Builder((MainActivity) getActivity(), R.string.accent_color)
    .allowUserColorInput(false)
    .customColors(ColorPalette.ACCENT_COLORS, ColorPalette.ACCENT_COLORS_SUB)
    .accentMode(true)  // optional boolean, true shows accent palette
    .doneButton(R.string.single_choice_ok)  // changes label of the done button
    .cancelButton(R.string.cancel)  // changes label of the cancel button
    .backButton(R.string.dialog_back)  // changes label of the back button
    .preselect(getThemeUtils().accentColor())  // optional color int, preselects a color
    .show();
```

and the exception:

```Gradle
10-19 12:55:52.556 12827-12827/it.cammino.risuscito E/AndroidRuntime: FATAL EXCEPTION: main
10-19 12:55:52.556 12827-12827/it.cammino.risuscito E/AndroidRuntime: Process: it.cammino.risuscito, PID: 12827
10-19 12:55:52.556 12827-12827/it.cammino.risuscito E/AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
10-19 12:55:52.556 12827-12827/it.cammino.risuscito E/AndroidRuntime:     at com.afollestad.materialdialogs.color.ColorChooserDialog.toggleCustom(ColorChooserDialog.java:351)
10-19 12:55:52.556 12827-12827/it.cammino.risuscito E/AndroidRuntime:     at com.afollestad.materialdialogs.color.ColorChooserDialog.onCreateDialog(ColorChooserDialog.java:337)
10-19 12:55:52.556 12827-12827/it.cammino.risuscito E/AndroidRuntime:     at android.support.v4.app.DialogFragment.getLayoutInflater(DialogFragment.java:308)
10-19 12:55:52.556 12827-12827/it.cammino.risuscito E/AndroidRuntime:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1078)
10-19 12:55:52.556 12827-12827/it.cammino.risuscito E/AndroidRuntime:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1259)
10-19 12:55:52.556 12827-12827/it.cammino.risuscito E/AndroidRuntime:     at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
10-19 12:55:52.556 12827-12827/it.cammino.risuscito E/AndroidRuntime:     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1624)
10-19 12:55:52.556 12827-12827/it.cammino.risuscito E/AndroidRuntime:     at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
10-19 12:55:52.556 12827-12827/it.cammino.risuscito E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:739)
10-19 12:55:52.556 12827-12827/it.cammino.risuscito E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
10-19 12:55:52.556 12827-12827/it.cammino.risuscito E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135)
10-19 12:55:52.556 12827-12827/it.cammino.risuscito E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5254)
10-19 12:55:52.556 12827-12827/it.cammino.risuscito E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
10-19 12:55:52.556 12827-12827/it.cammino.risuscito E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
10-19 12:55:52.556 12827-12827/it.cammino.risuscito E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
10-19 12:55:52.556 12827-12827/it.cammino.risuscito E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

Thanks in advance.

Marcello

**Comment by afollestad** [comment]
I'll look into it.

By the way, I updated your comment for syntax highlighting. Markdown is better than HTML 😉

**Comment by marbat87** [comment]
Thank you very much ;)

Is there an OTA for the release?

Regards,
Marcello

**Comment by afollestad** [comment]
Since I'm using JitPack, you can get it now using the commit ID:

```Gradle
dependencies {

    // ... other dependencies here
    compile('com.afollestad.material-dialogs:core:68fd646664@aar') {
        transitive = true
    }
    compile('com.afollestad.material-dialogs:commons:68fd646664@aar') {
        transitive = true
    }
}
```
