### ISSUE TITLE
Unable to have nothing selected after multi select dialog appears

### ISSUE THREAD

**Issue by gintechsystems** [afollestad/material-dialogs#797]
Hello,

I am having an issue when after showing the dialog and items are selected, if you deselect them all and tap the positive button it crashes with an `ArrayOutOfBoundsException`.

Here is my code and the error.

```Gradle
10-28 12:55:38.164 24908-24908/com.droid.visneta E/AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=6; index=-1
10-28 12:55:38.164 24908-24908/com.droid.visneta E/AndroidRuntime:     at com.afollestad.materialdialogs.MaterialDialog.sendMultichoiceCallback(MaterialDialog.java:324)
10-28 12:55:38.164 24908-24908/com.droid.visneta E/AndroidRuntime:     at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:343)
```

```java
final MaterialDialog.Builder builder = new MaterialDialog.Builder(getContext())
    .widgetColor(AppUtils.getColor(visnetawrap, R.color.dark_blue))
    .positiveText("Submit")
    .positiveColor(AppUtils.getColor(visnetawrap, R.color.dark_blue))
    .negativeText("Cancel")
    .negativeColor(AppUtils.getColor(visnetawrap, R.color.dark_blue))
    .typeface(visnetawrap.helveticaBoldFont, visnetawrap.helveticaLightFont)
    .items(formElementHolder.formMultiSpinner.itemsList.toArray(new String[formElementHolder.formMultiSpinner.itemsList.size()]))
    .itemsCallbackMultiChoice(formElementHolder.formMultiSpinner.selectedItemIndexes, 
            new MaterialDialog.ListCallbackMultiChoice() {
                @Override
                public boolean onSelection(MaterialDialog materialDialog, Integer[] integers, CharSequence[] charSequences) {
                        formElementHolder.formMultiSpinner.selectedItemIndexes = integers;
                        formElementHolder.formMultiSpinner.selectedItems.clear();
                        for (CharSequence charSequence : charSequences) {
                                formElementHolder.formMultiSpinner.selectedItems.add(charSequence.toString());
                        }
                        formElementHolder.formMultiSpinner.updateSelection();
                        if (charSequences.length == 0) {
                                objectItem.setQuestionAnswer("");
                        } else {
                                objectItem.setQuestionAnswer(formElementHolder.formMultiSpinner.buildSelectedItemString());
                        }
                        visnetawrap.smartFormAct.updateSaveFormButton();
                        return true;
            }
    }).show();
```

**Comment by afollestad** [comment]
I updated your comment for correct spacing and syntax highlighting. Please do so for any future issues, otherwise it's hard to read.

---

The line numbers in the crash log don't match up with anything in the current codebase, which would suggest you're using an old version.

**Comment by afollestad** [comment]
And there is not any code in `sendMultichoiceCallback()` that would cause this kind of error internally, so there must be something about the array you pass in that causes the issue.

**Comment by gintechsystems** [comment]
I am using 0.8.4.2, that is the latest?

**Comment by gintechsystems** [comment]
Hmmm ok I will look into it more myself, thanks.

**Comment by afollestad** [comment]
The line numbers are probably off because code has changed in the repository which hasn't been released yet.

The only thing that I think could cause this is if the `.items()` array got out of sync with what is selected. `sendMultichoiceCallback()` looks like this:

```
private boolean sendMultichoiceCallback() {
    if (mBuilder.listCallbackMultiChoice == null) return false;
    Collections.sort(selectedIndicesList); // make sure the indicies are in order
    List<CharSequence> selectedTitles = new ArrayList<>();
    for (Integer i : selectedIndicesList) {
        selectedTitles.add(mBuilder.items[i]);   // the error is probably here
    }
    return mBuilder.listCallbackMultiChoice.onSelection(this,
            selectedIndicesList.toArray(new Integer[selectedIndicesList.size()]),
            selectedTitles.toArray(new CharSequence[selectedTitles.size()]));
}
```

But I've had any issues with that, so I'm assuming your array gets modified after the dialog is open or something.

**Comment by gintechsystems** [comment]
Is it possible to pass empty selected indexes? I think I may be passing -1 and it is crashing. Also sorry about the syntax highlighting, I am new to github comments still.

**Comment by afollestad** [comment]
Yeah, like the README shows in the [Multi Choice List Dialogs section](https://github.com/afollestad/material-dialogs#multi-choice-list-dialogs), you pass `null` to indicate no preselection. -1 for single choice lists.

**Comment by afollestad** [comment]
And no worries, there's a lot of cool stuff you can do with Markdown on GitHub 😀

**Comment by afollestad** [comment]
Ohhh, so you were passing -1 inside an Integer array there? That makes a lot more sense.

**Comment by gintechsystems** [comment]
Yeah that is the issue, I didn't realize you could pass null. I am used to using -1 :P thank you for the help!

**Comment by afollestad** [comment]
Glad I could help!
