### ISSUE TITLE
java.lang.NoClassDefFoundError when showing Indeterminate Progress Dialogs

### ISSUE THREAD

**Issue by filipebezerra** [afollestad/material-dialogs#819]
I'm using:
* material-dialogs:core:0.8.5.0
* material-dialogs:commons:0.8.5.0

My app works with:
* build tools 23.0.1
* min sdk version 9
* target sdk version 23

When I call:

```java
mProgressDialog = new MaterialDialog.Builder(getActivity())
    .title(R.string.title)
    .content(R.string.content)
    .cancelable(false)
    .progress(true, 0)
    .show();
```

I'm getting the exception:

```Gradle
java.lang.NoClassDefFoundError: Failed resolution of: Lme/zhanghai/android/materialprogressbar/IndeterminateProgressDrawable;
    at com.afollestad.materialdialogs.DialogInit.setupProgressDialog(DialogInit.java:368)
    at com.afollestad.materialdialogs.DialogInit.init(DialogInit.java:298)
    at com.afollestad.materialdialogs.MaterialDialog.<init>(MaterialDialog.java:94)
    at com.afollestad.materialdialogs.MaterialDialog$Builder.build(MaterialDialog.java:1289)
    at com.afollestad.materialdialogs.MaterialDialog$Builder.show(MaterialDialog.java:1294)
...
Caused by: java.lang.ClassNotFoundException: Didn't find class "me.zhanghai.android.materialprogressbar.IndeterminateProgressDrawable" on path: DexPathList[[zip file "/data/app/br.com.hojeti.leiturafacil.android-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
...
```
Why I'm getting this exception? 

I know that the core module have the [MaterialProgressBar](https://github.com/DreaminginCodeZH/MaterialProgressBar) in the [dependencies](https://github.com/afollestad/material-dialogs/blob/master/core/build.gradle#L29).

Also, when I run ```gradle -q dependencies``` in my app module, I can't see any MaterialProgressBar dependency in the Material Dialogs Core module.

For now, I include the dependency ```me.zhanghai.android.materialprogressbar:library:1.1.4``` in my build.gradle to fix the exception.

**Comment by alexwhb** [comment]
I am getting this exception too.

**Comment by afollestad** [comment]
Hmmm, this should never happen since this library's proguard rules gets merged with your app's.

I'm guessing something is interfering somewhere.

**Comment by eneim** [comment]
the last statement says that the missing class was from the other guy's library ... I would like to double check the imported package of you (the issue owner).

**Comment by afollestad** [comment]
I think I found the reason.

The Proguard rules file this library has uses old package names (when the MaterialProgressBar classes were integrated into this library's code base). I will have to update the Proguard rules.

**Comment by afollestad** [comment]
@filipebezerra @alexwhb try this:

```Gradle
dependencies {

    // ... other dependencies here

    compile('com.github.afollestad.material-dialogs:core:3ebbc9549e@aar') {
        transitive = true
    }
}
```

**Comment by eneim** [comment]
Hm i forgot to check your dependencies :trollface: It includes ```me.zhanghai.android.materialprogressbar:library:1.1.4``` so yeah that might be so.

**Comment by afollestad** [comment]
If no one reports back about the solution above, I'll close this issue in a few hours.

**Comment by filipebezerra** [comment]
It works fine, and when I run ```gradle -q dependencies```:

![capturar](https://cloud.githubusercontent.com/assets/1006095/11133573/a5815ffe-897d-11e5-8e18-ff9339f4addb.PNG)

Thank you.

**Comment by filipebezerra** [comment]
Hei @alexwhb , you can include the dependencies as follows:

```
    compile (com.github.afollestad.material-dialogs:core:0.8.5.0@aar){transitive=true}
    compile (com.github.afollestad.material-dialogs:commons:0.8.5.0@aar){transitive=true}
```

**Comment by alexwhb** [comment]
@filipebezerra worked perfectly! Thank you so much! much cleaner solution. :+1:

**Comment by afollestad** [comment]
Did you guys forgot to include something before?

**Comment by alexwhb** [comment]
@afollestad I did. That was a stupid oversight on my part.

**Comment by afollestad** [comment]
Oh okay, glad you were able to figure it out!

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.1

**Comment by Zaldroc** [comment]
Is it still necessary to use transitive = true ? It doesn't say so in the docs but i still get the error above.

**Comment by ibrahim-appgodz** [comment]
**# Still now i am getting the error help me out...**

 FATAL EXCEPTION: main
                                                               Process: com.appgodz.evh, PID: 5523
                                                               java.lang.NoClassDefFoundError: me.zhanghai.android.materialprogressbar.IndeterminateCircularProgressDrawable
                                                                   at com.afollestad.materialdialogs.DialogInit.setupProgressDialog(DialogInit.java:468)
                                                                   at com.afollestad.materialdialogs.DialogInit.init(DialogInit.java:353)
                                                                   at com.afollestad.materialdialogs.MaterialDialog.<init>(MaterialDialog.java:94)
                                                                   at com.afollestad.materialdialogs.MaterialDialog$Builder.build(MaterialDialog.java:2183)

**Comment by mladenrakonjac** [comment]
I am still getting same error:

```
java.lang.NoClassDefFoundError: Failed resolution of: Lme/zhanghai/android/materialprogressbar/IndeterminateProgressDrawable;
                                                                     at com.afollestad.materialdialogs.DialogInit.setupProgressDialog(DialogInit.java:369)
                                                                     at com.afollestad.materialdialogs.DialogInit.init(DialogInit.java:297)
                                                                     at com.afollestad.materialdialogs.MaterialDialog.<init>(MaterialDialog.java:96)
                                                                     at com.afollestad.materialdialogs.MaterialDialog$Builder.build(MaterialDialog.java:1335)
                                                                     at com.afollestad.materialdialogs.MaterialDialog$Builder.show(MaterialDialog.java:1340)
```

This is how I added it:

compile('com.github.afollestad.material-dialogs:core:0.8.5.1@aar'){
        transitive = true
    }
