### ISSUE TITLE
Android says leaking windows on progress dialog

### ISSUE THREAD

**Issue by akmal** [afollestad/material-dialogs#842]
This is the code:

                vmProgress = new MaterialDialog.Builder(this)
                        .title(R.string.fetching_vm)
                        .content(R.string.please_wait)
                        .progress(true, 0)
                        .show()
                ;

Later,

                :
                vmProgress.dismiss();

This is the stack trace:

[ 11-23 16:21:29.822 3238: 3238 E/WindowManager ]

android.view.WindowLeaked: Activity com.vmware.bsky.resources.ResourcesActivity has leaked window com.android.internal.policy.PhoneWindow$DecorView{84461cf V.E...... R......D 0,0-1026,460} that was originally added here
at android.view.ViewRootImpl.(ViewRootImpl.java:368)
at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:299)
at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
at android.app.Dialog.show(Dialog.java:319)
at com.afollestad.materialdialogs.MaterialDialog.show(MaterialDialog.java:1326)
at com.afollestad.materialdialogs.MaterialDialog$Builder.show(MaterialDialog.java:1317)
at com.vmware.bsky.resources.ResourcesActivity.onCreate(ResourcesActivity.java:144)
at android.app.Activity.performCreate(Activity.java:6237)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
at android.app.ActivityThread.-wrap11(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by afollestad** [comment]
This isn't specific to this library. 

Dismiss your dialogs when your Activities close/pause.
