### ISSUE TITLE
java.lang.NoClassDefFoundError: me.zhanghai.android.materialprogressbar.HorizontalProgressDrawable

### ISSUE THREAD

**Issue by leijdekkers** [afollestad/material-dialogs#866]
Hi

I get this error with the following code. Not sure what is going on here. Was working okay in the past

```java
 mMaterialDialog = new MaterialDialog.Builder(SelectFileActivity.this)
                    .title(R.string.processing_addresses)
                    .content(R.string.please_wait)
                    .cancelable(false)
                    .progress(false, 0, true)
                    .progressIndeterminateStyle(true)
                    .show();
```

```Gradle
 java.lang.NoClassDefFoundError: me.zhanghai.android.materialprogressbar.HorizontalProgressDrawable
                                                     at com.afollestad.materialdialogs.DialogInit.setupProgressDialog(DialogInit.java:375)
                                                     at com.afollestad.materialdialogs.DialogInit.init(DialogInit.java:297)
                                                     at com.afollestad.materialdialogs.MaterialDialog.<init>(MaterialDialog.java:94)
                                                     at com.afollestad.materialdialogs.MaterialDialog$Builder.build(MaterialDialog.java:1311)
                                                     at com.afollestad.materialdialogs.MaterialDialog$Builder.show(MaterialDialog.java:1316)
```

**Comment by afollestad** [comment]
Try adding this to your app's proguard.rules file:

```Gradle
-keep class me.zhanghai.android.materialprogressbar.** { *; }
```

**Comment by leijdekkers** [comment]
Indeed that did the trick! thanks!

**Comment by ibrahim-appgodz** [comment]
this did not work for me
