### ISSUE TITLE
Used with tablayout will be reported to the wrong

### ISSUE THREAD

**Issue by l123456789jy** [afollestad/material-dialogs#890]
java.lang.NoClassDefFoundError: android.support.v7.internal.widget.TintManager
                                                       at android.support.design.widget.TabLayout$TabView.<init>(TabLayout.java:1107)
                                                       at android.support.design.widget.TabLayout.createTabView(TabLayout.java:612)
                                                       at android.support.design.widget.TabLayout.addTabView(TabLayout.java:646)
                                                       at android.support.design.widget.TabLayout.addTab(TabLayout.java:345)
                                                       at android.support.design.widget.TabLayout.addTab(TabLayout.java:320)
                                                       at android.support.design.widget.TabLayout.setTabsFromPagerAdapter(TabLayout.java:601)
                                                       at android.support.design.widget.TabLayout.setupWithViewPager(TabLayout.java:575)

**Comment by l123456789jy** [comment]
compile('com.github.afollestad.material-dialogs:core:0.8.5.3@aar') {
        transitive = false
    }
This is solved
