### ISSUE TITLE
Exception "unresolved theme attributes"

### ISSUE THREAD

**Issue by brunolopes446** [afollestad/material-dialogs#943]
Hi.

I'm getting an exception with every character I type on a material dialog:

```Gradle
Drawable android:drawable/text_cursor_material has unresolved theme attributes! Consider using Resources.getDrawable(int, Theme) or Context.getDrawable(int).
                                                                 java.lang.RuntimeException
```

This is the code I'm using:
````java
new MaterialDialog.Builder(getActivity())
                        .title("Add")
                        .content("Insert X: ")
                        .inputRangeRes(6, 11, R.color.BurlyWood)
                        .inputType(InputType.TYPE_CLASS_TEXT)
                        .input("AAAA", "", new MaterialDialog.InputCallback() {
                            @Override
                            public void onInput(MaterialDialog dialog, CharSequence input) {
                                View coordinatorLayout = getActivity().findViewById(R.id.listViewParent);
                                Snackbar snackbar = Snackbar
                                        .make(coordinatorLayout,  input + " added", Snackbar.LENGTH_LONG);
                                snackbar.show();
                            }
                        }).show();
```

So I'm getting thousands of exceptions using this library.

Happens in Android 6.0.0 and 5.0

**Comment by afollestad** [comment]
You're probably missing a dependency in your app such as AppCompat. 

I've never run into that issue, and haven't had any other reports of it.

**Comment by kevincwuu** [comment]
On my end I am running into the same bug. It's not a show stopper, but is annoying. Please fix and try to reproduce this bug.

**Comment by koskimas** [comment]
This happens to me every time I open a dialog using android 5 or 6 devices. The dialogs work perfectly, but my log fills up with these stack traces:

```
Drawable android:drawable/text_cursor_material has unresolved theme attributes! Consider using Resources.getDrawable(int, Theme) or Context.getDrawable(int).
                                                                           java.lang.RuntimeException
                                                                               at android.content.res.Resources.getDrawable(Resources.java:726)
                                                                               at android.support.v7.widget.ResourcesWrapper.getDrawable(ResourcesWrapper.java:128)
                                                                               at android.support.v7.widget.TintContextWrapper$TintResources.getDrawable(TintContextWrapper.java:70)
                                                                               at com.afollestad.materialdialogs.internal.MDTintHelper.setCursorTint(MDTintHelper.java:151)
                                                                               at com.afollestad.materialdialogs.internal.MDTintHelper.setTint(MDTintHelper.java:118)
                                                                               at com.afollestad.materialdialogs.DialogInit.setupInputDialog(DialogInit.java:428)
                                                                               at com.afollestad.materialdialogs.DialogInit.init(DialogInit.java:300)
                                                                               at com.afollestad.materialdialogs.MaterialDialog.<init>(MaterialDialog.java:95)
                                                                               at com.afollestad.materialdialogs.MaterialDialog$Builder.build(MaterialDialog.java:1334)
                                                                               at com.afollestad.materialdialogs.MaterialDialog$Builder.show(MaterialDialog.java:1339)
                                                                               at com.superoperator.superoperator.dialogs.DialogBuilderKt.observable(DialogBuilder.kt:35)
```

**Comment by koskimas** [comment]
Thanks!
