### ISSUE TITLE
Peer not authenticated error when sync Gradle on 0.8.5.5

### ISSUE THREAD

**Issue by gpulido** [afollestad/material-dialogs#967]
Hello,
I've updated to use the sdk 23.2 library and I have also updated the material-dialogs to use the 0.8.5.5 version.
I'm using android studio 2.0.0-beta5 and the gradle wraper.
The OS is Ubuntu Linux 15.10.
However I'm not able to sync the gradle project and it is throwing me a: "Peer not authenticated" error.
Reviewing the log I found the following

`Caused by: org.gradle.internal.resource.transport.http.HttpRequestException: Could not GET 'https://jitpack.io/com/github/afollestad/material-dialogs/commons/0.8.5.5/commons-0.8.5.5.pom'.
	at org.gradle.internal.resource.transport.http.HttpClientHelper.performRequest(HttpClientHelper.java:83)
	at org.gradle.internal.resource.transport.http.HttpClientHelper.performRawGet(HttpClientHelper.java:69)
	at org.gradle.internal.resource.transport.http.HttpClientHelper.performGet(HttpClientHelper.java:73)
	at org.gradle.internal.resource.transport.http.HttpResourceAccessor.openResource(HttpResourceAccessor.java:51)
	at org.gradle.internal.resource.transport.http.HttpResourceAccessor.openResource(HttpResourceAccessor.java:34)
	at org.gradle.internal.resource.transfer.DefaultExternalResourceConnector.openResource(DefaultExternalResourceConnector.java:41)
	at org.gradle.internal.resource.transfer.ProgressLoggingExternalResourceAccessor.openResource(ProgressLoggingExternalResourceAccessor.java:36)
	at org.gradle.internal.resource.transport.DefaultExternalResourceRepository.getResource(DefaultExternalResourceRepository.java:63)
	at org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor.getResource(DefaultCacheAwareExternalResourceAccessor.java:75)
	at org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver.downloadStaticResource(DefaultExternalResourceArtifactResolver.java:90)
	... 132 more
Caused by: javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:128)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:572)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:640)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
	at org.apache.http.impl.client.DecompressingHttpClient.execute(DecompressingHttpClient.java:137)
	at org.apache.http.impl.client.DecompressingHttpClient.execute(DecompressingHttpClient.java:118)
	at org.gradle.internal.resource.transport.http.HttpClientHelper.performHttpRequest(HttpClientHelper.java:113)
	at org.gradle.internal.resource.transport.http.HttpClientHelper.executeGetOrHead(HttpClientHelper.java:90)
at org.gradle.internal.resource.transport.http.HttpClientHelper.performRequest(HttpClientHelper.java:81)`

Is anything that I have missed?
Thank you for your help and support

**Comment by afollestad** [comment]
It's probably an issue with your computer or JitPack.

**Comment by afollestad** [comment]
An SSL error would suggest it's probably your computer.

**Comment by gpulido** [comment]
I already though so, but I also have other libraries that use ssl and the only one that throws me the error is this one. If I disable it on the gradle.build it synchronizes without problem.
I will try again with the new beta6 that t has been released this night (I'm on GMT time),

**Comment by gpulido** [comment]
Hello.
Just as a following up.
The problem has been solved with the 2.0.0-beta6 version of the android gradle tool.
Hope it helps anyone

**Comment by Tortel** [comment]
I had the same issue with multiple versions of the gradle tool - I fixed it by changing my JRE from openjdk7 to openjdk8 (On Arch linux)
