### ISSUE TITLE
Android 4 + support 23.2: "Error inflating class android.widget.RadioButton"

### ISSUE THREAD

**Issue by jacobras** [afollestad/material-dialogs#983]
I'm getting these crash reports:

`Fatal Exception: android.view.InflateException: Binary XML file line #14: Error inflating class android.widget.RadioButton`
`Caused by android.content.res.Resources$NotFoundException: File res/drawable/abc_btn_radio_material.xml from drawable resource ID #0x7f020008`
`Caused by android.content.res.Resources$NotFoundException: File res/drawable/abc_btn_radio_on_mtrl.xml from drawable resource ID #0x7f02000a`
`Caused by org.xmlpull.v1.XmlPullParserException: Binary XML file line #17: invalid drawable tag vector`
`       at com.afollestad.materialdialogs.DefaultAdapter.getView(DefaultAdapter.java:59)`
`       at com.afollestad.materialdialogs.internal.MDRootLayout.onMeasure(MDRootLayout.java:199)`

(Full crash report [here on Pastebin](http://pastebin.com/W0MBw5QA)).

I'm using the latest support library (23.2) and Material Dialogs (0.8.5.6) and the crash reports seem to only origin from Android 4 (34 crashes over 9 users so far).

I found this answer on StackOverflow: http://stackoverflow.com/a/35644236/425213. The RadioButton-part might be the cause of this problem.

**Comment by fichna** [comment]
I have also problem with this library and support 23.2

My problem is described on [stackoverflow](http://stackoverflow.com/questions/35628572/update-support-library-23-2-0-build-bug/35628668)

**Comment by jacobras** [comment]
@fichna for the moment I have reverted to support library 23.1.1 and Material Dialogs 0.8.5.1. Tested and works fine on Android 4.

**Comment by fichna** [comment]
Yes, I know, but problem stays...

**Comment by jacobras** [comment]
But at least it's a workaround for now ;-) I had to stop rolling out an update and now it can continue again so I will patiently wait until it's fixed.

**Comment by afollestad** [comment]
The problem was that the single choice and multi choice layouts were explicitly referencing their selectors from AppCompat resources.

AppCompat switched from using PNGs to Vectors in 23.2.0, so those drawables couldn't be inflated below Lollipop. I removed the direct use of those selectors and switched to using `AppCompatCheckBox` and `AppCompatRadioButton`.

**Comment by ShaymaaEssa** [comment]
I have the same problem even i used AppCompatRadioButton

**Comment by eincioch** [comment]
04-29 09:55:42.224 2536-2536/ev_softsa.appmedicacoorporativo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: ev_softsa.appmedicacoorporativo, PID: 2536
                                                                               java.lang.NullPointerException: Attempt to invoke virtual method 'void ev_softsa.appmedicacoorporativo.PdfManager.createPdfDocument(ev_softsa.appmedicacoorporativo.model.bean.InvoiceObject)' on a null object reference
                                                                                   at ev_softsa.appmedicacoorporativo.ActivityVerProforma$1.onClick(ActivityVerProforma.java:94)
                                                                                   at android.view.View.performClick(View.java:5198)
                                                                                   at android.view.View$PerformClick.run(View.java:21147)
                                                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by eincioch** [comment]
Solución: Cambiar <RadioButton...

y utilizar <android.support.v7.widget.AppCompatRadioButton...

Ejemplo: ahora funciona OK!..

<android.support.v7.widget.AppCompatRadioButton
                            android:layout_width="60.0dip"
                            android:layout_height="20.0dip"
                            android:layout_marginLeft="15.0dip"
                            android:layout_toRightOf="@id/rb20porc"
                            android:layout_centerHorizontal="true"
                            android:layout_centerVertical="true"
                            android:text="25%"
                            android:textColor="#f2f2dc"
                            android:id="@+id/rb25porc"/>

**Comment by Hackmodford** [comment]
I have this problem when using a API 16 simulator.

I am using appcompat-v7:24.0.0
